export const LECTURE_EXPANSION_TARGET_PROGRAMS = 25_000;
export const LECTURE_EXPANSION_TARGET_PLAYABLE_ITEMS = 50_000;

export const LECTURE_EXPANSION_MIN_AUDIO_ITEMS = 15_000;
export const LECTURE_EXPANSION_MIN_VIDEO_ITEMS = 15_000;

export const LECTURE_EXPANSION_MIN_COACHING_PROGRAMS = 2_500;
export const LECTURE_EXPANSION_MIN_COACHING_ITEMS = 5_000;
export const LECTURE_EXPANSION_MIN_COACHING_AUDIO = 1_500;
export const LECTURE_EXPANSION_MIN_COACHING_VIDEO = 1_500;

export const LECTURE_EXPANSION_DEFAULT_BATCH_SIZE = 250;
export const LECTURE_EXPANSION_MAX_BATCH_SIZE = 500;
export const LECTURE_EXPANSION_DEFAULT_VALIDATION_CONCURRENCY = 24;
export const LECTURE_EXPANSION_DEFAULT_SOURCE_CONCURRENCY = 4;
export const LECTURE_EXPANSION_DEFAULT_REQUEST_TIMEOUT_MS = 20_000;
export const LECTURE_EXPANSION_MAX_SOURCE_SHARE = 0.35;

export const LECTURE_EXPANSION_IMPORTER_VERSION = "lectures-expansion-v2";

export const LECTURE_EXPANSION_STATE_DIR = "data/lecture-expansion";
