/** ISO 3166-1 alpha-2 codes plus common territories used for coverage tracking. */
export const WORLDWIDE_COUNTRY_CODES: Array<{ code: string; name: string; region: string }> = [
  { code: "AF", name: "Afghanistan", region: "Asia" },
  { code: "AL", name: "Albania", region: "Europe" },
  { code: "DZ", name: "Algeria", region: "Africa" },
  { code: "AD", name: "Andorra", region: "Europe" },
  { code: "AO", name: "Angola", region: "Africa" },
  { code: "AR", name: "Argentina", region: "South America" },
  { code: "AM", name: "Armenia", region: "Asia" },
  { code: "AU", name: "Australia", region: "Oceania" },
  { code: "AT", name: "Austria", region: "Europe" },
  { code: "AZ", name: "Azerbaijan", region: "Asia" },
  { code: "BH", name: "Bahrain", region: "Middle East" },
  { code: "BD", name: "Bangladesh", region: "Asia" },
  { code: "BY", name: "Belarus", region: "Europe" },
  { code: "BE", name: "Belgium", region: "Europe" },
  { code: "BZ", name: "Belize", region: "Central America" },
  { code: "BJ", name: "Benin", region: "Africa" },
  { code: "BO", name: "Bolivia", region: "South America" },
  { code: "BA", name: "Bosnia and Herzegovina", region: "Europe" },
  { code: "BW", name: "Botswana", region: "Africa" },
  { code: "BR", name: "Brazil", region: "South America" },
  { code: "BN", name: "Brunei", region: "Asia" },
  { code: "BG", name: "Bulgaria", region: "Europe" },
  { code: "BF", name: "Burkina Faso", region: "Africa" },
  { code: "BI", name: "Burundi", region: "Africa" },
  { code: "KH", name: "Cambodia", region: "Asia" },
  { code: "CM", name: "Cameroon", region: "Africa" },
  { code: "CA", name: "Canada", region: "North America" },
  { code: "CV", name: "Cape Verde", region: "Africa" },
  { code: "CL", name: "Chile", region: "South America" },
  { code: "CN", name: "China", region: "Asia" },
  { code: "CO", name: "Colombia", region: "South America" },
  { code: "CR", name: "Costa Rica", region: "Central America" },
  { code: "HR", name: "Croatia", region: "Europe" },
  { code: "CU", name: "Cuba", region: "Caribbean" },
  { code: "CY", name: "Cyprus", region: "Europe" },
  { code: "CZ", name: "Czechia", region: "Europe" },
  { code: "DK", name: "Denmark", region: "Europe" },
  { code: "DO", name: "Dominican Republic", region: "Caribbean" },
  { code: "EC", name: "Ecuador", region: "South America" },
  { code: "EG", name: "Egypt", region: "Africa" },
  { code: "SV", name: "El Salvador", region: "Central America" },
  { code: "EE", name: "Estonia", region: "Europe" },
  { code: "ET", name: "Ethiopia", region: "Africa" },
  { code: "FI", name: "Finland", region: "Europe" },
  { code: "FR", name: "France", region: "Europe" },
  { code: "GA", name: "Gabon", region: "Africa" },
  { code: "GE", name: "Georgia", region: "Asia" },
  { code: "DE", name: "Germany", region: "Europe" },
  { code: "GH", name: "Ghana", region: "Africa" },
  { code: "GR", name: "Greece", region: "Europe" },
  { code: "GT", name: "Guatemala", region: "Central America" },
  { code: "HN", name: "Honduras", region: "Central America" },
  { code: "HK", name: "Hong Kong", region: "Asia" },
  { code: "HU", name: "Hungary", region: "Europe" },
  { code: "IS", name: "Iceland", region: "Europe" },
  { code: "IN", name: "India", region: "Asia" },
  { code: "ID", name: "Indonesia", region: "Asia" },
  { code: "IR", name: "Iran", region: "Middle East" },
  { code: "IQ", name: "Iraq", region: "Middle East" },
  { code: "IE", name: "Ireland", region: "Europe" },
  { code: "IL", name: "Israel", region: "Middle East" },
  { code: "IT", name: "Italy", region: "Europe" },
  { code: "JM", name: "Jamaica", region: "Caribbean" },
  { code: "JP", name: "Japan", region: "Asia" },
  { code: "JO", name: "Jordan", region: "Middle East" },
  { code: "KZ", name: "Kazakhstan", region: "Asia" },
  { code: "KE", name: "Kenya", region: "Africa" },
  { code: "KW", name: "Kuwait", region: "Middle East" },
  { code: "LV", name: "Latvia", region: "Europe" },
  { code: "LB", name: "Lebanon", region: "Middle East" },
  { code: "LY", name: "Libya", region: "Africa" },
  { code: "LT", name: "Lithuania", region: "Europe" },
  { code: "LU", name: "Luxembourg", region: "Europe" },
  { code: "MO", name: "Macao", region: "Asia" },
  { code: "MK", name: "North Macedonia", region: "Europe" },
  { code: "MG", name: "Madagascar", region: "Africa" },
  { code: "MY", name: "Malaysia", region: "Asia" },
  { code: "ML", name: "Mali", region: "Africa" },
  { code: "MT", name: "Malta", region: "Europe" },
  { code: "MX", name: "Mexico", region: "North America" },
  { code: "MD", name: "Moldova", region: "Europe" },
  { code: "MN", name: "Mongolia", region: "Asia" },
  { code: "ME", name: "Montenegro", region: "Europe" },
  { code: "MA", name: "Morocco", region: "Africa" },
  { code: "MZ", name: "Mozambique", region: "Africa" },
  { code: "MM", name: "Myanmar", region: "Asia" },
  { code: "NA", name: "Namibia", region: "Africa" },
  { code: "NP", name: "Nepal", region: "Asia" },
  { code: "NL", name: "Netherlands", region: "Europe" },
  { code: "NZ", name: "New Zealand", region: "Oceania" },
  { code: "NI", name: "Nicaragua", region: "Central America" },
  { code: "NG", name: "Nigeria", region: "Africa" },
  { code: "NO", name: "Norway", region: "Europe" },
  { code: "OM", name: "Oman", region: "Middle East" },
  { code: "PK", name: "Pakistan", region: "Asia" },
  { code: "PS", name: "Palestine", region: "Middle East" },
  { code: "PA", name: "Panama", region: "Central America" },
  { code: "PY", name: "Paraguay", region: "South America" },
  { code: "PE", name: "Peru", region: "South America" },
  { code: "PH", name: "Philippines", region: "Asia" },
  { code: "PL", name: "Poland", region: "Europe" },
  { code: "PT", name: "Portugal", region: "Europe" },
  { code: "PR", name: "Puerto Rico", region: "Caribbean" },
  { code: "QA", name: "Qatar", region: "Middle East" },
  { code: "RO", name: "Romania", region: "Europe" },
  { code: "RU", name: "Russia", region: "Europe" },
  { code: "RW", name: "Rwanda", region: "Africa" },
  { code: "SA", name: "Saudi Arabia", region: "Middle East" },
  { code: "SN", name: "Senegal", region: "Africa" },
  { code: "RS", name: "Serbia", region: "Europe" },
  { code: "SG", name: "Singapore", region: "Asia" },
  { code: "SK", name: "Slovakia", region: "Europe" },
  { code: "SI", name: "Slovenia", region: "Europe" },
  { code: "ZA", name: "South Africa", region: "Africa" },
  { code: "KR", name: "South Korea", region: "Asia" },
  { code: "ES", name: "Spain", region: "Europe" },
  { code: "LK", name: "Sri Lanka", region: "Asia" },
  { code: "SD", name: "Sudan", region: "Africa" },
  { code: "SE", name: "Sweden", region: "Europe" },
  { code: "CH", name: "Switzerland", region: "Europe" },
  { code: "SY", name: "Syria", region: "Middle East" },
  { code: "TW", name: "Taiwan", region: "Asia" },
  { code: "TZ", name: "Tanzania", region: "Africa" },
  { code: "TH", name: "Thailand", region: "Asia" },
  { code: "TN", name: "Tunisia", region: "Africa" },
  { code: "TR", name: "Turkey", region: "Middle East" },
  { code: "UG", name: "Uganda", region: "Africa" },
  { code: "UA", name: "Ukraine", region: "Europe" },
  { code: "AE", name: "United Arab Emirates", region: "Middle East" },
  { code: "GB", name: "United Kingdom", region: "Europe" },
  { code: "US", name: "United States", region: "North America" },
  { code: "UY", name: "Uruguay", region: "South America" },
  { code: "UZ", name: "Uzbekistan", region: "Asia" },
  { code: "VE", name: "Venezuela", region: "South America" },
  { code: "VN", name: "Vietnam", region: "Asia" },
  { code: "YE", name: "Yemen", region: "Middle East" },
  { code: "ZM", name: "Zambia", region: "Africa" },
  { code: "ZW", name: "Zimbabwe", region: "Africa" },
  { code: "GL", name: "Greenland", region: "North America" },
  { code: "FO", name: "Faroe Islands", region: "Europe" },
  { code: "GI", name: "Gibraltar", region: "Europe" },
  { code: "GP", name: "Guadeloupe", region: "Caribbean" },
  { code: "GF", name: "French Guiana", region: "South America" },
  { code: "MQ", name: "Martinique", region: "Caribbean" },
  { code: "RE", name: "Réunion", region: "Africa" },
  { code: "PF", name: "French Polynesia", region: "Pacific Islands" },
  { code: "NC", name: "New Caledonia", region: "Pacific Islands" },
  { code: "GU", name: "Guam", region: "Pacific Islands" },
  { code: "AS", name: "American Samoa", region: "Pacific Islands" },
  { code: "XK", name: "Kosovo", region: "Europe" },
  // Priority under-covered partitions (Africa, Caribbean, Central Asia, Pacific)
  { code: "AG", name: "Antigua and Barbuda", region: "Caribbean" },
  { code: "BB", name: "Barbados", region: "Caribbean" },
  { code: "BS", name: "Bahamas", region: "Caribbean" },
  { code: "DM", name: "Dominica", region: "Caribbean" },
  { code: "GD", name: "Grenada", region: "Caribbean" },
  { code: "HT", name: "Haiti", region: "Caribbean" },
  { code: "KN", name: "Saint Kitts and Nevis", region: "Caribbean" },
  { code: "LC", name: "Saint Lucia", region: "Caribbean" },
  { code: "TT", name: "Trinidad and Tobago", region: "Caribbean" },
  { code: "VC", name: "Saint Vincent and the Grenadines", region: "Caribbean" },
  { code: "KY", name: "Cayman Islands", region: "Caribbean" },
  { code: "BM", name: "Bermuda", region: "Caribbean" },
  { code: "AW", name: "Aruba", region: "Caribbean" },
  { code: "CW", name: "Curaçao", region: "Caribbean" },
  { code: "SX", name: "Sint Maarten", region: "Caribbean" },
  { code: "TC", name: "Turks and Caicos Islands", region: "Caribbean" },
  { code: "VG", name: "British Virgin Islands", region: "Caribbean" },
  { code: "VI", name: "U.S. Virgin Islands", region: "Caribbean" },
  { code: "FJ", name: "Fiji", region: "Pacific Islands" },
  { code: "PG", name: "Papua New Guinea", region: "Pacific Islands" },
  { code: "SB", name: "Solomon Islands", region: "Pacific Islands" },
  { code: "VU", name: "Vanuatu", region: "Pacific Islands" },
  { code: "TO", name: "Tonga", region: "Pacific Islands" },
  { code: "WS", name: "Samoa", region: "Pacific Islands" },
  { code: "KI", name: "Kiribati", region: "Pacific Islands" },
  { code: "TV", name: "Tuvalu", region: "Pacific Islands" },
  { code: "NR", name: "Nauru", region: "Pacific Islands" },
  { code: "FM", name: "Micronesia", region: "Pacific Islands" },
  { code: "MH", name: "Marshall Islands", region: "Pacific Islands" },
  { code: "PW", name: "Palau", region: "Pacific Islands" },
  { code: "CK", name: "Cook Islands", region: "Pacific Islands" },
  { code: "NU", name: "Niue", region: "Pacific Islands" },
  { code: "TK", name: "Tokelau", region: "Pacific Islands" },
  { code: "KG", name: "Kyrgyzstan", region: "Central Asia" },
  { code: "TJ", name: "Tajikistan", region: "Central Asia" },
  { code: "TM", name: "Turkmenistan", region: "Central Asia" },
  { code: "CI", name: "Côte d'Ivoire", region: "Africa" },
  { code: "CD", name: "DR Congo", region: "Africa" },
  { code: "CG", name: "Congo", region: "Africa" },
  { code: "NE", name: "Niger", region: "Africa" },
  { code: "TD", name: "Chad", region: "Africa" },
  { code: "TG", name: "Togo", region: "Africa" },
  { code: "SL", name: "Sierra Leone", region: "Africa" },
  { code: "LR", name: "Liberia", region: "Africa" },
  { code: "GM", name: "Gambia", region: "Africa" },
  { code: "GN", name: "Guinea", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", region: "Africa" },
  { code: "MR", name: "Mauritania", region: "Africa" },
  { code: "ER", name: "Eritrea", region: "Africa" },
  { code: "DJ", name: "Djibouti", region: "Africa" },
  { code: "SO", name: "Somalia", region: "Africa" },
  { code: "SS", name: "South Sudan", region: "Africa" },
  { code: "SZ", name: "Eswatini", region: "Africa" },
  { code: "LS", name: "Lesotho", region: "Africa" },
  { code: "MW", name: "Malawi", region: "Africa" },
  { code: "SC", name: "Seychelles", region: "Africa" },
  { code: "KM", name: "Comoros", region: "Africa" },
  { code: "ST", name: "São Tomé and Príncipe", region: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", region: "Africa" },
  { code: "CF", name: "Central African Republic", region: "Africa" },
  { code: "LA", name: "Laos", region: "Asia" },
  { code: "BT", name: "Bhutan", region: "Asia" },
  { code: "TL", name: "Timor-Leste", region: "Asia" },
  { code: "MV", name: "Maldives", region: "Asia" },
];

const COUNTRY_CODE_SET = new Set(WORLDWIDE_COUNTRY_CODES.map((entry) => entry.code));

export type Wave4CountryCode = string | null;

/** Normalize M3U / seed country values to a known ISO alpha-2 code or null. */
export function normalizeWave4CountryCode(
  value: string | null | undefined,
  fallbackCode?: string | null
): Wave4CountryCode {
  const candidates = [value, fallbackCode]
    .map((item) => String(item || "").trim().toUpperCase())
    .filter(Boolean);

  for (const raw of candidates) {
    const token = raw.split(/[,;/|]/)[0]?.trim() || "";
    if (!token) continue;
    if (COUNTRY_CODE_SET.has(token)) return token;
    if (token.length === 3) {
      const alpha2 = token.slice(0, 2);
      if (COUNTRY_CODE_SET.has(alpha2)) return alpha2;
    }
  }

  return null;
}

export function isKnownCountryCode(code: string | null | undefined) {
  return COUNTRY_CODE_SET.has(String(code || "").trim().toUpperCase());
}

export function regionForCountryCode(code: string | null | undefined) {
  const row = WORLDWIDE_COUNTRY_CODES.find((entry) => entry.code === String(code || "").toUpperCase());
  return row?.region || "International";
}
