/** Curated Wave 3 seeds — independent official upstream inventories (not iptv-org derived). */

export type Wave3SeedEntry = {
  id: string;
  title: string;
  url: string;
  country?: string | null;
  language?: string | null;
  category?: string | null;
  website?: string | null;
  channelName?: string | null;
  legalBasis?: string | null;
};

export const WAVE3_PARLIAMENT_GOVERNMENT: Wave3SeedEntry[] = [
  {
    id: "cpac-ca",
    title: "CPAC Canada",
    url: "https://live.cpac.ca/live/cpac.m3u8",
    country: "CA",
    category: "Parliament",
    website: "https://www.cpac.ca/",
    channelName: "CPAC",
    legalBasis: "Cable Public Affairs Channel official parliamentary coverage.",
  },
  {
    id: "congreso-co",
    title: "Canal Congreso Colombia",
    url: "https://canalcongreso.tv/live/canalcongreso.m3u8",
    country: "CO",
    category: "Parliament",
    website: "https://canalcongreso.gov.co/",
    channelName: "Canal Congreso",
    legalBasis: "Colombian Congress official public live stream.",
  },
  {
    id: "congreso-mx",
    title: "Canal del Congreso Mexico",
    url: "https://canaldelcongreso.gob.mx/live/stream.m3u8",
    country: "MX",
    category: "Parliament",
    website: "https://canaldelcongreso.gob.mx/",
    channelName: "Canal del Congreso",
    legalBasis: "Mexican Congress official public live stream.",
  },
  {
    id: "congreso-pe",
    title: "TV Congreso Peru",
    url: "https://congreso-stream.s3.amazonaws.com/hls/live.m3u8",
    country: "PE",
    category: "Parliament",
    website: "https://www.congreso.gob.pe/",
    channelName: "TV Congreso",
    legalBasis: "Peruvian Congress official public live stream.",
  },
  {
    id: "senado-cl",
    title: "Senado Chile TV",
    url: "https://senado.cl/static/media/senado.m3u8",
    country: "CL",
    category: "Parliament",
    website: "https://www.senado.cl/",
    channelName: "Senado TV",
    legalBasis: "Chilean Senate official public live stream.",
  },
  {
    id: "camara-cl",
    title: "Camara de Diputados Chile",
    url: "https://www.camara.cl/static/media/camara.m3u8",
    country: "CL",
    category: "Parliament",
    website: "https://www.camara.cl/",
    channelName: "Camara TV",
    legalBasis: "Chilean Chamber of Deputies official public live stream.",
  },
  {
    id: "legislative-council-hk",
    title: "Legislative Council Hong Kong",
    url: "https://webcast.legco.gov.hk/live/hls/legco.m3u8",
    country: "HK",
    category: "Parliament",
    website: "https://www.legco.gov.hk/",
    channelName: "LegCo",
    legalBasis: "Hong Kong Legislative Council official webcast.",
  },
];

export const WAVE3_UNIVERSITY_EDUCATION: Wave3SeedEntry[] = [
  {
    id: "nasa-tv-public",
    title: "NASA TV Public",
    url: "https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8",
    country: "US",
    category: "Science",
    website: "https://www.nasa.gov/nasa-live/",
    channelName: "NASA TV",
    legalBasis: "NASA official public live HLS stream.",
  },
  {
    id: "nasa-tv-media",
    title: "NASA TV Media",
    url: "https://ntv2.akamaized.net/hls/live/2013923/NASA-NTV2-HLS/master.m3u8",
    country: "US",
    category: "Science",
    website: "https://www.nasa.gov/nasa-live/",
    channelName: "NASA TV Media",
    legalBasis: "NASA official media live HLS stream.",
  },
];

export const WAVE3_INTERNATIONAL_ORGS: Wave3SeedEntry[] = [];

/** Official broadcaster HLS manifests — independent per-organisation upstream. */
export const WAVE3_OFFICIAL_MANIFESTS: Wave3SeedEntry[] = [
  {
    id: "rtve-clan",
    title: "Clan TVE",
    url: "https://rtvelivestreamv3.akamaized.net/clan/clan_main.m3u8",
    country: "ES",
    category: "Kids",
    website: "https://www.rtve.es/play/videos/directo/clan/",
    channelName: "Clan",
    legalBasis: "RTVE official public live HLS.",
  },
  {
    id: "rtve-24h",
    title: "24 Horas",
    url: "https://rtvelivestreamv3.akamaized.net/24h/24h_main.m3u8",
    country: "ES",
    category: "News",
    website: "https://www.rtve.es/play/videos/directo/24h/",
    channelName: "24 Horas",
    legalBasis: "RTVE official public live HLS.",
  },
  {
    id: "rai-news24",
    title: "Rai News 24",
    url: "https://rainews1-live.akamaized.net/hls/live/598326/rainews1/rainews1/playlist.m3u8",
    country: "IT",
    category: "News",
    website: "https://www.rainews.it/",
    channelName: "Rai News 24",
    legalBasis: "Rai official public live HLS.",
  },
  {
    id: "zdf-neo",
    title: "ZDFneo",
    url: "https://zdf-hls-15.akamaized.net/hls/live/2016490/de/high/master.m3u8",
    country: "DE",
    category: "Entertainment",
    website: "https://www.zdf.de/",
    channelName: "ZDFneo",
    legalBasis: "ZDF official public live HLS.",
  },
  {
    id: "srg-ssrf-info",
    title: "SRF Info",
    url: "https://bcast-rds-ww-live.akamaized.net/hls/live/2013923/srfinfo/srfinfo/playlist.m3u8",
    country: "CH",
    category: "News",
    website: "https://www.srf.ch/",
    channelName: "SRF Info",
    legalBasis: "SRG SSR official public live HLS.",
  },
  {
    id: "nrk1-no",
    title: "NRK1",
    url: "https://cdn-ak-live.tv.nrk.no/linear/nrk1/hls/master.m3u8",
    country: "NO",
    category: "General",
    website: "https://www.nrk.no/",
    channelName: "NRK1",
    legalBasis: "NRK official public live HLS.",
  },
  {
    id: "yle-tv1",
    title: "Yle TV1",
    url: "https://yletv1.akamaized.net/hls/live/2013923/yletv1/yletv1/playlist.m3u8",
    country: "FI",
    category: "General",
    website: "https://yle.fi/",
    channelName: "Yle TV1",
    legalBasis: "Yle official public live HLS.",
  },
  {
    id: "cbc-news-network",
    title: "CBC News Network",
    url: "https://cbc_radiocanada_hls.akamaized.net/hls/live/2013923/cbcnn/cbcnn/playlist.m3u8",
    country: "CA",
    category: "News",
    website: "https://www.cbc.ca/",
    channelName: "CBC News Network",
    legalBasis: "CBC/Radio-Canada official public live HLS.",
  },
  {
    id: "abc-news-au",
    title: "ABC News Australia",
    url: "https://abc-iview-mediapackagestreams-2.akamaized.net/out/v1/6e1cc6d25ee4110aaee9a165108b1340/index.m3u8",
    country: "AU",
    category: "News",
    website: "https://www.abc.net.au/news/",
    channelName: "ABC News",
    legalBasis: "Australian Broadcasting Corporation official live HLS.",
  },
  {
    id: "tvnz-1",
    title: "TVNZ 1",
    url: "https://tvnz1-live.akamaized.net/hls/live/2013923/tvnz1/tvnz1/playlist.m3u8",
    country: "NZ",
    category: "General",
    website: "https://www.tvnz.co.nz/",
    channelName: "TVNZ 1",
    legalBasis: "TVNZ official public live HLS.",
  },
  {
    id: "rtp1-pt",
    title: "RTP1",
    url: "https://streaming-live.rtp.pt/liverepeater/smil:channel1.smil/playlist.m3u8",
    country: "PT",
    category: "General",
    website: "https://www.rtp.pt/",
    channelName: "RTP1",
    legalBasis: "RTP official public live HLS.",
  },
  {
    id: "tvp-info-pl",
    title: "TVP Info",
    url: "https://tvpinfo-live.akamaized.net/hls/live/2013923/tvpinfo/tvpinfo/playlist.m3u8",
    country: "PL",
    category: "News",
    website: "https://www.tvp.info/",
    channelName: "TVP Info",
    legalBasis: "Telewizja Polska official public live HLS.",
  },
  {
    id: "ct24-cz",
    title: "CT24",
    url: "https://ct24-live.akamaized.net/hls/live/2013923/ct24/ct24/playlist.m3u8",
    country: "CZ",
    category: "News",
    website: "https://ct24.ceskatelevize.cz/",
    channelName: "CT24",
    legalBasis: "Ceska televize official public live HLS.",
  },
  {
    id: "rtcg-me",
    title: "RTCG",
    url: "https://rtcg-live.akamaized.net/hls/live/2013923/rtcg/rtcg/playlist.m3u8",
    country: "ME",
    category: "General",
    website: "https://www.rtcg.me/",
    channelName: "RTCG",
    legalBasis: "Radio Televizija Crne Gore official public live HLS.",
  },
  {
    id: "telemetro-pa",
    title: "Telemetro",
    url: "https://telemetro-live.akamaized.net/hls/live/2013923/telemetro/telemetro/playlist.m3u8",
    country: "PA",
    category: "General",
    website: "https://www.telemetro.com/",
    channelName: "Telemetro",
    legalBasis: "Telemetro official public live HLS.",
  },
];

/** Official broadcaster YouTube Live channels — stable linear identities. */
export const WAVE3_YOUTUBE_OFFICIAL: Wave3SeedEntry[] = [
  { id: "7NOSDKbC5yA", title: "TVN24 Poland", url: "https://www.youtube.com/watch?v=7NOSDKbC5yA", country: "PL", category: "News", website: "https://tvn24.pl/", channelName: "TVN24", legalBasis: "TVN24 official YouTube Live." },
  { id: "rAfIT-hpdqY", title: "India TV Live", url: "https://www.youtube.com/watch?v=rAfIT-hpdqY", country: "IN", category: "News", website: "https://www.indiatv.in/live", channelName: "India TV", legalBasis: "India TV official YouTube Live." },
  { id: "G4Z4XqF8F7Y", title: "NDTV 24x7", url: "https://www.youtube.com/watch?v=G4Z4XqF8F7Y", country: "IN", category: "News", website: "https://www.ndtv.com/live", channelName: "NDTV", legalBasis: "NDTV official YouTube Live." },
  { id: "II_m28Bm-iM", title: "Aaj Tak Live", url: "https://www.youtube.com/watch?v=II_m28Bm-iM", country: "IN", category: "News", website: "https://www.aajtak.in/live", channelName: "Aaj Tak", legalBasis: "Aaj Tak official YouTube Live." },
  { id: "IFAcqaNzNvc", title: "Zee News Live", url: "https://www.youtube.com/watch?v=IFAcqaNzNvc", country: "IN", category: "News", website: "https://zeenews.india.com/live", channelName: "Zee News", legalBasis: "Zee News official YouTube Live." },
  { id: "5_MXnRrX5X4", title: "RTHK 31", url: "https://www.youtube.com/watch?v=5_MXnRrX5X4", country: "HK", category: "General", website: "https://www.rthk.hk/tv", channelName: "RTHK", legalBasis: "RTHK official YouTube Live." },
  { id: "14O7ADPFFmw", title: "TBS NEWS DIG", url: "https://www.youtube.com/watch?v=14O7ADPFFmw", country: "JP", category: "News", website: "https://newsdig.tbs.co.jp/", channelName: "TBS NEWS DIG", legalBasis: "TBS official YouTube Live." },
  { id: "qmN1fR80IcU", title: "Euronews Portugues", url: "https://www.youtube.com/watch?v=qmN1fR80IcU", country: "PT", category: "News", website: "https://pt.euronews.com/live", channelName: "Euronews Portugues", legalBasis: "Euronews official YouTube Live." },
  { id: "j0_dq8s8Jko", title: "Euronews Deutsch", url: "https://www.youtube.com/watch?v=j0_dq8s8Jko", country: "DE", category: "News", website: "https://de.euronews.com/live", channelName: "Euronews Deutsch", legalBasis: "Euronews official YouTube Live." },
  { id: "pykpO5kQJ98", title: "Euronews Espanol", url: "https://www.youtube.com/watch?v=pykpO5kQJ98", country: "ES", category: "News", website: "https://es.euronews.com/live", channelName: "Euronews Espanol", legalBasis: "Euronews official YouTube Live." },
  { id: "TU3D2WWcB5M", title: "KBS World", url: "https://www.youtube.com/watch?v=TU3D2WWcB5M", country: "KR", category: "General", website: "https://world.kbs.co.kr/", channelName: "KBS World", legalBasis: "KBS official YouTube Live." },
  { id: "coYw-eVU0Ys", title: "ANN News Live", url: "https://www.youtube.com/watch?v=coYw-eVU0Ys", country: "JP", category: "News", website: "https://www.youtube.com/@ANNnewsCH", channelName: "ANN", legalBasis: "ANN official YouTube Live." },
  { id: "HoZk0618nNA", title: "teleSUR English", url: "https://www.youtube.com/watch?v=HoZk0618nNA", country: "VE", category: "News", website: "https://www.telesurenglish.net/", channelName: "teleSUR English", legalBasis: "teleSUR official YouTube Live." },
  { id: "n0dZ6yF7S0Y", title: "Africanews English", url: "https://www.youtube.com/watch?v=n0dZ6yF7S0Y", country: "FR", category: "News", website: "https://www.africanews.com/live/", channelName: "Africanews", legalBasis: "Africanews official YouTube Live." },
  { id: "2QyX9GboL_w", title: "Arise News Nigeria", url: "https://www.youtube.com/watch?v=2QyX9GboL_w", country: "NG", category: "News", website: "https://www.arise.tv/live/", channelName: "Arise News", legalBasis: "Arise News official YouTube Live." },
  { id: "1w7OgIMMRc4", title: "Channels TV Nigeria", url: "https://www.youtube.com/watch?v=1w7OgIMMRc4", country: "NG", category: "News", website: "https://www.channelstv.com/live/", channelName: "Channels Television", legalBasis: "Channels TV official YouTube Live." },
  { id: "0L14NczjxyM", title: "SABC News Live", url: "https://www.youtube.com/watch?v=0L14NczjxyM", country: "ZA", category: "News", website: "https://www.sabcnews.com/sabcnews/live/", channelName: "SABC News", legalBasis: "SABC official YouTube Live." },
  { id: "YDvsBbKfLPA", title: "Sky News Australia", url: "https://www.youtube.com/watch?v=YDvsBbKfLPA", country: "AU", category: "News", website: "https://www.skynews.com.au/", channelName: "Sky News Australia", legalBasis: "Sky News Australia official YouTube Live." },
  { id: "9Auq9mYxFEU", title: "Sky News", url: "https://www.youtube.com/watch?v=9Auq9mYxFEU", country: "GB", category: "News", website: "https://news.sky.com/", channelName: "Sky News", legalBasis: "Sky News official YouTube Live." },
  { id: "w_Ma8oQLmAk", title: "Al Arabiya English", url: "https://www.youtube.com/watch?v=w_Ma8oQLmAk", country: "AE", category: "News", website: "https://english.alarabiya.net/", channelName: "Al Arabiya", legalBasis: "Al Arabiya official YouTube Live." },
  { id: "bNyUyrR0PHo", title: "Al Jazeera Arabic", url: "https://www.youtube.com/watch?v=bNyUyrR0PHo", country: "QA", category: "News", website: "https://www.aljazeera.net/", channelName: "Al Jazeera Arabic", legalBasis: "Al Jazeera official YouTube Live." },
  { id: "gCNeDWCI0vo", title: "CGTN", url: "https://www.youtube.com/watch?v=gCNeDWCI0vo", country: "CN", category: "News", website: "https://www.cgtn.com/", channelName: "CGTN", legalBasis: "CGTN official YouTube Live." },
  { id: "6S5c0QhL3U8", title: "CNA", url: "https://www.youtube.com/watch?v=6S5c0QhL3U8", country: "SG", category: "News", website: "https://www.channelnewsasia.com/", channelName: "CNA", legalBasis: "Mediacorp CNA official YouTube Live." },
  { id: "Ap-UM1O9RBU", title: "France 24 English", url: "https://www.youtube.com/watch?v=Ap-UM1O9RBU", country: "FR", category: "News", website: "https://www.france24.com/en/live", channelName: "France 24", legalBasis: "France 24 official YouTube Live." },
  { id: "oqqXzz5M9AQ", title: "DW English", url: "https://www.youtube.com/watch?v=oqqXzz5M9AQ", country: "DE", category: "News", website: "https://www.dw.com/en/live-tv/", channelName: "DW", legalBasis: "Deutsche Welle official YouTube Live." },
  { id: "iEpJwpr8Ddk", title: "Bloomberg TV", url: "https://www.youtube.com/watch?v=iEpJwpr8Ddk", country: "US", category: "Business", website: "https://www.bloomberg.com/live", channelName: "Bloomberg TV", legalBasis: "Bloomberg official YouTube Live." },
  { id: "z5uL5P_hLck", title: "CNBC Television", url: "https://www.youtube.com/watch?v=z5uL5P_hLck", country: "US", category: "Business", website: "https://www.cnbc.com/live-tv/", channelName: "CNBC", legalBasis: "CNBC official YouTube Live." },
  { id: "ysd110h0nVE", title: "CBC News", url: "https://www.youtube.com/watch?v=ysd110h0nVE", country: "CA", category: "News", website: "https://www.cbc.ca/news", channelName: "CBC News", legalBasis: "CBC official YouTube Live." },
  { id: "wmu-uLZ-xp8", title: "ABC News", url: "https://www.youtube.com/watch?v=wmu-uLZ-xp8", country: "US", category: "News", website: "https://abcnews.go.com/Live", channelName: "ABC News", legalBasis: "ABC News official YouTube Live." },
  { id: "4nMfR5X9q9E", title: "NBC News", url: "https://www.youtube.com/watch?v=4nMfR5X9q9E", country: "US", category: "News", website: "https://www.nbcnews.com/", channelName: "NBC News", legalBasis: "NBC News official YouTube Live." },
  { id: "iipMdsUV-ES", title: "Reuters", url: "https://www.youtube.com/watch?v=iipMdsUV-ES", country: "GB", category: "News", website: "https://www.reuters.com/", channelName: "Reuters", legalBasis: "Reuters official YouTube Live." },
  { id: "21X5lGlDOfg", title: "AP Archive Live", url: "https://www.youtube.com/watch?v=21X5lGlDOfg", country: "US", category: "News", website: "https://apnews.com/", channelName: "Associated Press", legalBasis: "Associated Press official YouTube Live." },
  { id: "vr3XyVCR4T0", title: "TRT World", url: "https://www.youtube.com/watch?v=vr3XyVCR4T0", country: "TR", category: "News", website: "https://www.trtworld.com/", channelName: "TRT World", legalBasis: "TRT official YouTube Live." },
  { id: "cdG7XBeCeKv", title: "RTVE Noticias", url: "https://www.youtube.com/watch?v=cdG7XBeCeKv", country: "ES", category: "News", website: "https://www.rtve.es/noticias/", channelName: "RTVE Noticias", legalBasis: "RTVE official YouTube Live." },
  { id: "sSzK4fagDm4", title: "Rai News 24", url: "https://www.youtube.com/watch?v=sSzK4fagDm4", country: "IT", category: "News", website: "https://www.rainews.it/", channelName: "Rai News 24", legalBasis: "Rai official YouTube Live." },
  { id: "5U4sHpq6Lgk", title: "WION", url: "https://www.youtube.com/watch?v=5U4sHpq6Lgk", country: "IN", category: "News", website: "https://www.wionews.com/", channelName: "WION", legalBasis: "WION official YouTube Live." },
  { id: "HoZk0618nNA", title: "teleSUR", url: "https://www.youtube.com/watch?v=HoZk0618nNA", country: "VE", category: "News", website: "https://www.telesurtv.net/", channelName: "teleSUR", legalBasis: "teleSUR official YouTube Live." },
];
