/**
 * Batch 2 wave B — additional worldwide official discovery handles.
 * Never invent channel IDs; store handles/URLs only until resolved.
 */

import type { ConcertWaveSeed } from "./batch2SourceWave";

const YT = (
  key: string,
  name: string,
  handle: string,
  country: string,
  langs: string[],
  type: ConcertWaveSeed["providerType"],
  category: string,
  officialUrl: string,
  owner?: string
): ConcertWaveSeed => ({
  stableKey: key,
  name,
  provider: "youtube",
  providerType: type,
  countryCode: country,
  languageCodes: langs,
  officialUrl,
  mediaChannelUrl: `https://www.youtube.com/@${handle.replace(/^@/, "")}`,
  providerChannelId: null,
  category,
  sourceOwner: owner || name,
});

export const CONCERT_BATCH2_WAVE_B_SEEDS: ConcertWaveSeed[] = [
  // Africa
  YT("cape-town-phil", "Cape Town Philharmonic", "CapeTownPhilharmonic", "ZA", ["en"], "orchestra", "orchestra", "https://www.cpo.org.za/"),
  YT("johannesburg-phil", "Johannesburg Philharmonic", "JohannesburgPhilharmonic", "ZA", ["en"], "orchestra", "orchestra", "https://www.jpo.co.za/"),
  YT("joburg-theatre", "Joburg Theatre", "JoburgTheatre", "ZA", ["en"], "official_venue", "venue", "https://www.joburgtheatre.com/"),
  YT("afrochella", "Afrochella", "Afrochella", "GH", ["en"], "official_festival", "festival", "https://afrochella.com/"),
  YT("detty-december", "Detty December Accra", "DettyDecember", "GH", ["en"], "official_festival", "festival", "https://www.dettydecember.com/"),
  YT("lagos-jazz", "Lagos International Jazz Festival", "LagosJazzFest", "NG", ["en"], "official_festival", "jazz", "https://www.lagosjazzfestival.com/"),
  YT("felabration", "Felabration", "Felabration", "NG", ["en"], "official_festival", "festival", "https://felabration.net/"),
  YT("nairobi-orchestra", "Nairobi Orchestra", "NairobiOrchestra", "KE", ["en"], "orchestra", "orchestra", "https://www.nairoborchestra.com/"),
  YT("cairo-opera", "Cairo Opera House", "CairoOperaHouse", "EG", ["ar", "en"], "opera_house", "opera", "https://www.cairoopera.org/"),
  YT("mawlid", "Egyptian Opera / Mawlid cultural", "CairoOpera", "EG", ["ar", "en"], "cultural_institution", "cultural", "https://www.cairoopera.org/"),
  YT("morocco-mawazine", "Mawazine Festival", "MawazineFestival", "MA", ["fr", "ar", "en"], "official_festival", "festival", "https://www.festivalmawazine.ma/"),
  YT("essaouira-gnawa", "Essaouira Gnawa Festival", "FestivalGnaoua", "MA", ["fr", "ar"], "official_festival", "festival", "https://www.festival-gnaoua.net/"),
  YT("tunis-carthage", "Carthage Music Days", "CarthageMusic", "TN", ["fr", "ar"], "official_festival", "festival", "https://www.festivaldecarthage.tn/"),
  YT("sauti-za-busara", "Sauti za Busara", "SautizaBusara", "TZ", ["en", "sw"], "official_festival", "festival", "https://www.busaramusic.org/"),

  // Middle East / Central Asia
  YT("israel-phil", "Israel Philharmonic", "IsraelPhilharmonic", "IL", ["he", "en"], "orchestra", "orchestra", "https://www.ipo.co.il/"),
  YT("dubai-opera", "Dubai Opera", "DubaiOpera", "AE", ["en", "ar"], "opera_house", "opera", "https://www.dubaiopera.com/"),
  YT("abu-dhabi-classics", "Abu Dhabi Classics", "AbuDhabiClassics", "AE", ["en", "ar"], "cultural_institution", "classical", "https://www.abudhabiclassics.com/"),
  YT("qatar-phil", "Qatar Philharmonic", "QatarPhilharmonic", "QA", ["en", "ar"], "orchestra", "orchestra", "https://www.qatarphilharmonicorchestra.org/"),
  YT("riyadh-season", "Riyadh Season Music", "RiyadhSeason", "SA", ["ar", "en"], "official_festival", "festival", "https://riyadhseason.sa/"),
  YT("byblos-festival", "Byblos International Festival", "ByblosFestival", "LB", ["en", "ar", "fr"], "official_festival", "festival", "https://www.byblosfestival.org/"),
  YT("baalbeck", "Baalbeck International Festival", "BaalbeckFestival", "LB", ["en", "ar", "fr"], "official_festival", "festival", "https://www.baalbeck.org.lb/"),

  // South / SE Asia
  YT("mumbai-nCPA", "NCPA Mumbai", "NCPAMumbai", "IN", ["en", "hi"], "cultural_institution", "cultural", "https://www.ncpamumbai.com/"),
  YT("symphony-orchestra-india", "Symphony Orchestra of India", "SymphonyOrchestraIndia", "IN", ["en"], "orchestra", "orchestra", "https://soi.org.in/"),
  YT("nh7-weekender", "NH7 Weekender", "NH7Weekender", "IN", ["en"], "official_festival", "festival", "https://nh7.in/"),
  YT("sunburn", "Sunburn Festival", "SunburnFestival", "IN", ["en"], "official_festival", "dj", "https://sunburn.in/"),
  YT("magnetic-fields", "Magnetic Fields Festival", "MagneticFieldsFest", "IN", ["en"], "official_festival", "festival", "https://www.magneticfields.in/"),
  YT("bangladesh-shilpakala", "Bangladesh Shilpakala Academy", "ShilpakalaAcademy", "BD", ["bn", "en"], "government_cultural", "cultural", "https://shilpakala.gov.bd/"),
  YT("lahore-music", "Lahore Music Meet", "LahoreMusicMeet", "PK", ["en", "ur"], "official_festival", "festival", "https://www.lahoremusicmeet.com/"),
  YT("singapore-symphony", "Singapore Symphony Orchestra", "SingaporeSymphony", "SG", ["en"], "orchestra", "orchestra", "https://www.sso.org.sg/"),
  YT("esplanade-sg", "Esplanade Singapore", "EsplanadeSG", "SG", ["en"], "official_venue", "venue", "https://www.esplanade.com/"),
  YT("malaysian-phil", "Malaysian Philharmonic", "MPOrchestra", "MY", ["en", "ms"], "orchestra", "orchestra", "https://mpo.com.my/"),
  YT("bangkok-symphony", "Bangkok Symphony", "BangkokSymphony", "TH", ["th", "en"], "orchestra", "orchestra", "https://www.bangkoksymphony.org/"),
  YT("jakarta-concert", "Jakarta Concert Hall / Taman Ismail", "TIMJakarta", "ID", ["id", "en"], "official_venue", "venue", "https://www.tamanismailmarzuki.co.id/"),
  YT("manila-symphony", "Manila Symphony Orchestra", "ManilaSymphony", "PH", ["en"], "orchestra", "orchestra", "https://www.manilasymphony.com/"),
  YT("ccp-philippines", "Cultural Center of the Philippines", "CCPhilippines", "PH", ["en"], "government_cultural", "cultural", "https://www.culturalcenter.gov.ph/"),
  YT("hanoi-opera", "Hanoi Opera House", "HanoiOperaHouse", "VN", ["vi", "en"], "opera_house", "opera", "https://hanoioperahouse.org.vn/"),

  // East Asia
  YT("nhk-symphony", "NHK Symphony Orchestra", "NHKSymphony", "JP", ["ja", "en"], "orchestra", "orchestra", "https://www.nhkso.or.jp/"),
  YT("suntory-hall", "Suntory Hall", "SuntoryHall", "JP", ["ja", "en"], "official_venue", "venue", "https://www.suntory.com/culture-sports/suntoryhall/"),
  YT("tokyo-phil", "Tokyo Philharmonic", "TokyoPhilharmonic", "JP", ["ja", "en"], "orchestra", "orchestra", "https://www.tpo.or.jp/"),
  YT("fuji-rock", "Fuji Rock Festival", "FujiRockFestival", "JP", ["ja", "en"], "official_festival", "festival", "https://www.fujirockfestival.com/"),
  YT("summer-sonic", "Summer Sonic", "SummerSonic", "JP", ["ja", "en"], "official_festival", "festival", "https://www.summersonic.com/"),
  YT("seoul-phil", "Seoul Philharmonic", "SeoulPhilharmonic", "KR", ["ko", "en"], "orchestra", "orchestra", "https://www.seoulphil.or.kr/"),
  YT("korean-national-opera", "Korean National Opera", "KoreanNationalOpera", "KR", ["ko", "en"], "opera_house", "opera", "https://www.nationalopera.org/"),
  YT("busan-rock", "Busan International Rock Festival", "BusanRockFest", "KR", ["ko", "en"], "official_festival", "festival", "https://www.birf.or.kr/"),
  YT("national-taiwan-symphony", "National Taiwan Symphony", "NTSOTaiwan", "TW", ["zh", "en"], "orchestra", "orchestra", "https://www.ntso.gov.tw/"),
  YT("hong-kong-phil", "Hong Kong Philharmonic", "HKPhil", "HK", ["en", "zh"], "orchestra", "orchestra", "https://www.hkphil.org/"),
  YT("china-phil", "China Philharmonic Orchestra", "ChinaPhilharmonic", "CN", ["zh", "en"], "orchestra", "orchestra", "https://www.chinaphilharmonic.org/"),
  YT("shanghai-symphony", "Shanghai Symphony", "ShanghaiSymphony", "CN", ["zh", "en"], "orchestra", "orchestra", "https://www.shsymphony.com/"),
  YT("beijing-music-fest", "Beijing Music Festival", "BeijingMusicFest", "CN", ["zh", "en"], "official_festival", "festival", "https://www.bmf.org.cn/"),

  // Oceania more
  YT("melbourne-symphony", "Melbourne Symphony Orchestra", "MelbourneSymphony", "AU", ["en"], "orchestra", "orchestra", "https://www.mso.com.au/"),
  YT("queensland-symphony", "Queensland Symphony", "QueenslandSymphony", "AU", ["en"], "orchestra", "orchestra", "https://qso.com.au/"),
  YT("west-australian-symphony", "West Australian Symphony", "WASOrchestra", "AU", ["en"], "orchestra", "orchestra", "https://www.waso.com.au/"),
  YT("adelaide-symphony", "Adelaide Symphony Orchestra", "AdelaideSymphony", "AU", ["en"], "orchestra", "orchestra", "https://www.aso.com.au/"),
  YT("splendour-in-grass", "Splendour in the Grass", "Splendour", "AU", ["en"], "official_festival", "festival", "https://splendourinthegrass.com/"),
  YT("falls-festival", "Falls Festival", "FallsFestival", "AU", ["en"], "official_festival", "festival", "https://fallsfestival.com/"),
  YT("bluesfest-byron", "Bluesfest Byron Bay", "Bluesfest", "AU", ["en"], "official_festival", "festival", "https://www.bluesfest.com.au/"),
  YT("auckland-phil", "Auckland Philharmonia", "AucklandPhil", "NZ", ["en"], "orchestra", "orchestra", "https://www.apo.co.nz/"),
  YT("nzso", "New Zealand Symphony Orchestra", "NZSymphony", "NZ", ["en"], "orchestra", "orchestra", "https://www.nzso.co.nz/"),
  YT("laneway", "St Jerome's Laneway", "LanewayFestival", "AU", ["en"], "official_festival", "festival", "https://lanewayfestival.com/"),

  // Europe more — Nordic / Baltics / East
  YT("oslo-phil", "Oslo Philharmonic", "OsloPhilharmonic", "NO", ["no", "en"], "orchestra", "orchestra", "https://ofo.no/"),
  YT("bergen-phil", "Bergen Philharmonic", "BergenPhilharmonic", "NO", ["no", "en"], "orchestra", "orchestra", "https://harmonien.no/"),
  YT("stockholm-phil", "Royal Stockholm Philharmonic", "Konserthuset", "SE", ["sv", "en"], "orchestra", "orchestra", "https://www.konserthuset.se/"),
  YT("swedish-radio-symphony", "Swedish Radio Symphony", "SwedishRadioSymphony", "SE", ["sv", "en"], "orchestra", "orchestra", "https://www.berwaldhallen.se/"),
  YT("helsinki-phil", "Helsinki Philharmonic", "HelsinkiPhilharmonic", "FI", ["fi", "en"], "orchestra", "orchestra", "https://helsinkiphilharmonicorchestra.fi/"),
  YT("finnish-radio-symphony", "Finnish Radio Symphony", "FRSOOrchestra", "FI", ["fi", "en"], "orchestra", "orchestra", "https://yle.fi/aihe/rso"),
  YT("copenhagen-phil", "Copenhagen Phil", "CopenhagenPhil", "DK", ["da", "en"], "orchestra", "orchestra", "https://www.copenhagenphil.dk/"),
  YT("danish-national-symphony", "Danish National Symphony", "DNSOOrchestra", "DK", ["da", "en"], "orchestra", "orchestra", "https://www.dr.dk/koncerthuset"),
  YT("reykjavik-arts", "Reykjavík Arts Festival", "ReykjavikArts", "IS", ["is", "en"], "official_festival", "festival", "https://www.listahatid.is/"),
  YT("estonia-festival", "Estonian Music Days", "EstonianMusicDays", "EE", ["et", "en"], "official_festival", "festival", "https://www.eestimuusikapaevad.ee/"),
  YT("latvian-national-opera", "Latvian National Opera", "LatvianNationalOpera", "LV", ["lv", "en"], "opera_house", "opera", "https://www.opera.lv/"),
  YT("lithuanian-national-opera", "Lithuanian National Opera", "LNOBT", "LT", ["lt", "en"], "opera_house", "opera", "https://www.opera.lt/"),
  YT("warsaw-phil", "Warsaw Philharmonic", "WarsawPhilharmonic", "PL", ["pl", "en"], "orchestra", "orchestra", "https://www.filharmonia.pl/"),
  YT("chopin-institute", "Fryderyk Chopin Institute", "NIFCChopin", "PL", ["pl", "en"], "cultural_institution", "classical", "https://nifc.pl/"),
  YT("prague-spring", "Prague Spring Festival", "PragueSpring", "CZ", ["cs", "en"], "official_festival", "festival", "https://festival.cz/"),
  YT("czech-phil", "Czech Philharmonic", "CzechPhilharmonic", "CZ", ["cs", "en"], "orchestra", "orchestra", "https://www.ceskafilharmonie.cz/"),
  YT("budapest-festival-orch", "Budapest Festival Orchestra", "BFOrchestra", "HU", ["hu", "en"], "orchestra", "orchestra", "https://www.bfz.hu/"),
  YT("hungarian-state-opera", "Hungarian State Opera", "OperaBudapest", "HU", ["hu", "en"], "opera_house", "opera", "https://www.opera.hu/"),
  YT("bucharest-athenaeum", "George Enescu Festival", "EnescuFestival", "RO", ["ro", "en"], "official_festival", "festival", "https://www.festivalenescu.ro/"),
  YT("sofia-phil", "Sofia Philharmonic", "SofiaPhilharmonic", "BG", ["bg", "en"], "orchestra", "orchestra", "https://sofiaphilharmonic.com/"),
  YT("belgrade-phil", "Belgrade Philharmonic", "BelgradePhilharmonic", "RS", ["sr", "en"], "orchestra", "orchestra", "https://www.bgf.rs/"),
  YT("zagreb-phil", "Zagreb Philharmonic", "ZagrebPhilharmonic", "HR", ["hr", "en"], "orchestra", "orchestra", "https://www.zgf.hr/"),
  YT("ljubljana-festival", "Ljubljana Festival", "LjubljanaFestival", "SI", ["sl", "en"], "official_festival", "festival", "https://www.ljubljanafestival.si/"),
  YT("athens-megaron", "Megaron Athens", "MegaronAthens", "GR", ["el", "en"], "official_venue", "venue", "https://www.megaron.gr/"),
  YT("greek-national-opera", "Greek National Opera", "GreekNationalOpera", "GR", ["el", "en"], "opera_house", "opera", "https://www.nationalopera.gr/"),
  YT("istanbul-music", "Istanbul Music Festival", "IstanbulMusicFest", "TR", ["tr", "en"], "official_festival", "festival", "https://muzik.iksv.org/"),
  YT("borusan-istanbul", "Borusan Istanbul Philharmonic", "BorusanIstanbul", "TR", ["tr", "en"], "orchestra", "orchestra", "https://www.borusansanat.com/"),

  // Iberia / Italy / France more
  YT("orquesta-nacional-espana", "Orquesta Nacional de España", "OrquestaNacional", "ES", ["es"], "orchestra", "orchestra", "https://www.ocne.es/"),
  YT("teatro-real", "Teatro Real Madrid", "TeatroReal", "ES", ["es", "en"], "opera_house", "opera", "https://www.teatroreal.es/"),
  YT("liceu", "Gran Teatre del Liceu", "LiceuBarcelona", "ES", ["ca", "es", "en"], "opera_house", "opera", "https://www.liceubarcelona.cat/"),
  YT("sagrada-musica", "Palau de la Música Catalana", "PalauMusica", "ES", ["ca", "es"], "official_venue", "venue", "https://www.palaumusica.cat/"),
  YT("nos-primavera", "NOS Primavera Sound", "PrimaveraSound", "ES", ["es", "en"], "official_festival", "festival", "https://www.primaverasound.com/"),
  YT("madcool", "Mad Cool Festival", "MadCoolFestival", "ES", ["es", "en"], "official_festival", "festival", "https://www.madcoolfestival.com/"),
  YT("gulbenkian", "Calouste Gulbenkian Music", "GulbenkianMusica", "PT", ["pt", "en"], "cultural_institution", "classical", "https://gulbenkian.pt/musica/"),
  YT("casa-da-musica", "Casa da Música", "CasadaMusica", "PT", ["pt", "en"], "official_venue", "venue", "https://www.casadamusica.com/"),
  YT("teatro-alla-scala", "Teatro alla Scala", "TeatroallaScala", "IT", ["it", "en"], "opera_house", "opera", "https://www.teatroallascala.org/"),
  YT("santa-cecilia", "Accademia Nazionale di Santa Cecilia", "SantaCecilia", "IT", ["it", "en"], "orchestra", "orchestra", "https://www.santacecilia.it/"),
  YT("teatro-regio-torino", "Teatro Regio Torino", "TeatroRegioTorino", "IT", ["it", "en"], "opera_house", "opera", "https://www.teatroregio.torino.it/"),
  YT("ravello-festival", "Ravello Festival", "RavelloFestival", "IT", ["it", "en"], "official_festival", "festival", "https://www.ravellofestival.com/"),
  YT("umbria-jazz", "Umbria Jazz", "UmbriaJazz", "IT", ["it", "en"], "official_festival", "jazz", "https://www.umbriajazz.com/"),
  YT("orchestre-de-paris", "Orchestre de Paris", "OrchestredeParis", "FR", ["fr", "en"], "orchestra", "orchestra", "https://www.orchestredeparis.com/"),
  YT("opera-bastille", "Opéra national de Paris", "OperaParis", "FR", ["fr", "en"], "opera_house", "opera", "https://www.operadeparis.fr/"),
  YT("philharmonie-paris", "Philharmonie de Paris", "PhilharmonieParis", "FR", ["fr", "en"], "official_venue", "venue", "https://philharmoniedeparis.fr/"),
  YT("jazz-a-vienne", "Jazz à Vienne", "JazzAVienne", "FR", ["fr", "en"], "official_festival", "jazz", "https://www.jazzavienne.com/"),
  YT("solidays", "Solidays", "Solidays", "FR", ["fr"], "official_festival", "festival", "https://www.solidays.org/"),
  YT("vieilles-charrues", "Vieilles Charrues", "VieillesCharrues", "FR", ["fr"], "official_festival", "festival", "https://www.vieillescharrues.asso.fr/"),

  // UK / Ireland more
  YT("barbican-centre", "Barbican Centre", "BarbicanCentre", "GB", ["en"], "official_venue", "venue", "https://www.barbican.org.uk/"),
  YT("wigmore-hall", "Wigmore Hall", "WigmoreHall", "GB", ["en"], "official_venue", "venue", "https://wigmore-hall.org.uk/"),
  YT("sage-gateshead", "Sage Gateshead / The Glasshouse", "TheGlasshouse", "GB", ["en"], "official_venue", "venue", "https://theglasshouseicm.org/"),
  YT("glyndebourne", "Glyndebourne", "Glyndebourne", "GB", ["en"], "opera_house", "opera", "https://www.glyndebourne.com/"),
  YT("welsh-national-opera", "Welsh National Opera", "WelshNationalOpera", "GB", ["en"], "opera_house", "opera", "https://wno.org.uk/"),
  YT("scottish-opera", "Scottish Opera", "ScottishOpera", "GB", ["en"], "opera_house", "opera", "https://www.scottishopera.org.uk/"),
  YT("edinburgh-festival", "Edinburgh International Festival", "EdIntFest", "GB", ["en"], "official_festival", "festival", "https://www.eif.co.uk/"),
  YT("glastonbury", "Glastonbury Festival", "Glastonbury", "GB", ["en"], "official_festival", "festival", "https://www.glastonburyfestivals.co.uk/"),
  YT("reading-leeds", "Reading & Leeds", "ReadingLeeds", "GB", ["en"], "official_festival", "festival", "https://www.readingandleedsfestival.com/"),
  YT("download-fest", "Download Festival", "DownloadFest", "GB", ["en"], "official_festival", "festival", "https://downloadfestival.co.uk/"),
  YT("latitude-fest", "Latitude Festival", "LatitudeFestival", "GB", ["en"], "official_festival", "festival", "https://www.latitudefestival.com/"),
  YT("npr-music-uk", "BBC Introducing", "BBCIntroducing", "GB", ["en"], "public_broadcaster", "broadcaster", "https://www.bbc.co.uk/introducing"),
  YT("rte-lyric", "RTÉ Lyric FM / Concerts", "RTElyricfm", "IE", ["en"], "public_broadcaster", "broadcaster", "https://www.rte.ie/lyricfm/"),
  YT("national-concert-hall-ie", "National Concert Hall Dublin", "NationalConcertHall", "IE", ["en"], "official_venue", "venue", "https://www.nch.ie/"),

  // Germany / Austria / CH more
  YT("gewandhaus", "Gewandhausorchester Leipzig", "Gewandhaus", "DE", ["de", "en"], "orchestra", "orchestra", "https://www.gewandhausorchester.de/"),
  YT("staatsoper-berlin", "Staatsoper Berlin", "StaatsoperBerlin", "DE", ["de", "en"], "opera_house", "opera", "https://www.staatsoper-berlin.de/"),
  YT("bayerische-staatsoper", "Bayerische Staatsoper", "BayerischeStaatsoper", "DE", ["de", "en"], "opera_house", "opera", "https://www.staatsoper.de/"),
  YT("semperoper", "Semperoper Dresden", "Semperoper", "DE", ["de", "en"], "opera_house", "opera", "https://www.semperoper.de/"),
  YT("elphilharmonie", "Elbphilharmonie", "Elbphilharmonie", "DE", ["de", "en"], "official_venue", "venue", "https://www.elbphilharmonie.de/"),
  YT("wacken", "Wacken Open Air", "WackenOpenAir", "DE", ["de", "en"], "official_festival", "festival", "https://www.wacken.com/"),
  YT("rock-am-ring", "Rock am Ring", "RockamRing", "DE", ["de", "en"], "official_festival", "festival", "https://www.rock-am-ring.com/"),
  YT("melt-festival", "Melt! Festival", "MeltFestival", "DE", ["de", "en"], "official_festival", "festival", "https://meltfestival.de/"),
  YT("salzburg-festspiele", "Salzburg Festival", "SalzburgFestival", "AT", ["de", "en"], "official_festival", "festival", "https://www.salzburgerfestspiele.at/"),
  YT("wiener-staatsoper", "Wiener Staatsoper", "WienerStaatsoper", "AT", ["de", "en"], "opera_house", "opera", "https://www.wiener-staatsoper.at/"),
  YT("lucerne-festival", "Lucerne Festival", "LucerneFestival", "CH", ["de", "en", "fr"], "official_festival", "festival", "https://www.lucernefestival.ch/"),
  YT("verbier-festival", "Verbier Festival", "VerbierFestival", "CH", ["en", "fr"], "official_festival", "festival", "https://www.verbierfestival.com/"),

  // Americas more venues / festivals
  YT("carnegie-hall", "Carnegie Hall", "CarnegieHall", "US", ["en"], "official_venue", "venue", "https://www.carnegiehall.org/"),
  YT("lincoln-center", "Lincoln Center", "LincolnCenter", "US", ["en"], "cultural_institution", "cultural", "https://www.lincolncenter.org/"),
  YT("disney-hall", "Walt Disney Concert Hall", "DisneyHall", "US", ["en"], "official_venue", "venue", "https://www.laphil.com/"),
  YT("laphil", "Los Angeles Philharmonic", "LAPhil", "US", ["en"], "orchestra", "orchestra", "https://www.laphil.com/"),
  YT("sf-symphony", "San Francisco Symphony", "SFSymphony", "US", ["en"], "orchestra", "orchestra", "https://www.sfsymphony.org/"),
  YT("boston-symphony", "Boston Symphony Orchestra", "BostonSymphony", "US", ["en"], "orchestra", "orchestra", "https://www.bso.org/"),
  YT("chicago-symphony", "Chicago Symphony Orchestra", "ChicagoSymphony", "US", ["en"], "orchestra", "orchestra", "https://cso.org/"),
  YT("met-museum-concerts", "Met Museum Concerts", "metmuseum", "US", ["en"], "cultural_institution", "cultural", "https://www.metmuseum.org/"),
  YT("smithsonian-music", "Smithsonian Music", "SmithsonianMusic", "US", ["en"], "government_cultural", "cultural", "https://music.si.edu/"),
  YT("newportsfolk", "Newport Folk Festival", "NewportFolkFest", "US", ["en"], "official_festival", "festival", "https://www.newportfolk.org/"),
  YT("coachella", "Coachella", "coachella", "US", ["en"], "official_festival", "festival", "https://www.coachella.com/"),
  YT("outside-lands", "Outside Lands", "OutsideLands", "US", ["en"], "official_festival", "festival", "https://www.sfoutsidelands.com/"),
  YT("governors-ball", "Governors Ball", "GovernorsBall", "US", ["en"], "official_festival", "festival", "https://www.governorsballmusicfestival.com/"),
  YT("pitchfork-fest", "Pitchfork Music Festival", "Pitchfork", "US", ["en"], "official_festival", "festival", "https://pitchforkmusicfestival.com/"),
  YT("afropunk", "AFROPUNK", "AFROPUNK", "US", ["en"], "official_festival", "festival", "https://afropunk.com/"),
  YT("montreal-jazz-alt", "Festival International de Jazz de Montréal", "MontrealJazzFest", "CA", ["fr", "en"], "official_festival", "jazz", "https://www.montrealjazzfest.com/"),
  YT("ottawa-jazz", "Ottawa Jazz Festival", "OttawaJazzFest", "CA", ["en", "fr"], "official_festival", "jazz", "https://ottawajazzfestival.com/"),
  YT("vancouver-folk", "Vancouver Folk Music Festival", "VanFolkFest", "CA", ["en"], "official_festival", "festival", "https://thefestival.bc.ca/"),
  YT("osheaga", "Osheaga", "Osheaga", "CA", ["en", "fr"], "official_festival", "festival", "https://www.osheaga.com/"),
  YT("lollapalooza-chile", "Lollapalooza Chile", "LollapaloozaCL", "CL", ["es", "en"], "official_festival", "festival", "https://www.lollapaloozacl.com/"),
  YT("lollapalooza-ar", "Lollapalooza Argentina", "LollapaloozaAR", "AR", ["es", "en"], "official_festival", "festival", "https://www.lollapaloozaar.com/"),
  YT("vive-latino", "Vive Latino", "ViveLatino", "MX", ["es"], "official_festival", "festival", "https://www.vivelatino.com.mx/"),
  YT("cosquin-rock", "Cosquín Rock", "CosquinRock", "AR", ["es"], "official_festival", "festival", "https://www.cosquinrock.net/"),
  YT("festival-de-vina", "Festival de Viña del Mar", "FestivaldeVina", "CL", ["es"], "official_festival", "festival", "https://www.festivaldevina.cl/"),

  // Choirs / gospel / community
  YT("mormon-tabernacle", "Tabernacle Choir", "TheTabernacleChoir", "US", ["en"], "cultural_institution", "choir", "https://www.thetabernaclechoir.org/"),
  YT("kings-college-choir", "Choir of King's College Cambridge", "KingsCollegeChoir", "GB", ["en"], "university", "choir", "https://www.kings.cam.ac.uk/choir"),
  YT("westminster-abbey-choir", "Westminster Abbey Choir", "WestminsterAbbey", "GB", ["en"], "cultural_institution", "choir", "https://www.westminster-abbey.org/"),
  YT("vienna-boys-choir", "Vienna Boys Choir", "ViennaBoysChoir", "AT", ["de", "en"], "cultural_institution", "choir", "https://www.wsk.at/"),
  YT("eric-whitacre", "Eric Whitacre Virtual Choir", "EricWhitacre", "US", ["en"], "official_artist", "choir", "https://ericwhitacre.com/"),
  YT("tanglewood", "Tanglewood", "Tanglewood", "US", ["en"], "official_festival", "classical", "https://www.bso.org/tanglewood"),
  YT("aspen-music", "Aspen Music Festival", "AspenMusicFest", "US", ["en"], "official_festival", "classical", "https://www.aspenmusicfestival.com/"),
  YT("interlochen", "Interlochen Center for the Arts", "InterlochenArts", "US", ["en"], "conservatory", "conservatory", "https://www.interlochen.org/"),
  YT("eastman-school", "Eastman School of Music", "EastmanSchool", "US", ["en"], "conservatory", "conservatory", "https://www.esm.rochester.edu/"),
  YT("berklee", "Berklee College of Music", "BerkleeCollege", "US", ["en"], "conservatory", "conservatory", "https://www.berklee.edu/"),
  YT("juilliard", "The Juilliard School", "JuilliardSchool", "US", ["en"], "conservatory", "conservatory", "https://www.juilliard.edu/"),
  YT("curtis-institute", "Curtis Institute of Music", "CurtisInstitute", "US", ["en"], "conservatory", "conservatory", "https://www.curtis.edu/"),

  // Radio / session channels
  YT("kexp", "KEXP", "kexp", "US", ["en"], "public_broadcaster", "artist", "https://www.kexp.org/"),
  YT("kcrw", "KCRW", "KCRW", "US", ["en"], "public_broadcaster", "artist", "https://www.kcrw.com/"),
  YT("wfuv", "WFUV", "WFUV", "US", ["en"], "public_broadcaster", "artist", "https://www.wfuv.org/"),
  YT("triplej", "triple j", "triplej", "AU", ["en"], "public_broadcaster", "artist", "https://www.abc.net.au/triplej"),
  YT("bbc-radio1", "BBC Radio 1", "BBCR1", "GB", ["en"], "public_broadcaster", "artist", "https://www.bbc.co.uk/radio1"),
  YT("bbc-radio2", "BBC Radio 2", "BBCRadio2", "GB", ["en"], "public_broadcaster", "artist", "https://www.bbc.co.uk/radio2"),
  YT("bbc-radio3", "BBC Radio 3", "BBCRadio3", "GB", ["en"], "public_broadcaster", "classical", "https://www.bbc.co.uk/radio3"),
  YT("radio-france-musique", "France Musique", "FranceMusique", "FR", ["fr"], "public_broadcaster", "classical", "https://www.radiofrance.fr/francemusique"),
  YT("deutschlandfunk-kultur", "Deutschlandfunk Kultur", "DLFKultur", "DE", ["de"], "public_broadcaster", "broadcaster", "https://www.deutschlandfunkkultur.de/"),
  YT("npo-radio4", "NPO Radio 4", "NPORadio4", "NL", ["nl"], "public_broadcaster", "classical", "https://www.nporadio4.nl/"),
  YT("cbc-music", "CBC Music", "cbcmusic", "CA", ["en"], "public_broadcaster", "artist", "https://www.cbc.ca/music"),
  YT("sofarsounds", "Sofar Sounds", "SofarSounds", "GB", ["en"], "official_artist", "artist", "https://www.sofarsounds.com/"),
  YT("mahalofest", "Mahalo Fest / sessions", "Mahalo", "US", ["en"], "official_artist", "dj", "https://mahalo.com/"),
  YT("stones-throw", "Stones Throw", "StonesThrow", "US", ["en"], "official_artist", "artist", "https://www.stonesthrow.com/"),
  YT("brainfeeder", "Brainfeeder", "Brainfeeder", "US", ["en"], "official_artist", "artist", "https://brainfeedersite.com/"),

  // Non-YouTube wave B
  {
    stableKey: "vimeo-berlin-phil",
    name: "Berlin Phil on Vimeo",
    provider: "vimeo",
    providerType: "orchestra",
    countryCode: "DE",
    languageCodes: ["de", "en"],
    officialUrl: "https://www.berliner-philharmoniker.de/",
    mediaChannelUrl: "https://vimeo.com/berlinphil",
    category: "orchestra",
    sourceOwner: "Berliner Philharmoniker",
  },
  {
    stableKey: "vimeo-royal-opera",
    name: "Royal Opera House Vimeo",
    provider: "vimeo",
    providerType: "opera_house",
    countryCode: "GB",
    languageCodes: ["en"],
    officialUrl: "https://www.roh.org.uk/",
    mediaChannelUrl: "https://vimeo.com/royaloperahouse",
    category: "opera",
    sourceOwner: "Royal Opera House",
  },
  {
    stableKey: "dailymotion-france-tv",
    name: "France Télévisions Dailymotion",
    provider: "dailymotion",
    providerType: "public_broadcaster",
    countryCode: "FR",
    languageCodes: ["fr"],
    officialUrl: "https://www.france.tv/",
    mediaChannelUrl: "https://www.dailymotion.com/francetv",
    category: "broadcaster",
    sourceOwner: "France Télévisions",
  },
  {
    stableKey: "dailymotion-nhk",
    name: "NHK World Dailymotion",
    provider: "dailymotion",
    providerType: "public_broadcaster",
    countryCode: "JP",
    languageCodes: ["en", "ja"],
    officialUrl: "https://www3.nhk.or.jp/nhkworld/",
    mediaChannelUrl: "https://www.dailymotion.com/NHKWORLD_NEWS",
    category: "broadcaster",
    sourceOwner: "NHK",
  },
  {
    stableKey: "twitch-audiotool",
    name: "Audiotool Twitch",
    provider: "twitch",
    providerType: "authorized_platform",
    countryCode: "DE",
    languageCodes: ["en"],
    officialUrl: "https://www.audiotool.com/",
    mediaChannelUrl: "https://www.twitch.tv/audiotool",
    category: "dj",
    sourceOwner: "Audiotool",
  },
  {
    stableKey: "twitch-beatport",
    name: "Beatport Twitch",
    provider: "twitch",
    providerType: "authorized_platform",
    countryCode: "US",
    languageCodes: ["en"],
    officialUrl: "https://www.beatport.com/",
    mediaChannelUrl: "https://www.twitch.tv/beatport",
    category: "dj",
    sourceOwner: "Beatport",
  },
];
