-- Expanded public TV browse categories for production catalog lanes.

insert into public.tv_categories (name, slug, type, sort_order)
values
  ('Featured', 'featured', 'collection', 90),
  ('Trending', 'trending', 'collection', 95),
  ('News', 'news', 'collection', 100),
  ('Sports', 'sports', 'collection', 110),
  ('Movies', 'movies', 'collection', 120),
  ('Entertainment', 'entertainment', 'collection', 130),
  ('Kids', 'kids', 'collection', 140),
  ('Documentary', 'documentary', 'collection', 150),
  ('Music TV', 'music-tv', 'collection', 160),
  ('Afrobeats', 'afrobeats', 'collection', 165),
  ('Amapiano', 'amapiano', 'collection', 167),
  ('Hip Hop', 'hip-hop', 'collection', 170),
  ('R&B', 'r-and-b', 'collection', 172),
  ('Pop', 'pop', 'collection', 174),
  ('Rock', 'rock', 'collection', 176),
  ('Country', 'country', 'collection', 178),
  ('Jazz', 'jazz', 'collection', 180),
  ('Classical', 'classical', 'collection', 182),
  ('Reggae', 'reggae', 'collection', 184),
  ('Latin', 'latin', 'collection', 186),
  ('EDM', 'edm', 'collection', 188),
  ('Worship Music', 'worship-music', 'collection', 190),
  ('Live Sessions', 'live-sessions', 'collection', 192),
  ('Artist TV', 'artist-tv', 'collection', 194),
  ('Festival Streams', 'festival-streams', 'collection', 196),
  ('Lifestyle', 'lifestyle', 'collection', 200),
  ('Education', 'education', 'collection', 210),
  ('Government', 'government', 'collection', 220),
  ('Africa', 'africa', 'collection', 230),
  ('Europe', 'europe', 'collection', 240),
  ('Americas', 'americas', 'collection', 250),
  ('Asia', 'asia', 'collection', 260),
  ('Local TV', 'local-tv', 'collection', 270),
  ('Motivation', 'motivation', 'collection', 280),
  ('Emotional Worlds', 'emotional-worlds', 'collection', 290),
  ('Motivational speeches', 'motivational-speeches', 'collection', 300),
  ('Self-improvement', 'self-improvement', 'collection', 310),
  ('Business motivation', 'business-motivation', 'collection', 320),
  ('Gym motivation', 'gym-motivation', 'collection', 330),
  ('Study motivation', 'study-motivation', 'collection', 340),
  ('Faith motivation', 'faith-motivation', 'collection', 350),
  ('Success stories', 'success-stories', 'collection', 360),
  ('Mindset', 'mindset', 'collection', 370),
  ('Discipline', 'discipline', 'collection', 380),
  ('Focus', 'focus', 'collection', 390)
on conflict (slug) do nothing;
