-- Phase 2G additive foundation. Staged only; no canonical identities or legacy rows are deleted.
create table if not exists public.tv_canonical_channels(id uuid primary key default gen_random_uuid(),canonical_key text not null unique,display_name text not null,country text,language text,category text,network text,aliases text[] not null default '{}',former_names text[] not null default '{}',logo_url text,epg_id text,identity_confidence text not null default 'UNRESOLVED',public_playable boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.tv_playback_sources(id uuid primary key default gen_random_uuid(),canonical_channel_id uuid not null references public.tv_canonical_channels(id) on delete restrict,legacy_tv_video_id uuid references public.tv_videos(id) on delete set null,source_url text not null,source_host text not null,source_type text not null,provenance text not null,role text not null default 'HISTORICAL',priority integer not null default 0,health text not null default 'TEMPORARY_FAILURE',reliability_score integer not null default 0,consecutive_failures integer not null default 0,success_count bigint not null default 0,failure_count bigint not null default 0,last_health_check_at timestamptz,last_success_at timestamptz,last_failure_at timestamptz,next_check_at timestamptz,manifest_latency_ms integer,first_media_latency_ms integer,quarantined_at timestamptz,platform_playable boolean not null default false,region_codes text[] not null default '{}',research_fingerprint text,replacement_of uuid references public.tv_playback_sources(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(canonical_channel_id,source_url));
create table if not exists public.tv_source_health_events(id bigint generated always as identity primary key,source_id uuid not null references public.tv_playback_sources(id) on delete cascade,checked_at timestamptz not null default now(),previous_health text,new_health text not null,reason text,manifest_ok boolean,segments_ok boolean,media_ok boolean,identity_ok boolean,startup_ms integer,http_status integer,details jsonb not null default '{}');
create table if not exists public.tv_recovery_queue(id uuid primary key default gen_random_uuid(),canonical_channel_id uuid not null references public.tv_canonical_channels(id) on delete cascade,reason text not null,status text not null default 'PENDING',attempt_fingerprints text[] not null default '{}',last_evidence jsonb not null default '{}',next_attempt_at timestamptz,attempt_count integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(canonical_channel_id,reason));
create index if not exists tv_sources_due_idx on public.tv_playback_sources(next_check_at asc nulls first,id) where quarantined_at is null;
create index if not exists tv_sources_channel_rank_idx on public.tv_playback_sources(canonical_channel_id,role,priority desc,reliability_score desc);
create index if not exists tv_recovery_due_idx on public.tv_recovery_queue(next_attempt_at asc nulls first,id) where status='PENDING';
alter table public.tv_canonical_channels enable row level security;alter table public.tv_playback_sources enable row level security;alter table public.tv_source_health_events enable row level security;alter table public.tv_recovery_queue enable row level security;
