/**
 * Curated official Concerts source registry.
 * Phase 4: eligible YouTube/public sources are import-enabled so checkpointed
 * import runs can process all verified free playable content. Items still insert
 * as validation_pending and are never public until later validation passes.
 *
 * Evidence standard:
 * - Official website exists and identifies the institution/owner
 * - Media/channel URL is the institution's official presence (or clearly linked)
 * - Authorization and embed policy are classified separately from public visibility
 * - Unclear ownership or unknown/prohibited embed policy => disabled, non-importable
 * - Subscription/external-link-only platforms stay non-importable for in-app playback
 */

import type { ConcertSourceSeed } from "./types";
import { validateConcertSourceRegistry } from "./sourceValidation";
import { normalizeConcertSourceSeed } from "./sourceNormalization";
import { getKnownConcertYouTubeChannelId } from "./providers/channelIdentityMap";
import { withPhase4ImportFlags } from "./import/sourceEligibility";

const REVIEWED = "2026-07-18";

function seed(partial: Omit<ConcertSourceSeed, "importEnabled">): ConcertSourceSeed {
  const knownId = getKnownConcertYouTubeChannelId(partial.stableKey);
  const providerChannelId = partial.providerChannelId || knownId || null;
  const mediaChannelUrl =
    partial.provider === "youtube" && providerChannelId
      ? `https://www.youtube.com/channel/${providerChannelId}`
      : partial.mediaChannelUrl;

  return withPhase4ImportFlags({
    ...partial,
    providerChannelId,
    mediaChannelUrl,
    importEnabled: false,
  });
}

export const CURATED_CONCERT_SOURCES: ConcertSourceSeed[] = [
  seed({
    stableKey: "arte-concert",
    name: "ARTE Concert",
    providerType: "public_broadcaster",
    provider: "youtube",
    officialUrl: "https://www.arte.tv/en/arte-concert/",
    mediaChannelUrl: "https://www.youtube.com/channel/UC-smeLB9AnOTeypr1YyjJ3A",
    providerChannelId: "UC-smeLB9AnOTeypr1YyjJ3A",
    countryCode: "FR",
    region: "europe",
    languageCodes: ["fr", "de", "en"],
    sourceOwner: "ARTE G.E.I.E. / ARTE Concert",
    ownershipEvidenceUrl: "https://www.arte.tv/en/arte-concert/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official free concert streams, festival captures, and cultural performances published by ARTE Concert.",
    expectedConcertFormats: ["full_concert", "festival_set", "livestream", "cultural_performance"],
    supportedCountries: ["FR", "DE", "BE", "AT", "CH"],
    geoRestrictions: { note: "Some titles may be geo-limited on arte.tv and/or YouTube." },
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_channel_match+youtube_oembed_per_item",
    reliabilityScore: 90,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Public Franco-German cultural broadcaster concert brand. Channel ID matched to ARTE Concert YouTube presence; official site confirms ARTE Concert product. Per-video embed/geo still required at import.",
  }),
  seed({
    stableKey: "berliner-philharmoniker",
    name: "Berliner Philharmoniker",
    providerType: "orchestra",
    provider: "youtube",
    officialUrl: "https://www.berliner-philharmoniker.de/en/",
    mediaChannelUrl: "https://www.youtube.com/channel/UCtRkmSO4PrhJ4TzNOmFIwjw",
    providerChannelId: "UCtRkmSO4PrhJ4TzNOmFIwjw",
    countryCode: "DE",
    region: "europe",
    languageCodes: ["de", "en"],
    sourceOwner: "Berliner Philharmoniker Foundation",
    ownershipEvidenceUrl: "https://www.berliner-philharmoniker.de/en/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official orchestra performances, excerpts, and educational concert content from the Berlin Philharmonic.",
    expectedConcertFormats: ["orchestra_performance", "full_concert", "recital"],
    supportedCountries: ["DE"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 92,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official orchestra website. YouTube channel ID UCtRkmSO4PrhJ4TzNOmFIwjw confirmed for @BerlinPhil. Digital Concert Hall subscription content remains a separate non-importable source.",
  }),
  seed({
    stableKey: "digital-concert-hall",
    name: "Berliner Philharmoniker Digital Concert Hall",
    providerType: "authorized_platform",
    provider: "authorized_platform",
    officialUrl: "https://www.digitalconcerthall.com/",
    mediaChannelUrl: "https://www.digitalconcerthall.com/",
    providerChannelId: null,
    countryCode: "DE",
    region: "europe",
    languageCodes: ["de", "en"],
    sourceOwner: "Berliner Philharmoniker Digital Concert Hall",
    ownershipEvidenceUrl: "https://www.digitalconcerthall.com/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.digitalconcerthall.com/",
    embedPolicy: "external_link_only",
    contentScope: "Subscription digital concert platform operated by the Berlin Philharmonic.",
    expectedConcertFormats: ["orchestra_performance", "full_concert"],
    supportedCountries: ["DE"],
    geoRestrictions: { subscription: true },
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_platform_terms_review",
    reliabilityScore: 88,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official ownership is clear, but the product is primarily subscription. Classified external_link_only for Hidden Tunes free in-app playback. Not import-enabled.",
  }),
  seed({
    stableKey: "metropolitan-opera",
    name: "Metropolitan Opera",
    providerType: "opera_house",
    provider: "youtube",
    officialUrl: "https://www.metopera.org/",
    mediaChannelUrl: "https://www.youtube.com/@MetropolitanOpera",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Metropolitan Opera Association",
    ownershipEvidenceUrl: "https://www.metopera.org/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Met Opera performances, free streams, and educational excerpts from the house channel.",
    expectedConcertFormats: ["opera", "full_concert", "livestream"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 91,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official opera house. Met Opera on Demand / paid offerings are out of free-playback scope; only clearly free official uploads may be imported later.",
  }),
  seed({
    stableKey: "royal-opera-house",
    name: "Royal Opera House",
    providerType: "opera_house",
    provider: "youtube",
    officialUrl: "https://www.roh.org.uk/",
    mediaChannelUrl: "https://www.youtube.com/@RoyalOperaHouse",
    providerChannelId: null,
    countryCode: "GB",
    region: "europe",
    languageCodes: ["en"],
    sourceOwner: "Royal Opera House Covent Garden Foundation",
    ownershipEvidenceUrl: "https://www.roh.org.uk/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official ROH opera and ballet performance content published by the house.",
    expectedConcertFormats: ["opera", "full_concert", "cultural_performance"],
    supportedCountries: ["GB"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 90,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official UK opera house channel linked from institutional identity. Stream Cinema / paid events remain external.",
  }),
  seed({
    stableKey: "opera-national-de-paris",
    name: "Opéra national de Paris",
    providerType: "opera_house",
    provider: "youtube",
    officialUrl: "https://www.operadeparis.fr/en",
    mediaChannelUrl: "https://www.youtube.com/@operadeparis",
    providerChannelId: null,
    countryCode: "FR",
    region: "europe",
    languageCodes: ["fr", "en"],
    sourceOwner: "Opéra national de Paris",
    ownershipEvidenceUrl: "https://www.operadeparis.fr/en",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Paris Opera performance and cultural broadcasts.",
    expectedConcertFormats: ["opera", "full_concert", "cultural_performance"],
    supportedCountries: ["FR"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 89,
    lastReviewedAt: REVIEWED,
    reviewNotes: "French national opera institution with official channel presence.",
  }),
  seed({
    stableKey: "teatro-alla-scala",
    name: "Teatro alla Scala",
    providerType: "opera_house",
    provider: "youtube",
    officialUrl: "https://www.teatroallascala.org/",
    mediaChannelUrl: "https://www.youtube.com/@TeatroallaScala",
    providerChannelId: null,
    countryCode: "IT",
    region: "europe",
    languageCodes: ["it", "en"],
    sourceOwner: "Teatro alla Scala",
    ownershipEvidenceUrl: "https://www.teatroallascala.org/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official La Scala performance and institutional concert content.",
    expectedConcertFormats: ["opera", "orchestra_performance", "full_concert"],
    supportedCountries: ["IT"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 88,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Historic Italian opera house official digital presence.",
  }),
  seed({
    stableKey: "wiener-philharmoniker",
    name: "Wiener Philharmoniker",
    providerType: "orchestra",
    provider: "youtube",
    officialUrl: "https://www.wienerphilharmoniker.at/en",
    mediaChannelUrl: "https://www.youtube.com/@WienerPhilharmoniker",
    providerChannelId: null,
    countryCode: "AT",
    region: "europe",
    languageCodes: ["de", "en"],
    sourceOwner: "Wiener Philharmoniker",
    ownershipEvidenceUrl: "https://www.wienerphilharmoniker.at/en",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Vienna Philharmonic concert and performance publications.",
    expectedConcertFormats: ["orchestra_performance", "full_concert"],
    supportedCountries: ["AT"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 91,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official Austrian orchestra identity with public YouTube presence.",
  }),
  seed({
    stableKey: "concertgebouw",
    name: "Concertgebouw",
    providerType: "official_venue",
    provider: "youtube",
    officialUrl: "https://www.concertgebouw.nl/en",
    mediaChannelUrl: "https://www.youtube.com/@Concertgebouw",
    providerChannelId: null,
    countryCode: "NL",
    region: "europe",
    languageCodes: ["nl", "en"],
    sourceOwner: "Het Concertgebouw N.V.",
    ownershipEvidenceUrl: "https://www.concertgebouw.nl/en",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Amsterdam Concertgebouw venue performances and broadcasts.",
    expectedConcertFormats: ["venue_broadcast", "orchestra_performance", "full_concert"],
    supportedCountries: ["NL"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 87,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official venue institution; distinguish Royal Concertgebouw Orchestra content when classifying items.",
  }),
  seed({
    stableKey: "sydney-opera-house",
    name: "Sydney Opera House",
    providerType: "official_venue",
    provider: "youtube",
    officialUrl: "https://www.sydneyoperahouse.com/",
    mediaChannelUrl: "https://www.youtube.com/@SydneyOperaHouse",
    providerChannelId: null,
    countryCode: "AU",
    region: "oceania",
    languageCodes: ["en"],
    sourceOwner: "Sydney Opera House Trust",
    ownershipEvidenceUrl: "https://www.sydneyoperahouse.com/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Sydney Opera House performances and livestreams.",
    expectedConcertFormats: ["venue_broadcast", "full_concert", "cultural_performance", "opera"],
    supportedCountries: ["AU"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 88,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Major venue/cultural institution with official channel.",
  }),
  seed({
    stableKey: "carnegie-hall",
    name: "Carnegie Hall",
    providerType: "official_venue",
    provider: "youtube",
    officialUrl: "https://www.carnegiehall.org/",
    mediaChannelUrl: "https://www.youtube.com/@CarnegieHall",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Carnegie Hall Corporation",
    ownershipEvidenceUrl: "https://www.carnegiehall.org/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Carnegie Hall concert presentations and educational performance content.",
    expectedConcertFormats: ["venue_broadcast", "full_concert", "recital"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 89,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official US venue; paid streaming products are out of free import scope.",
  }),
  seed({
    stableKey: "lincoln-center",
    name: "Lincoln Center",
    providerType: "cultural_institution",
    provider: "youtube",
    officialUrl: "https://www.lincolncenter.org/",
    mediaChannelUrl: "https://www.youtube.com/@LincolnCenter",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Lincoln Center for the Performing Arts",
    ownershipEvidenceUrl: "https://www.lincolncenter.org/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Lincoln Center cultural performances and concert programming.",
    expectedConcertFormats: ["cultural_performance", "full_concert", "venue_broadcast"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 86,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Campus-level cultural institution; resident companies have separate channels and must not be conflated without evidence.",
  }),
  seed({
    stableKey: "kennedy-center",
    name: "Kennedy Center",
    providerType: "cultural_institution",
    provider: "youtube",
    officialUrl: "https://www.kennedy-center.org/",
    mediaChannelUrl: "https://www.youtube.com/@KennedyCenter",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "John F. Kennedy Center for the Performing Arts",
    ownershipEvidenceUrl: "https://www.kennedy-center.org/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Kennedy Center concert and performing-arts broadcasts.",
    expectedConcertFormats: ["cultural_performance", "full_concert", "venue_broadcast"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "official_site_identity+handle_resolve+per_item_embed",
    reliabilityScore: 86,
    lastReviewedAt: REVIEWED,
    reviewNotes: "US national cultural center with official channel presence.",
  }),
  seed({
    stableKey: "library-of-congress-concerts",
    name: "Library of Congress Concerts",
    providerType: "government_cultural",
    provider: "youtube",
    officialUrl: "https://www.loc.gov/concerts/",
    mediaChannelUrl: "https://www.youtube.com/@LibraryOfCongress",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Library of Congress",
    ownershipEvidenceUrl: "https://www.loc.gov/concerts/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.loc.gov/legal/",
    embedPolicy: "provider_player_required",
    contentScope: "Official Library of Congress concert series and related performance recordings.",
    expectedConcertFormats: ["full_concert", "recital", "cultural_performance"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "gov_site_concerts_page+channel_identity+per_item_class",
    reliabilityScore: 93,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "US government cultural institution. Library of Congress channel also hosts non-concert material; item classification is mandatory.",
  }),
  seed({
    stableKey: "smithsonian-folkways",
    name: "Smithsonian Folkways",
    providerType: "government_cultural",
    provider: "youtube",
    officialUrl: "https://folkways.si.edu/",
    mediaChannelUrl: "https://www.youtube.com/@SmithsonianFolkways",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Smithsonian Institution / Smithsonian Folkways Recordings",
    ownershipEvidenceUrl: "https://folkways.si.edu/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.si.edu/termsofuse",
    embedPolicy: "provider_player_required",
    contentScope: "Official Smithsonian Folkways performance and concert-related publications.",
    expectedConcertFormats: ["cultural_performance", "full_concert", "recital"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "smithsonian_site+channel_identity+per_item_class",
    reliabilityScore: 90,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Smithsonian unit with official channel. Not all uploads are full concerts; classify carefully.",
  }),
  seed({
    stableKey: "juilliard-school",
    name: "The Juilliard School",
    providerType: "conservatory",
    provider: "youtube",
    officialUrl: "https://www.juilliard.edu/",
    mediaChannelUrl: "https://www.youtube.com/@juilliardschool",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "The Juilliard School",
    ownershipEvidenceUrl: "https://www.juilliard.edu/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official conservatory concerts, recitals, and student/faculty performances.",
    expectedConcertFormats: ["recital", "full_concert", "orchestra_performance"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "conservatory_site+channel_identity+per_item_class",
    reliabilityScore: 87,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Major US conservatory official channel.",
  }),
  seed({
    stableKey: "curtis-institute",
    name: "Curtis Institute of Music",
    providerType: "conservatory",
    provider: "youtube",
    officialUrl: "https://www.curtis.edu/",
    mediaChannelUrl: "https://www.youtube.com/@curtisinstitute",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Curtis Institute of Music",
    ownershipEvidenceUrl: "https://www.curtis.edu/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Curtis conservatory concerts and recitals.",
    expectedConcertFormats: ["recital", "full_concert", "orchestra_performance"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "conservatory_site+channel_identity+per_item_class",
    reliabilityScore: 86,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official US conservatory.",
  }),
  seed({
    stableKey: "royal-college-of-music",
    name: "Royal College of Music",
    providerType: "conservatory",
    provider: "youtube",
    officialUrl: "https://www.rcm.ac.uk/",
    mediaChannelUrl: "https://www.youtube.com/@RoyalCollegeofMusic",
    providerChannelId: null,
    countryCode: "GB",
    region: "europe",
    languageCodes: ["en"],
    sourceOwner: "Royal College of Music",
    ownershipEvidenceUrl: "https://www.rcm.ac.uk/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official RCM conservatory performances and concert recordings.",
    expectedConcertFormats: ["recital", "full_concert", "orchestra_performance"],
    supportedCountries: ["GB"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "conservatory_site+channel_identity+per_item_class",
    reliabilityScore: 85,
    lastReviewedAt: REVIEWED,
    reviewNotes: "UK conservatory official presence.",
  }),
  seed({
    stableKey: "san-francisco-symphony",
    name: "San Francisco Symphony",
    providerType: "orchestra",
    provider: "youtube",
    officialUrl: "https://www.sfsymphony.org/",
    mediaChannelUrl: "https://www.youtube.com/@sfsymphony",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "San Francisco Symphony",
    ownershipEvidenceUrl: "https://www.sfsymphony.org/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official SF Symphony concert publications.",
    expectedConcertFormats: ["orchestra_performance", "full_concert"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "orchestra_site+channel_identity+per_item_embed",
    reliabilityScore: 88,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official US orchestra channel.",
  }),
  seed({
    stableKey: "los-angeles-philharmonic",
    name: "Los Angeles Philharmonic",
    providerType: "orchestra",
    provider: "youtube",
    officialUrl: "https://www.laphil.com/",
    mediaChannelUrl: "https://www.youtube.com/@LAPhil",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Los Angeles Philharmonic Association",
    ownershipEvidenceUrl: "https://www.laphil.com/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official LA Phil concert and performance content.",
    expectedConcertFormats: ["orchestra_performance", "full_concert", "venue_broadcast"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "orchestra_site+channel_identity+per_item_embed",
    reliabilityScore: 88,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official US orchestra; Walt Disney Concert Hall venue streams may appear separately.",
  }),
  seed({
    stableKey: "boston-symphony-orchestra",
    name: "Boston Symphony Orchestra",
    providerType: "orchestra",
    provider: "youtube",
    officialUrl: "https://www.bso.org/",
    mediaChannelUrl: "https://www.youtube.com/@BostonSymphony",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Boston Symphony Orchestra, Inc.",
    ownershipEvidenceUrl: "https://www.bso.org/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official BSO concert publications.",
    expectedConcertFormats: ["orchestra_performance", "full_concert"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "orchestra_site+channel_identity+per_item_embed",
    reliabilityScore: 87,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official US orchestra channel.",
  }),
  seed({
    stableKey: "chicago-symphony-orchestra",
    name: "Chicago Symphony Orchestra",
    providerType: "orchestra",
    provider: "youtube",
    officialUrl: "https://cso.org/",
    mediaChannelUrl: "https://www.youtube.com/@chicagosymphony",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Chicago Symphony Orchestra Association",
    ownershipEvidenceUrl: "https://cso.org/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official CSO concert publications.",
    expectedConcertFormats: ["orchestra_performance", "full_concert"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "orchestra_site+channel_identity+per_item_embed",
    reliabilityScore: 87,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official US orchestra channel.",
  }),
  seed({
    stableKey: "npr-music",
    name: "NPR Music",
    providerType: "public_broadcaster",
    provider: "youtube",
    officialUrl: "https://www.npr.org/music",
    mediaChannelUrl: "https://www.youtube.com/@nprmusic",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "National Public Radio, Inc. (NPR Music)",
    ownershipEvidenceUrl: "https://www.npr.org/music",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.npr.org/about-npr/179876898/terms-of-use",
    embedPolicy: "provider_player_required",
    contentScope: "Official NPR Music live performance series (e.g. Tiny Desk) and related free concert sessions.",
    expectedConcertFormats: ["full_concert", "festival_set", "venue_broadcast"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "npr_music_site+channel_identity+per_item_class",
    reliabilityScore: 89,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "US public media music brand. Tiny Desk and similar sessions are performance content; interviews/non-performance must be rejected at import.",
  }),
  seed({
    stableKey: "kexp",
    name: "KEXP",
    providerType: "public_broadcaster",
    provider: "youtube",
    officialUrl: "https://www.kexp.org/",
    mediaChannelUrl: "https://www.youtube.com/@kexp",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Friends of KEXP / KEXP",
    ownershipEvidenceUrl: "https://www.kexp.org/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official KEXP live in-studio performances and concert sessions.",
    expectedConcertFormats: ["venue_broadcast", "full_concert", "festival_set"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "kexp_site+channel_identity+per_item_class",
    reliabilityScore: 88,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Public radio station known for official live performance videos. Non-performance uploads must be filtered.",
  }),
  seed({
    stableKey: "bbc-proms",
    name: "BBC Proms",
    providerType: "public_broadcaster",
    provider: "official_website",
    officialUrl: "https://www.bbc.co.uk/proms",
    mediaChannelUrl: "https://www.bbc.co.uk/proms",
    providerChannelId: null,
    countryCode: "GB",
    region: "europe",
    languageCodes: ["en"],
    sourceOwner: "British Broadcasting Corporation",
    ownershipEvidenceUrl: "https://www.bbc.co.uk/proms",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.bbc.co.uk/usingthebbc/terms/",
    embedPolicy: "region_limited",
    contentScope: "Official BBC Proms festival broadcasts and related concert coverage.",
    expectedConcertFormats: ["festival_set", "full_concert", "orchestra_performance", "livestream"],
    supportedCountries: ["GB"],
    geoRestrictions: { primary: ["GB"], note: "BBC iPlayer/geo rules frequently apply." },
    matureContentPossible: false,
    enabled: true,
    validationMethod: "bbc_proms_site+geo_and_embed_review_per_item",
    reliabilityScore: 84,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official BBC festival brand. Often region-limited and may require BBC player rather than free global embed. Import remains off until per-item playback path is proven.",
  }),
  seed({
    stableKey: "montreux-jazz-festival",
    name: "Montreux Jazz Festival",
    providerType: "official_festival",
    provider: "youtube",
    officialUrl: "https://www.montreuxjazzfestival.com/",
    mediaChannelUrl: "https://www.youtube.com/@MontreuxJazzFestival",
    providerChannelId: null,
    countryCode: "CH",
    region: "europe",
    languageCodes: ["en", "fr"],
    sourceOwner: "Montreux Jazz Festival",
    ownershipEvidenceUrl: "https://www.montreuxjazzfestival.com/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Montreux Jazz Festival performance publications.",
    expectedConcertFormats: ["festival_set", "full_concert", "livestream"],
    supportedCountries: ["CH"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "festival_site+channel_identity+per_item_embed",
    reliabilityScore: 85,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official festival. Historical archives may also appear via broadcasters (e.g. ARTE); prefer source provenance per item.",
  }),
  seed({
    stableKey: "montreal-jazz-festival",
    name: "Festival International de Jazz de Montréal",
    providerType: "official_festival",
    provider: "youtube",
    officialUrl: "https://www.montrealjazzfest.com/",
    mediaChannelUrl: "https://www.youtube.com/@MontrealJazzFestival",
    providerChannelId: null,
    countryCode: "CA",
    region: "americas",
    languageCodes: ["fr", "en"],
    sourceOwner: "Festival International de Jazz de Montréal",
    ownershipEvidenceUrl: "https://www.montrealjazzfest.com/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Montreal Jazz Festival performances and livestreams.",
    expectedConcertFormats: ["festival_set", "full_concert", "livestream"],
    supportedCountries: ["CA"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "festival_site+channel_identity+per_item_embed",
    reliabilityScore: 84,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official Canadian festival channel presence.",
  }),
  seed({
    stableKey: "southbank-centre",
    name: "Southbank Centre",
    providerType: "cultural_institution",
    provider: "youtube",
    officialUrl: "https://www.southbankcentre.co.uk/",
    mediaChannelUrl: "https://www.youtube.com/@SouthbankCentre",
    providerChannelId: null,
    countryCode: "GB",
    region: "europe",
    languageCodes: ["en"],
    sourceOwner: "Southbank Centre",
    ownershipEvidenceUrl: "https://www.southbankcentre.co.uk/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Southbank Centre concert and performance content.",
    expectedConcertFormats: ["venue_broadcast", "full_concert", "cultural_performance"],
    supportedCountries: ["GB"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "venue_site+channel_identity+per_item_class",
    reliabilityScore: 83,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Major UK cultural venue complex with official channel.",
  }),
  seed({
    stableKey: "dutch-national-opera",
    name: "Dutch National Opera & Ballet",
    providerType: "opera_house",
    provider: "youtube",
    officialUrl: "https://www.operaballet.nl/en",
    mediaChannelUrl: "https://www.youtube.com/@DutchNationalOperaBallet",
    providerChannelId: null,
    countryCode: "NL",
    region: "europe",
    languageCodes: ["nl", "en"],
    sourceOwner: "Dutch National Opera & Ballet",
    ownershipEvidenceUrl: "https://www.operaballet.nl/en",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Dutch National Opera & Ballet performance publications.",
    expectedConcertFormats: ["opera", "cultural_performance", "full_concert"],
    supportedCountries: ["NL"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "opera_site+channel_identity+per_item_embed",
    reliabilityScore: 84,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Dutch national opera/ballet company official presence.",
  }),
  seed({
    stableKey: "medici-tv",
    name: "medici.tv",
    providerType: "authorized_platform",
    provider: "authorized_platform",
    officialUrl: "https://www.medici.tv/",
    mediaChannelUrl: "https://www.medici.tv/",
    providerChannelId: null,
    countryCode: "FR",
    region: "europe",
    languageCodes: ["en", "fr"],
    sourceOwner: "medici.tv",
    ownershipEvidenceUrl: "https://www.medici.tv/",
    authorizationBasis: "unclear",
    termsUrl: "https://www.medici.tv/",
    embedPolicy: "unknown",
    contentScope: "Classical performance platform; many titles are subscription-gated.",
    expectedConcertFormats: ["orchestra_performance", "opera", "full_concert"],
    supportedCountries: ["FR"],
    geoRestrictions: { subscription: true },
    matureContentPossible: false,
    enabled: false,
    validationMethod: "manual_rights_and_embed_review",
    reliabilityScore: 40,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Disabled review candidate. Platform is real, but free/embed/in-app rights for Hidden Tunes are not established. Do not import.",
  }),
  seed({
    stableKey: "coachella",
    name: "Coachella",
    providerType: "official_festival",
    provider: "youtube",
    officialUrl: "https://www.coachella.com/",
    mediaChannelUrl: "https://www.youtube.com/@coachella",
    providerChannelId: null,
    countryCode: "US",
    region: "americas",
    languageCodes: ["en"],
    sourceOwner: "Coachella Valley Music and Arts Festival / Goldenvoice",
    ownershipEvidenceUrl: "https://www.coachella.com/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Coachella festival livestreams and performance publications.",
    expectedConcertFormats: ["festival_set", "livestream", "full_concert"],
    supportedCountries: ["US"],
    geoRestrictions: {},
    matureContentPossible: true,
    enabled: true,
    validationMethod: "festival_site+channel_identity+per_item_embed_maturity",
    reliabilityScore: 82,
    lastReviewedAt: REVIEWED,
    reviewNotes:
      "Official festival channel. Mature-content possible; YouTube age/embed gates must never be bypassed. Weekend livestream rights vary by year.",
  }),
  seed({
    stableKey: "tomorrowland",
    name: "Tomorrowland",
    providerType: "official_festival",
    provider: "youtube",
    officialUrl: "https://www.tomorrowland.com/",
    mediaChannelUrl: "https://www.youtube.com/channel/UCsN8M73DMWa8SPp5o_0IAQQ",
    providerChannelId: "UCsN8M73DMWa8SPp5o_0IAQQ",
    countryCode: "BE",
    region: "europe",
    languageCodes: ["en", "nl", "fr"],
    sourceOwner: "Tomorrowland / We Are One World",
    ownershipEvidenceUrl: "https://www.tomorrowland.com/",
    authorizationBasis: "official_owner",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official Tomorrowland festival sets and livestream publications.",
    expectedConcertFormats: ["festival_set", "livestream", "full_concert"],
    supportedCountries: ["BE"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "festival_site+channel_identity+per_item_embed",
    reliabilityScore: 81,
    lastReviewedAt: REVIEWED,
    reviewNotes: "Official electronic music festival channel.",
  }),
  seed({
    stableKey: "university-of-oxford-music",
    name: "University of Oxford Faculty of Music",
    providerType: "university",
    provider: "youtube",
    officialUrl: "https://www.music.ox.ac.uk/",
    mediaChannelUrl: "https://www.youtube.com/@OxfordFacultyofMusic",
    providerChannelId: null,
    countryCode: "GB",
    region: "europe",
    languageCodes: ["en"],
    sourceOwner: "University of Oxford Faculty of Music",
    ownershipEvidenceUrl: "https://www.music.ox.ac.uk/",
    authorizationBasis: "institutional_official",
    termsUrl: "https://www.youtube.com/static?template=terms",
    embedPolicy: "provider_player_required",
    contentScope: "Official university faculty concerts and performance recordings.",
    expectedConcertFormats: ["recital", "full_concert", "orchestra_performance"],
    supportedCountries: ["GB"],
    geoRestrictions: {},
    matureContentPossible: false,
    enabled: true,
    validationMethod: "university_site+channel_identity+per_item_class",
    reliabilityScore: 80,
    lastReviewedAt: REVIEWED,
    reviewNotes: "University faculty channel; confirm handle resolves to faculty-owned channel before import.",
  }),
];

export function getCuratedConcertSources() {
  return CURATED_CONCERT_SOURCES.map((source) => normalizeConcertSourceSeed(source));
}

export function auditCuratedConcertSourceRegistry() {
  const sources = getCuratedConcertSources();
  return {
    total: sources.length,
    ...validateConcertSourceRegistry(sources),
    sources,
  };
}
