import AsyncStorage from '@react-native-async-storage/async-storage';
import { getMobileSupabaseClient, subscribeToMobileAuthState } from './mobileSupabaseAuth';
const INSTALLATION_KEY='hidden-tunes.crossplay.installation.v1';const ACCOUNT_CACHE_KEY='hidden-tunes.crossplay.account-cache.v1';
export type CrossplayContentType='music'|'podcast'|'audiobook'|'lecture'|'motivational'|'radio'|'tv';
function randomId(){const bytes=new Uint8Array(24);globalThis.crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
export async function mobileInstallationId(){let id=await AsyncStorage.getItem(INSTALLATION_KEY);if(!id){id=randomId();await AsyncStorage.setItem(INSTALLATION_KEY,id)}return id}
export async function clearMobileCrossplayAccountCache(){await AsyncStorage.removeItem(ACCOUNT_CACHE_KEY)}
subscribeToMobileAuthState(()=>{void clearMobileCrossplayAccountCache()});
export async function registerMobileDevice(input:{name:string;deviceClass:'phone'|'tablet';appVersion:string}){const client=getMobileSupabaseClient();if(!client)return null;const {data,error}=await client.rpc('crossplay_register_device',{p_public_id:await mobileInstallationId(),p_name:input.name,p_platform:'mobile',p_class:input.deviceClass,p_app_version:input.appVersion,p_capabilities:{continueAnywhere:true,receiveHandoff:false,remoteTarget:false}});if(error)throw error;return data}
export async function listContinueAnywhere(limit=8){const client=getMobileSupabaseClient();if(!client)return[];const {data,error}=await client.from('playback_progress').select('content_type,content_id,item_id,position_ms,duration_ms,completion_state,version,updated_at,safe_metadata,user_devices!playback_progress_last_device_id_fkey(device_name,platform)').eq('completion_state','in_progress').order('updated_at',{ascending:false}).limit(Math.min(8,Math.max(1,limit)));if(error)throw error;await AsyncStorage.setItem(ACCOUNT_CACHE_KEY,JSON.stringify(data||[]));return data||[]}
export async function loadCachedContinueAnywhere(){try{return JSON.parse(await AsyncStorage.getItem(ACCOUNT_CACHE_KEY)||'[]')}catch{return[]}}
export async function writeMobileProgress(input:{deviceId:string;type:CrossplayContentType;contentId:string;itemId?:string;positionMs:number|null;durationMs:number|null;completion?:'in_progress'|'completed';expectedVersion:number;metadata?:Record<string,unknown>}){const client=getMobileSupabaseClient();if(!client)return null;const {data,error}=await client.rpc('crossplay_write_progress',{p_device_id:input.deviceId,p_content_type:input.type,p_content_id:input.contentId,p_item_id:input.itemId||'',p_position_ms:input.positionMs,p_duration_ms:input.durationMs,p_completion:input.completion||'in_progress',p_expected_version:input.expectedVersion,p_metadata:input.metadata||{}});if(error)throw error;return data}
export async function revokeMobileDevice(deviceId:string){const client=getMobileSupabaseClient();if(!client)return;const{error}=await client.rpc('crossplay_revoke_device',{p_device_id:deviceId});if(error)throw error}
export function safeResumeMs(type:CrossplayContentType,position:number,duration:number|null){if(type==='radio'||type==='tv')return null;if(duration!==null&&duration<30_000)return 0;return Math.max(0,position-((type==='podcast'||type==='audiobook'||type==='lecture')?10_000:type==='music'?3_000:5_000))}
