/**
 * Controlled Asia radio expansion queue (West, Central, South, East, Southeast).
 */
import type { WorldwideRadioCountry } from "@/lib/radioWorldwideExpansion/types";

export const ASIA_RADIO_QUEUE: WorldwideRadioCountry[] = [
  {
    code: "TR",
    name: "Turkey",
    continent: "asia",
    aliases: ["Türkiye"],
    cities: ["Istanbul","Ankara","Izmir","Bursa","Antalya","Adana","Gaziantep","Konya","Kayseri","Mersin","Eskişehir","Diyarbakır","Samsun","Denizli"],
    states: ["Istanbul","Ankara","Izmir","Bursa","Antalya","Adana","Konya","Gaziantep","Şanlıurfa","Mersin","Kocaeli","Diyarbakır","Hatay","Manisa","Kayseri","Samsun","Balıkesir","Kahramanmaraş","Van","Aydın"],
    languages: ["turkish","kurdish","arabic","zazaki"],
    tags: ["turkey","news","arabesque","folk","classical","public","community","university"],
  },
  {
    code: "IL",
    name: "Israel",
    continent: "asia",
    cities: ["Jerusalem","Tel Aviv","Haifa","Rishon LeZion","Petah Tikva","Ashdod","Netanya","Beersheba","Bnei Brak","Holon"],
    states: ["Jerusalem","Tel Aviv","Haifa","Central","Northern","Southern","Judea and Samaria"],
    languages: ["hebrew","arabic","russian","english"],
    tags: ["israel","news","classical","jazz","folk","public","community","university","religious"],
  },
  {
    code: "PS",
    name: "Palestine",
    continent: "asia",
    aliases: ["State of Palestine","Palestinian Territories"],
    cities: ["Ramallah","Gaza","Hebron","Nablus","Bethlehem","Jenin","Jericho"],
    states: ["West Bank","Gaza Strip","Ramallah","Hebron","Nablus","Bethlehem","Jenin"],
    languages: ["arabic","hebrew"],
    tags: ["palestine","news","folk","community","public"],
  },
  {
    code: "JO",
    name: "Jordan",
    continent: "asia",
    cities: ["Amman","Zarqa","Irbid","Aqaba","Salt","Madaba"],
    states: ["Amman","Zarqa","Irbid","Balqa","Karak","Aqaba","Mafraq"],
    languages: ["arabic"],
    tags: ["jordan","news","public","community"],
  },
  {
    code: "LB",
    name: "Lebanon",
    continent: "asia",
    cities: ["Beirut","Tripoli","Sidon","Tyre","Zahlé","Jounieh"],
    states: ["Beirut","Mount Lebanon","North","South","Bekaa","Nabatieh","Akkar","Baalbek-Hermel"],
    languages: ["arabic","french","english","armenian"],
    tags: ["lebanon","news","classical","jazz","public","community"],
  },
  {
    code: "SY",
    name: "Syria",
    continent: "asia",
    cities: ["Damascus","Aleppo","Homs","Latakia","Hama","Tartus"],
    states: ["Damascus","Aleppo","Homs","Latakia","Hama","Tartus","Idlib","Daraa"],
    languages: ["arabic","kurdish","armenian"],
    tags: ["syria","news","folk","public","community"],
  },
  {
    code: "IQ",
    name: "Iraq",
    continent: "asia",
    cities: ["Baghdad","Basra","Mosul","Erbil","Kirkuk","Najaf","Karbala","Sulaymaniyah"],
    states: ["Baghdad","Basra","Nineveh","Erbil","Kirkuk","Najaf","Karbala","Sulaymaniyah","Anbar","Diyala"],
    languages: ["arabic","kurdish","turkmen"],
    tags: ["iraq","news","folk","public","community"],
  },
  {
    code: "IR",
    name: "Iran",
    continent: "asia",
    cities: ["Tehran","Mashhad","Isfahan","Karaj","Shiraz","Tabriz","Qom","Ahvaz","Kermanshah","Urmia"],
    states: ["Tehran","Razavi Khorasan","Isfahan","Fars","East Azerbaijan","Khuzestan","Mazandaran","West Azerbaijan","Kerman","Alborz","Gilan","Sistan and Baluchestan"],
    languages: ["persian","azerbaijani","kurdish","luri","balochi","arabic"],
    tags: ["iran","news","classical","folk","public","community"],
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    continent: "asia",
    cities: ["Riyadh","Jeddah","Mecca","Medina","Dammam","Khobar","Taif","Tabuk","Buraidah","Abha"],
    states: ["Riyadh","Makkah","Eastern Province","Madinah","Asir","Qassim","Tabuk","Hail","Jazan","Najran","Northern Borders","Al Bahah","Al Jawf"],
    languages: ["arabic"],
    tags: ["saudi","news","islamic","public","community"],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    continent: "asia",
    aliases: ["UAE"],
    cities: ["Dubai","Abu Dhabi","Sharjah","Ajman","Ras Al Khaimah","Fujairah","Al Ain"],
    states: ["Abu Dhabi","Dubai","Sharjah","Ajman","Umm Al Quwain","Ras Al Khaimah","Fujairah"],
    languages: ["arabic","english","hindi","urdu","malayalam"],
    tags: ["uae","dubai","news","public","community","jazz","classical"],
  },
  {
    code: "QA",
    name: "Qatar",
    continent: "asia",
    cities: ["Doha","Al Rayyan","Al Wakrah","Al Khor"],
    languages: ["arabic","english"],
    tags: ["qatar","news","public","community"],
  },
  {
    code: "BH",
    name: "Bahrain",
    continent: "asia",
    cities: ["Manama","Riffa","Muharraq","Hamad Town"],
    languages: ["arabic","english"],
    tags: ["bahrain","news","public","community"],
  },
  {
    code: "KW",
    name: "Kuwait",
    continent: "asia",
    cities: ["Kuwait City","Hawalli","Salmiya","Jahra","Farwaniya"],
    states: ["Capital","Hawalli","Farwaniya","Ahmadi","Jahra","Mubarak Al-Kabeer"],
    languages: ["arabic","english"],
    tags: ["kuwait","news","public","community"],
  },
  {
    code: "OM",
    name: "Oman",
    continent: "asia",
    cities: ["Muscat","Salalah","Sohar","Nizwa","Sur"],
    states: ["Muscat","Dhofar","Al Batinah North","Ad Dakhiliyah","Ash Sharqiyah South"],
    languages: ["arabic"],
    tags: ["oman","news","public","community"],
  },
  {
    code: "YE",
    name: "Yemen",
    continent: "asia",
    cities: ["Sana'a","Aden","Taiz","Al Hudaydah","Ibb","Mukalla"],
    states: ["Sana'a","Aden","Taiz","Al Hudaydah","Ibb","Hadhramaut"],
    languages: ["arabic"],
    tags: ["yemen","news","folk","community"],
  },
  {
    code: "GE",
    name: "Georgia",
    continent: "asia",
    cities: ["Tbilisi","Batumi","Kutaisi","Rustavi","Zugdidi","Gori"],
    states: ["Tbilisi","Adjara","Imereti","Kvemo Kartli","Samegrelo-Zemo Svaneti","Kakheti","Shida Kartli"],
    languages: ["georgian","russian","armenian","azerbaijani"],
    tags: ["georgia","news","folk","classical","public","community"],
  },
  {
    code: "AM",
    name: "Armenia",
    continent: "asia",
    cities: ["Yerevan","Gyumri","Vanadzor","Vagharshapat","Hrazdan"],
    states: ["Yerevan","Shirak","Lori","Armavir","Ararat","Kotayk","Gegharkunik"],
    languages: ["armenian","russian"],
    tags: ["armenia","news","folk","classical","public","community"],
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    continent: "asia",
    cities: ["Baku","Ganja","Sumqayit","Mingachevir","Lankaran","Shirvan"],
    states: ["Baku","Ganja-Dashkasan","Absheron-Khizi","Lankaran-Astara","Shaki-Zagatala","Karabakh"],
    languages: ["azerbaijani","russian"],
    tags: ["azerbaijan","news","mugham","folk","public","community"],
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    continent: "asia",
    cities: ["Almaty","Astana","Shymkent","Karaganda","Aktobe","Taraz","Pavlodar","Semey","Oskemen"],
    states: ["Almaty","Astana","Shymkent","Karaganda","Aktobe","East Kazakhstan","Kostanay","Pavlodar","Atyrau","Mangystau","West Kazakhstan","North Kazakhstan","Zhambyl","Turkistan","Kyzylorda","Akmola"],
    languages: ["kazakh","russian"],
    tags: ["kazakhstan","news","folk","public","community"],
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    continent: "asia",
    cities: ["Tashkent","Samarkand","Namangan","Andijan","Bukhara","Nukus","Fergana","Qarshi"],
    states: ["Tashkent","Samarkand","Namangan","Andijan","Fergana","Bukhara","Kashkadarya","Surkhandarya","Khorezm","Navoiy","Jizzakh","Sirdaryo","Karakalpakstan"],
    languages: ["uzbek","russian","karakalpak","tajik"],
    tags: ["uzbekistan","news","folk","public","community"],
  },
  {
    code: "TM",
    name: "Turkmenistan",
    continent: "asia",
    cities: ["Ashgabat","Türkmenabat","Daşoguz","Mary","Balkanabat"],
    states: ["Ashgabat","Ahal","Balkan","Daşoguz","Lebap","Mary"],
    languages: ["turkmen","russian"],
    tags: ["turkmenistan","news","folk","public"],
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    continent: "asia",
    cities: ["Bishkek","Osh","Jalal-Abad","Karakol","Tokmok"],
    states: ["Bishkek","Chüy","Osh","Jalal-Abad","Issyk-Kul","Naryn","Talas","Batken"],
    languages: ["kyrgyz","russian","uzbek"],
    tags: ["kyrgyzstan","news","folk","public","community"],
  },
  {
    code: "TJ",
    name: "Tajikistan",
    continent: "asia",
    cities: ["Dushanbe","Khujand","Bokhtar","Kulob","Istaravshan"],
    states: ["Dushanbe","Sughd","Khatlon","Gorno-Badakhshan","Districts of Republican Subordination"],
    languages: ["tajik","russian","uzbek"],
    tags: ["tajikistan","news","folk","public","community"],
  },
  {
    code: "AF",
    name: "Afghanistan",
    continent: "asia",
    cities: ["Kabul","Kandahar","Herat","Mazar-i-Sharif","Jalalabad","Kunduz"],
    states: ["Kabul","Kandahar","Herat","Balkh","Nangarhar","Kunduz","Ghazni"],
    languages: ["dari","pashto","uzbek","turkmen"],
    tags: ["afghanistan","news","folk","community"],
  },
  {
    code: "PK",
    name: "Pakistan",
    continent: "asia",
    cities: ["Karachi","Lahore","Islamabad","Faisalabad","Rawalpindi","Multan","Peshawar","Quetta","Hyderabad","Gujranwala","Sialkot"],
    states: ["Punjab","Sindh","Khyber Pakhtunkhwa","Balochistan","Islamabad Capital Territory","Gilgit-Baltistan","Azad Kashmir"],
    languages: ["urdu","english","punjabi","pashto","sindhi","balochi","saraiki"],
    tags: ["pakistan","news","qawwali","folk","public","community","islamic","university"],
  },
  {
    code: "IN",
    name: "India",
    continent: "asia",
    cities: ["Mumbai","Delhi","Bengaluru","Hyderabad","Chennai","Kolkata","Pune","Ahmedabad","Jaipur","Lucknow","Kanpur","Nagpur","Indore","Thane","Bhopal","Visakhapatnam","Patna","Vadodara","Ghaziabad","Ludhiana","Agra","Nashik","Faridabad","Meerut","Rajkot","Varanasi","Srinagar","Amritsar","Ranchi","Guwahati","Chandigarh","Thiruvananthapuram","Kochi","Coimbatore","Madurai"],
    states: ["Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Delhi","Jammu and Kashmir","Ladakh","Puducherry","Chandigarh","Andaman and Nicobar Islands","Dadra and Nagar Haveli and Daman and Diu","Lakshadweep"],
    languages: ["hindi","english","bengali","telugu","marathi","tamil","urdu","gujarati","kannada","odia","malayalam","punjabi","assamese"],
    tags: ["india","news","bollywood","classical","carnatic","hindustani","folk","public","community","university","devotional","jazz"],
  },
  {
    code: "BD",
    name: "Bangladesh",
    continent: "asia",
    cities: ["Dhaka","Chittagong","Khulna","Rajshahi","Sylhet","Barisal","Rangpur","Comilla","Narayanganj"],
    states: ["Dhaka","Chittagong","Khulna","Rajshahi","Sylhet","Barisal","Rangpur","Mymensingh"],
    languages: ["bengali","english"],
    tags: ["bangladesh","news","folk","public","community","university"],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    continent: "asia",
    cities: ["Colombo","Kandy","Galle","Jaffna","Negombo","Trincomalee","Batticaloa","Anuradhapura"],
    states: ["Western","Central","Southern","Northern","Eastern","North Western","North Central","Uva","Sabaragamuwa"],
    languages: ["sinhala","tamil","english"],
    tags: ["sri lanka","news","folk","public","community"],
  },
  {
    code: "NP",
    name: "Nepal",
    continent: "asia",
    cities: ["Kathmandu","Pokhara","Lalitpur","Bharatpur","Biratnagar","Birgunj","Dharan"],
    states: ["Bagmati","Gandaki","Koshi","Madhesh","Lumbini","Karnali","Sudurpashchim"],
    languages: ["nepali","maithili","bhojpuri","newari","english"],
    tags: ["nepal","news","folk","public","community"],
  },
  {
    code: "BT",
    name: "Bhutan",
    continent: "asia",
    cities: ["Thimphu","Phuntsholing","Paro","Punakha"],
    languages: ["dzongkha","english"],
    tags: ["bhutan","news","folk","public"],
  },
  {
    code: "MV",
    name: "Maldives",
    continent: "asia",
    cities: ["Malé","Addu City","Fuvahmulah","Kulhudhuffushi"],
    languages: ["dhivehi","english"],
    tags: ["maldives","news","community","islamic"],
  },
  {
    code: "CN",
    name: "China",
    continent: "asia",
    cities: ["Beijing","Shanghai","Guangzhou","Shenzhen","Chengdu","Chongqing","Tianjin","Wuhan","Hangzhou","Xi'an","Nanjing","Suzhou","Zhengzhou","Changsha","Qingdao","Dalian","Xiamen","Kunming","Harbin","Shenyang","Jinan","Fuzhou","Ningbo","Hefei"],
    states: ["Beijing","Shanghai","Guangdong","Sichuan","Zhejiang","Jiangsu","Shandong","Henan","Hubei","Hunan","Anhui","Fujian","Jiangxi","Liaoning","Heilongjiang","Jilin","Yunnan","Guizhou","Guangxi","Shaanxi","Shanxi","Hebei","Chongqing","Tianjin","Inner Mongolia","Xinjiang","Tibet","Qinghai","Ningxia","Gansu","Hainan"],
    languages: ["chinese","mandarin","cantonese","wu","min","hakka","tibetan","uyghur","mongolian"],
    tags: ["china","news","classical","folk","public","community","university","opera"],
  },
  {
    code: "JP",
    name: "Japan",
    continent: "asia",
    cities: ["Tokyo","Osaka","Yokohama","Nagoya","Sapporo","Fukuoka","Kobe","Kyoto","Kawasaki","Saitama","Hiroshima","Sendai","Chiba","Kitakyushu","Sakai"],
    states: ["Tokyo","Osaka","Kanagawa","Aichi","Hokkaido","Fukuoka","Hyogo","Kyoto","Saitama","Chiba","Hiroshima","Miyagi","Shizuoka","Ibaraki","Okinawa","Niigata","Nagano","Gifu","Tochigi","Gunma","Okayama","Kumamoto","Kagoshima","Mie","Ehime"],
    languages: ["japanese"],
    tags: ["japan","news","classical","jazz","j-pop","anime","public","community","university","folk"],
  },
  {
    code: "KR",
    name: "South Korea",
    continent: "asia",
    aliases: ["Korea","Republic of Korea"],
    cities: ["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju","Suwon","Ulsan","Changwon","Goyang"],
    states: ["Seoul","Busan","Incheon","Daegu","Daejeon","Gwangju","Ulsan","Gyeonggi","Gangwon","North Chungcheong","South Chungcheong","North Jeolla","South Jeolla","North Gyeongsang","South Gyeongsang","Jeju"],
    languages: ["korean"],
    tags: ["korea","south korea","k-pop","news","classical","jazz","public","community","university"],
  },
  {
    code: "KP",
    name: "North Korea",
    continent: "asia",
    aliases: ["DPRK","Democratic People's Republic of Korea"],
    cities: ["Pyongyang","Hamhung","Chongjin","Nampo","Wonsan","Sinuiju"],
    states: ["Pyongyang","South Pyongan","North Pyongan","South Hamgyong","North Hamgyong","Kangwon","South Hwanghae","North Hwanghae","Ryanggang","Jagang"],
    languages: ["korean"],
    tags: ["north korea","news","public"],
    notes: ["Prefer lawful publicly available official/educational feeds only"],
  },
  {
    code: "MN",
    name: "Mongolia",
    continent: "asia",
    cities: ["Ulaanbaatar","Erdenet","Darkhan","Choibalsan","Mörön"],
    states: ["Ulaanbaatar","Orkhon","Darkhan-Uul","Khentii","Khövsgöl","Övörkhangai","Selenge","Bayan-Ölgii"],
    languages: ["mongolian","kazakh"],
    tags: ["mongolia","news","folk","public","community"],
  },
  {
    code: "TW",
    name: "Taiwan",
    continent: "asia",
    cities: ["Taipei","Kaohsiung","Taichung","Tainan","Hsinchu","Taoyuan","Keelung","Chiayi"],
    states: ["Taipei","New Taipei","Taoyuan","Taichung","Tainan","Kaohsiung","Hsinchu","Keelung","Chiayi","Changhua","Pingtung","Yunlin","Nantou","Yilan","Hualien","Taitung","Penghu","Kinmen","Lienchiang"],
    languages: ["chinese","mandarin","taiwanese","hakka","english"],
    tags: ["taiwan","news","classical","jazz","public","community","university","pop"],
  },
  {
    code: "HK",
    name: "Hong Kong",
    continent: "asia",
    cities: ["Hong Kong","Kowloon","Tsuen Wan","Sha Tin","Tuen Mun","Tai Po"],
    languages: ["chinese","cantonese","english","mandarin"],
    tags: ["hong kong","news","cantopop","public","community","classical","jazz"],
  },
  {
    code: "MO",
    name: "Macau",
    continent: "asia",
    aliases: ["Macao"],
    cities: ["Macau","Taipa","Coloane"],
    languages: ["chinese","cantonese","portuguese","english"],
    tags: ["macau","news","public","community"],
  },
  {
    code: "TH",
    name: "Thailand",
    continent: "asia",
    cities: ["Bangkok","Chiang Mai","Pattaya","Phuket","Hat Yai","Nakhon Ratchasima","Khon Kaen","Chiang Rai","Udon Thani","Surat Thani"],
    states: ["Bangkok","Chiang Mai","Chonburi","Phuket","Songkhla","Nakhon Ratchasima","Khon Kaen","Chiang Rai","Udon Thani","Surat Thani","Nonthaburi","Pathum Thani","Samut Prakan","Rayong"],
    languages: ["thai","english","isan","northern thai"],
    tags: ["thailand","news","luk thung","mor lam","public","community","university"],
  },
  {
    code: "VN",
    name: "Vietnam",
    continent: "asia",
    cities: ["Ho Chi Minh City","Hanoi","Da Nang","Hai Phong","Can Tho","Bien Hoa","Nha Trang","Hue","Vung Tau","Buon Ma Thuot"],
    states: ["Ho Chi Minh City","Hanoi","Da Nang","Hai Phong","Can Tho","Dong Nai","Binh Duong","Khanh Hoa","Thua Thien Hue","Quang Ninh","An Giang","Dong Thap","Lam Dong"],
    languages: ["vietnamese"],
    tags: ["vietnam","news","folk","public","community","university"],
  },
  {
    code: "MY",
    name: "Malaysia",
    continent: "asia",
    cities: ["Kuala Lumpur","George Town","Johor Bahru","Ipoh","Shah Alam","Petaling Jaya","Kota Kinabalu","Kuching","Malacca City","Alor Setar"],
    states: ["Selangor","Johor","Sabah","Sarawak","Perak","Kedah","Kelantan","Penang","Pahang","Negeri Sembilan","Terengganu","Malacca","Perlis","Kuala Lumpur","Putrajaya","Labuan"],
    languages: ["malay","english","chinese","tamil"],
    tags: ["malaysia","news","public","community","university","islamic","pop"],
  },
  {
    code: "SG",
    name: "Singapore",
    continent: "asia",
    cities: ["Singapore","Jurong","Woodlands","Tampines","Bedok"],
    languages: ["english","mandarin","malay","tamil"],
    tags: ["singapore","news","classical","jazz","public","community","university"],
  },
  {
    code: "ID",
    name: "Indonesia",
    continent: "asia",
    cities: ["Jakarta","Surabaya","Bandung","Medan","Semarang","Makassar","Palembang","Depok","Tangerang","Bekasi","Denpasar","Yogyakarta","Malang","Padang","Balikpapan","Manado","Pontianak","Banjarmasin"],
    states: ["Jakarta","West Java","East Java","Central Java","North Sumatra","Banten","South Sulawesi","South Sumatra","Lampung","Riau","Bali","East Kalimantan","West Kalimantan","South Kalimantan","Papua","West Papua","Aceh","West Sumatra","Yogyakarta","North Sulawesi"],
    languages: ["indonesian","javanese","sundanese","balinese","madurese","minangkabau","buginese"],
    tags: ["indonesia","news","dangdut","gamelan","public","community","university","islamic","pop"],
  },
  {
    code: "PH",
    name: "Philippines",
    continent: "asia",
    cities: ["Manila","Quezon City","Davao","Cebu City","Zamboanga","Antipolo","Pasig","Cagayan de Oro","Parañaque","Dasmariñas","Baguio","Iloilo","Bacolod","General Santos"],
    states: ["Metro Manila","Cebu","Davao","Cavite","Laguna","Rizal","Bulacan","Pampanga","Batangas","Negros Occidental","Pangasinan","Iloilo","Quezon","Nueva Ecija","Zamboanga del Sur","Baguio"],
    languages: ["filipino","english","tagalog","cebuano","ilocano","hiligaynon","waray"],
    tags: ["philippines","news","opm","public","community","university","gospel","jazz"],
  },
  {
    code: "MM",
    name: "Myanmar",
    continent: "asia",
    aliases: ["Burma"],
    cities: ["Yangon","Mandalay","Naypyidaw","Mawlamyine","Bago","Pathein","Monywa"],
    states: ["Yangon","Mandalay","Naypyidaw","Shan","Sagaing","Bago","Magway","Ayeyarwady","Mon","Rakhine","Kachin","Kayin","Chin","Kayah","Tanintharyi"],
    languages: ["burmese","shan","karen","kachin","chin","mon","rakhine"],
    tags: ["myanmar","burma","news","folk","public","community"],
  },
  {
    code: "KH",
    name: "Cambodia",
    continent: "asia",
    cities: ["Phnom Penh","Siem Reap","Battambang","Sihanoukville","Kampong Cham"],
    states: ["Phnom Penh","Siem Reap","Battambang","Sihanoukville","Kampong Cham","Kandal","Takeo"],
    languages: ["khmer","english"],
    tags: ["cambodia","news","folk","public","community"],
  },
  {
    code: "LA",
    name: "Laos",
    continent: "asia",
    aliases: ["Lao PDR"],
    cities: ["Vientiane","Luang Prabang","Pakse","Savannakhet","Thakhek"],
    states: ["Vientiane","Luang Prabang","Champasak","Savannakhet","Khammouane","Xiangkhouang"],
    languages: ["lao","french","english"],
    tags: ["laos","news","folk","public","community"],
  },
  {
    code: "BN",
    name: "Brunei",
    continent: "asia",
    cities: ["Bandar Seri Begawan","Kuala Belait","Seria","Tutong"],
    states: ["Brunei-Muara","Belait","Tutong","Temburong"],
    languages: ["malay","english"],
    tags: ["brunei","news","islamic","public","community"],
  },
  {
    code: "TL",
    name: "Timor-Leste",
    continent: "asia",
    aliases: ["East Timor"],
    cities: ["Dili","Baucau","Maliana","Suai"],
    states: ["Dili","Baucau","Bobonaro","Cova Lima","Ermera","Lautém"],
    languages: ["tetum","portuguese","indonesian","english"],
    tags: ["timor-leste","east timor","news","community","public"],
  },
];
