/**
 * Controlled Europe radio expansion queue. Process one country/territory at a time.
 */
import type { WorldwideRadioCountry } from "@/lib/radioWorldwideExpansion/types";

export const EUROPE_RADIO_QUEUE: WorldwideRadioCountry[] = [
  {
    code: "DE",
    name: "Germany",
    continent: "europe",
    cities: ["Berlin","Hamburg","Munich","Cologne","Frankfurt","Stuttgart","Düsseldorf","Dortmund","Essen","Leipzig","Bremen","Dresden","Hannover","Nuremberg","Bonn"],
    states: ["Baden-Württemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"],
    languages: ["german"],
    tags: ["germany","news","classical","jazz","folk","public","community","university","rock","electronic"],
  },
  {
    code: "FR",
    name: "France",
    continent: "europe",
    cities: ["Paris","Marseille","Lyon","Toulouse","Nice","Nantes","Strasbourg","Montpellier","Bordeaux","Lille","Rennes","Reims","Saint-Étienne","Toulon","Le Havre"],
    states: ["Île-de-France","Provence-Alpes-Côte d'Azur","Auvergne-Rhône-Alpes","Occitanie","Nouvelle-Aquitaine","Hauts-de-France","Grand Est","Brittany","Normandy","Pays de la Loire","Centre-Val de Loire","Bourgogne-Franche-Comté","Corsica"],
    languages: ["french","breton","occitan","basque","catalan","corsican"],
    tags: ["france","news","classical","jazz","chanson","public","community","university","electronic"],
  },
  {
    code: "IT",
    name: "Italy",
    continent: "europe",
    cities: ["Rome","Milan","Naples","Turin","Palermo","Genoa","Bologna","Florence","Bari","Catania","Venice","Verona","Messina","Padua","Trieste"],
    states: ["Lazio","Lombardy","Campania","Piedmont","Sicily","Veneto","Emilia-Romagna","Tuscany","Apulia","Liguria","Calabria","Sardinia","Marche","Abruzzo","Friuli-Venezia Giulia","Trentino-Alto Adige","Umbria","Basilicata","Molise","Aosta Valley"],
    languages: ["italian","german","french","sardinian","sicilian"],
    tags: ["italy","news","classical","opera","jazz","folk","public","community","university"],
  },
  {
    code: "ES",
    name: "Spain",
    continent: "europe",
    cities: ["Madrid","Barcelona","Valencia","Seville","Zaragoza","Málaga","Murcia","Palma","Las Palmas","Bilbao","Alicante","Córdoba","Valladolid","Vigo","Gijón"],
    states: ["Andalusia","Catalonia","Community of Madrid","Valencian Community","Galicia","Castile and León","Basque Country","Canary Islands","Castile-La Mancha","Region of Murcia","Aragon","Extremadura","Balearic Islands","Asturias","Navarre","Cantabria","La Rioja","Ceuta","Melilla"],
    languages: ["spanish","catalan","galician","basque"],
    tags: ["spain","news","flamenco","classical","jazz","folk","public","community","university"],
  },
  {
    code: "GB",
    name: "United Kingdom",
    continent: "europe",
    aliases: ["UK","Great Britain","Britain","England","Scotland","Wales","Northern Ireland"],
    cities: ["London","Birmingham","Manchester","Glasgow","Liverpool","Leeds","Edinburgh","Bristol","Sheffield","Cardiff","Belfast","Newcastle","Nottingham","Leicester","Coventry","Aberdeen","Swansea","Derry"],
    states: ["England","Scotland","Wales","Northern Ireland","Greater London","West Midlands","Greater Manchester","West Yorkshire","Merseyside","South Yorkshire","Tyne and Wear"],
    languages: ["english","welsh","scottish gaelic","irish"],
    tags: ["uk","britain","bbc","news","classical","jazz","folk","community","university","public","indie","rock"],
  },
  {
    code: "PL",
    name: "Poland",
    continent: "europe",
    cities: ["Warsaw","Kraków","Łódź","Wrocław","Poznań","Gdańsk","Szczecin","Bydgoszcz","Lublin","Białystok","Katowice","Gdynia"],
    states: ["Masovian","Lesser Poland","Silesian","Greater Poland","Lower Silesian","Łódź","Pomeranian","Lublin","West Pomeranian","Podlaskie","Warmian-Masurian","Świętokrzyskie","Podkarpackie","Lubusz","Opole","Kuyavian-Pomeranian"],
    languages: ["polish"],
    tags: ["poland","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "NL",
    name: "Netherlands",
    continent: "europe",
    cities: ["Amsterdam","Rotterdam","The Hague","Utrecht","Eindhoven","Groningen","Tilburg","Almere","Breda","Nijmegen","Haarlem","Arnhem"],
    states: ["North Holland","South Holland","Utrecht","North Brabant","Gelderland","Overijssel","Limburg","Friesland","Groningen","Drenthe","Flevoland","Zeeland"],
    languages: ["dutch","frisian","english"],
    tags: ["netherlands","holland","news","classical","jazz","public","community","university","electronic"],
  },
  {
    code: "SE",
    name: "Sweden",
    continent: "europe",
    cities: ["Stockholm","Gothenburg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Jönköping","Norrköping","Lund","Umeå"],
    states: ["Stockholm","Västra Götaland","Skåne","Östergötland","Uppsala","Jönköping","Halland","Örebro","Södermanland","Dalarna","Gävleborg","Värmland","Västmanland","Västerbotten","Norrbotten","Västernorrland","Kalmar","Kronoberg","Blekinge","Gotland","Jämtland"],
    languages: ["swedish","finnish","sami"],
    tags: ["sweden","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "NO",
    name: "Norway",
    continent: "europe",
    cities: ["Oslo","Bergen","Trondheim","Stavanger","Drammen","Fredrikstad","Kristiansand","Tromsø","Sandnes","Ålesund"],
    states: ["Oslo","Viken","Vestland","Rogaland","Trøndelag","Innlandet","Agder","Troms og Finnmark","Møre og Romsdal","Nordland","Vestfold og Telemark"],
    languages: ["norwegian","sami"],
    tags: ["norway","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "FI",
    name: "Finland",
    continent: "europe",
    cities: ["Helsinki","Espoo","Tampere","Vantaa","Oulu","Turku","Jyväskylä","Lahti","Kuopio","Pori"],
    states: ["Uusimaa","Pirkanmaa","Southwest Finland","North Ostrobothnia","Central Finland","Satakunta","Päijät-Häme","Kymenlaakso","South Karelia","North Karelia","Northern Savonia","Southern Savonia","Ostrobothnia","Central Ostrobothnia","South Ostrobothnia","Kainuu","Lapland","Åland"],
    languages: ["finnish","swedish","sami"],
    tags: ["finland","news","classical","jazz","folk","public","community","university","metal"],
  },
  {
    code: "PT",
    name: "Portugal",
    continent: "europe",
    cities: ["Lisbon","Porto","Braga","Coimbra","Funchal","Setúbal","Aveiro","Faro","Évora","Ponta Delgada"],
    states: ["Lisbon","Porto","Braga","Aveiro","Setúbal","Faro","Coimbra","Leiria","Santarém","Viseu","Madeira","Azores","Vila Real","Castelo Branco","Beja","Évora","Guarda","Bragança","Portalegre","Viana do Castelo"],
    languages: ["portuguese","mirandese"],
    tags: ["portugal","news","fado","classical","jazz","folk","public","community","university"],
  },
  {
    code: "RO",
    name: "Romania",
    continent: "europe",
    cities: ["Bucharest","Cluj-Napoca","Timișoara","Iași","Constanța","Craiova","Brașov","Galați","Ploiești","Oradea","Sibiu"],
    states: ["Bucharest","Cluj","Timiș","Iași","Constanța","Dolj","Brașov","Galați","Prahova","Bihor","Sibiu","Mureș","Argeș","Bacău","Suceava"],
    languages: ["romanian","hungarian","german"],
    tags: ["romania","news","classical","folk","public","community","university"],
  },
  {
    code: "UA",
    name: "Ukraine",
    continent: "europe",
    cities: ["Kyiv","Kharkiv","Odesa","Dnipro","Lviv","Zaporizhzhia","Vinnytsia","Mykolaiv","Poltava","Chernihiv","Chernivtsi"],
    states: ["Kyiv","Kharkiv","Odesa","Dnipropetrovsk","Lviv","Zaporizhzhia","Vinnytsia","Mykolaiv","Poltava","Chernihiv","Chernivtsi","Ivano-Frankivsk","Ternopil","Volyn","Zakarpattia","Zhytomyr","Sumy","Kirovohrad","Rivne","Khmelnytskyi","Cherkasy"],
    languages: ["ukrainian","russian","crimean tatar"],
    tags: ["ukraine","news","classical","folk","public","community","university"],
  },
  {
    code: "GR",
    name: "Greece",
    continent: "europe",
    cities: ["Athens","Thessaloniki","Patras","Heraklion","Larissa","Volos","Rhodes","Ioannina","Chania","Kalamata"],
    states: ["Attica","Central Macedonia","Crete","Thessaly","Western Greece","Peloponnese","Central Greece","East Macedonia and Thrace","Epirus","South Aegean","North Aegean","Ionian Islands","Western Macedonia"],
    languages: ["greek"],
    tags: ["greece","news","classical","folk","public","community","university","rebetiko"],
  },
  {
    code: "CZ",
    name: "Czechia",
    continent: "europe",
    aliases: ["Czech Republic"],
    cities: ["Prague","Brno","Ostrava","Plzeň","Liberec","Olomouc","České Budějovice","Hradec Králové","Ústí nad Labem","Pardubice"],
    states: ["Prague","Central Bohemian","South Moravian","Moravian-Silesian","Ústí nad Labem","South Bohemian","Olomouc","Hradec Králové","Pardubice","Zlín","Plzeň","Liberec","Karlovy Vary","Vysočina"],
    languages: ["czech","slovak","german"],
    tags: ["czechia","czech","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "AT",
    name: "Austria",
    continent: "europe",
    cities: ["Vienna","Graz","Linz","Salzburg","Innsbruck","Klagenfurt","Villach","Wels","Sankt Pölten","Dornbirn"],
    states: ["Vienna","Lower Austria","Upper Austria","Styria","Tyrol","Carinthia","Salzburg","Vorarlberg","Burgenland"],
    languages: ["german","slovene","croatian","hungarian"],
    tags: ["austria","news","classical","opera","jazz","folk","public","community","university"],
  },
  {
    code: "CH",
    name: "Switzerland",
    continent: "europe",
    cities: ["Zurich","Geneva","Basel","Bern","Lausanne","Winterthur","Lucerne","St. Gallen","Lugano","Biel"],
    states: ["Zurich","Bern","Vaud","Aargau","St. Gallen","Geneva","Lucerne","Ticino","Valais","Basel-Stadt","Basel-Landschaft","Fribourg","Thurgau","Solothurn","Graubünden","Neuchâtel","Schwyz","Zug","Schaffhausen","Jura","Appenzell Ausserrhoden","Appenzell Innerrhoden","Nidwalden","Obwalden","Glarus","Uri"],
    languages: ["german","french","italian","romansh"],
    tags: ["switzerland","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "BE",
    name: "Belgium",
    continent: "europe",
    cities: ["Brussels","Antwerp","Ghent","Charleroi","Liège","Bruges","Namur","Leuven","Mons","Aalst"],
    states: ["Brussels-Capital","Flanders","Wallonia","Antwerp","East Flanders","West Flanders","Flemish Brabant","Limburg","Hainaut","Liège","Namur","Luxembourg","Walloon Brabant"],
    languages: ["dutch","french","german"],
    tags: ["belgium","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "IE",
    name: "Ireland",
    continent: "europe",
    cities: ["Dublin","Cork","Limerick","Galway","Waterford","Drogheda","Dundalk","Sligo","Kilkenny","Wexford"],
    states: ["Dublin","Cork","Galway","Limerick","Waterford","Kerry","Mayo","Donegal","Tipperary","Clare","Wexford","Kilkenny","Meath","Louth","Wicklow","Kildare","Westmeath","Offaly","Laois","Carlow","Longford","Roscommon","Sligo","Leitrim","Cavan","Monaghan"],
    languages: ["english","irish"],
    tags: ["ireland","news","folk","traditional","classical","jazz","public","community","university"],
  },
  {
    code: "DK",
    name: "Denmark",
    continent: "europe",
    cities: ["Copenhagen","Aarhus","Odense","Aalborg","Esbjerg","Randers","Kolding","Horsens","Vejle","Roskilde"],
    states: ["Capital Region","Central Denmark","North Denmark","Region Zealand","Region of Southern Denmark"],
    languages: ["danish","faroese","greenlandic"],
    tags: ["denmark","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "HU",
    name: "Hungary",
    continent: "europe",
    cities: ["Budapest","Debrecen","Szeged","Miskolc","Pécs","Győr","Nyíregyháza","Kecskemét","Székesfehérvár"],
    states: ["Budapest","Pest","Borsod-Abaúj-Zemplén","Hajdú-Bihar","Csongrád-Csanád","Győr-Moson-Sopron","Baranya","Fejér","Bács-Kiskun","Szabolcs-Szatmár-Bereg","Veszprém","Somogy","Tolna","Heves","Nógrád","Komárom-Esztergom","Vas","Zala","Jász-Nagykun-Szolnok","Békés"],
    languages: ["hungarian"],
    tags: ["hungary","news","classical","folk","jazz","public","community","university"],
  },
  {
    code: "BG",
    name: "Bulgaria",
    continent: "europe",
    cities: ["Sofia","Plovdiv","Varna","Burgas","Ruse","Stara Zagora","Pleven","Sliven","Dobrich"],
    states: ["Sofia City","Plovdiv","Varna","Burgas","Ruse","Stara Zagora","Pleven","Blagoevgrad","Pazardzhik","Veliko Tarnovo"],
    languages: ["bulgarian","turkish","romani"],
    tags: ["bulgaria","news","classical","folk","public","community","university"],
  },
  {
    code: "HR",
    name: "Croatia",
    continent: "europe",
    cities: ["Zagreb","Split","Rijeka","Osijek","Zadar","Pula","Slavonski Brod","Dubrovnik","Karlovac"],
    states: ["Zagreb","Split-Dalmatia","Primorje-Gorski Kotar","Osijek-Baranja","Zadar","Istria","Dubrovnik-Neretva","Varaždin","Sisak-Moslavina","Međimurje"],
    languages: ["croatian"],
    tags: ["croatia","news","classical","folk","public","community","university"],
  },
  {
    code: "RS",
    name: "Serbia",
    continent: "europe",
    cities: ["Belgrade","Novi Sad","Niš","Kragujevac","Subotica","Zrenjanin","Pančevo","Čačak","Kraljevo"],
    states: ["Belgrade","Vojvodina","Šumadija","Southern and Eastern Serbia","Western Serbia"],
    languages: ["serbian","hungarian","bosnian","romanian"],
    tags: ["serbia","news","classical","folk","public","community","university"],
  },
  {
    code: "SK",
    name: "Slovakia",
    continent: "europe",
    cities: ["Bratislava","Košice","Prešov","Žilina","Nitra","Banská Bystrica","Trnava","Trenčín"],
    states: ["Bratislava","Trnava","Trenčín","Nitra","Žilina","Banská Bystrica","Prešov","Košice"],
    languages: ["slovak","hungarian"],
    tags: ["slovakia","news","classical","folk","public","community","university"],
  },
  {
    code: "SI",
    name: "Slovenia",
    continent: "europe",
    cities: ["Ljubljana","Maribor","Celje","Kranj","Koper","Velenje","Novo Mesto"],
    states: ["Central Slovenia","Drava","Savinja","Coastal–Karst","Upper Carniola","Southeast Slovenia","Gorizia","Carinthia","Mura","Lower Sava","Central Sava","Littoral–Inner Carniola"],
    languages: ["slovene","italian","hungarian"],
    tags: ["slovenia","news","classical","folk","public","community","university"],
  },
  {
    code: "LT",
    name: "Lithuania",
    continent: "europe",
    cities: ["Vilnius","Kaunas","Klaipėda","Šiauliai","Panevėžys","Alytus","Marijampolė"],
    states: ["Vilnius","Kaunas","Klaipėda","Šiauliai","Panevėžys","Alytus","Marijampolė","Tauragė","Telšiai","Utena"],
    languages: ["lithuanian","russian","polish"],
    tags: ["lithuania","news","classical","folk","public","community","university"],
  },
  {
    code: "LV",
    name: "Latvia",
    continent: "europe",
    cities: ["Riga","Daugavpils","Liepāja","Jelgava","Jūrmala","Ventspils","Rēzekne"],
    states: ["Riga","Kurzeme","Latgale","Vidzeme","Zemgale"],
    languages: ["latvian","russian"],
    tags: ["latvia","news","classical","folk","public","community","university"],
  },
  {
    code: "EE",
    name: "Estonia",
    continent: "europe",
    cities: ["Tallinn","Tartu","Narva","Pärnu","Kohtla-Järve","Viljandi"],
    states: ["Harju","Tartu","Ida-Viru","Pärnu","Lääne-Viru","Viljandi","Rapla","Võru","Saare","Jõgeva","Järva","Valga","Põlva","Lääne","Hiiu"],
    languages: ["estonian","russian"],
    tags: ["estonia","news","classical","folk","public","community","university"],
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    continent: "europe",
    cities: ["Sarajevo","Banja Luka","Tuzla","Zenica","Mostar","Bijeljina","Prijedor"],
    states: ["Federation of Bosnia and Herzegovina","Republika Srpska","Brčko District","Sarajevo","Tuzla","Zenica-Doboj","Herzegovina-Neretva","Central Bosnia"],
    languages: ["bosnian","croatian","serbian"],
    tags: ["bosnia","news","folk","public","community"],
  },
  {
    code: "MK",
    name: "North Macedonia",
    continent: "europe",
    aliases: ["Macedonia","FYROM"],
    cities: ["Skopje","Bitola","Kumanovo","Prilep","Tetovo","Ohrid","Veles"],
    states: ["Skopje","Pelagonia","Polog","Eastern","Southeastern","Southwestern","Northeastern","Vardar"],
    languages: ["macedonian","albanian"],
    tags: ["north macedonia","macedonia","news","folk","public","community"],
  },
  {
    code: "AL",
    name: "Albania",
    continent: "europe",
    cities: ["Tirana","Durrës","Vlorë","Shkodër","Elbasan","Korçë","Fier"],
    states: ["Tirana","Durrës","Vlorë","Shkodër","Elbasan","Fier","Korçë","Berat","Gjirokastër","Kukës","Lezhë","Dibër"],
    languages: ["albanian"],
    tags: ["albania","news","folk","public","community"],
  },
  {
    code: "ME",
    name: "Montenegro",
    continent: "europe",
    cities: ["Podgorica","Nikšić","Herceg Novi","Bar","Budva","Cetinje","Pljevlja"],
    states: ["Podgorica","Nikšić","Bar","Budva","Herceg Novi","Cetinje","Bijelo Polje","Pljevlja"],
    languages: ["montenegrin","serbian","bosnian","albanian"],
    tags: ["montenegro","news","folk","public","community"],
  },
  {
    code: "MD",
    name: "Moldova",
    continent: "europe",
    cities: ["Chișinău","Tiraspol","Bălți","Bender","Rîbnița","Cahul"],
    states: ["Chișinău","Bălți","Gagauzia","Transnistria","Cahul","Orhei","Ungheni"],
    languages: ["romanian","russian","gagauz","ukrainian"],
    tags: ["moldova","news","folk","public","community"],
  },
  {
    code: "BY",
    name: "Belarus",
    continent: "europe",
    cities: ["Minsk","Gomel","Mogilev","Vitebsk","Grodno","Brest","Bobruisk"],
    states: ["Minsk","Gomel","Mogilev","Vitebsk","Grodno","Brest"],
    languages: ["belarusian","russian"],
    tags: ["belarus","news","classical","folk","public","community"],
  },
  {
    code: "IS",
    name: "Iceland",
    continent: "europe",
    cities: ["Reykjavík","Kópavogur","Hafnarfjörður","Akureyri","Reykjanesbær","Selfoss"],
    states: ["Capital Region","Southern Peninsula","Western Region","Westfjords","Northwestern Region","Northeastern Region","Eastern Region","Southern Region"],
    languages: ["icelandic"],
    tags: ["iceland","news","classical","folk","public","community","university"],
  },
  {
    code: "LU",
    name: "Luxembourg",
    continent: "europe",
    cities: ["Luxembourg City","Esch-sur-Alzette","Differdange","Dudelange","Ettelbruck"],
    states: ["Luxembourg","Diekirch","Grevenmacher","Capellen","Esch-sur-Alzette","Remich","Wiltz","Clervaux","Echternach","Mersch","Redange","Vianden"],
    languages: ["luxembourgish","french","german"],
    tags: ["luxembourg","news","classical","public","community"],
  },
  {
    code: "MT",
    name: "Malta",
    continent: "europe",
    cities: ["Valletta","Birkirkara","Sliema","Mosta","Qormi","Żabbar","St. Julian's"],
    states: ["Malta","Gozo","Northern Region","Central Region","Southern Region"],
    languages: ["maltese","english"],
    tags: ["malta","news","public","community"],
  },
  {
    code: "CY",
    name: "Cyprus",
    continent: "europe",
    cities: ["Nicosia","Limassol","Larnaca","Paphos","Famagusta","Kyrenia"],
    states: ["Nicosia","Limassol","Larnaca","Paphos","Famagusta","Kyrenia"],
    languages: ["greek","turkish","english"],
    tags: ["cyprus","news","folk","public","community"],
  },
  {
    code: "RU",
    name: "Russia",
    continent: "europe",
    cities: ["Moscow","Saint Petersburg","Novosibirsk","Yekaterinburg","Kazan","Nizhny Novgorod","Chelyabinsk","Samara","Omsk","Rostov-on-Don","Ufa","Krasnoyarsk","Voronezh","Perm","Volgograd","Krasnodar","Saratov","Tyumen","Tolyatti","Izhevsk"],
    states: ["Moscow","Saint Petersburg","Moscow Oblast","Krasnodar Krai","Sverdlovsk","Rostov","Bashkortostan","Tatarstan","Chelyabinsk","Nizhny Novgorod","Samara","Krasnoyarsk Krai","Novosibirsk","Perm Krai","Voronezh","Volgograd","Saratov","Tyumen","Irkutsk","Khabarovsk Krai","Primorsky Krai"],
    languages: ["russian","tatar","bashkir","chechen","chuvash"],
    tags: ["russia","news","classical","jazz","folk","public","community","university"],
  },
  {
    code: "VA",
    name: "Vatican City",
    continent: "europe",
    aliases: ["Holy See"],
    cities: ["Vatican City"],
    languages: ["italian","latin"],
    tags: ["vatican","catholic","religious","news"],
  },
  {
    code: "MC",
    name: "Monaco",
    continent: "europe",
    cities: ["Monaco","Monte Carlo"],
    languages: ["french","monégasque","italian","english"],
    tags: ["monaco","news","classical","public"],
  },
  {
    code: "AD",
    name: "Andorra",
    continent: "europe",
    cities: ["Andorra la Vella","Escaldes-Engordany","Encamp"],
    languages: ["catalan","spanish","french"],
    tags: ["andorra","news","public"],
  },
  {
    code: "SM",
    name: "San Marino",
    continent: "europe",
    cities: ["San Marino","Serravalle","Borgo Maggiore"],
    languages: ["italian"],
    tags: ["san marino","news","public"],
  },
  {
    code: "LI",
    name: "Liechtenstein",
    continent: "europe",
    cities: ["Vaduz","Schaan","Triesen","Balzers"],
    languages: ["german"],
    tags: ["liechtenstein","news","public"],
  },
  {
    code: "XK",
    name: "Kosovo",
    continent: "europe",
    cities: ["Pristina","Prizren","Peja","Mitrovica","Gjakova","Ferizaj"],
    states: ["Pristina","Prizren","Peja","Mitrovica","Gjakova","Ferizaj","Gjilan"],
    languages: ["albanian","serbian"],
    tags: ["kosovo","news","folk","public","community"],
  },
  {
    code: "FO",
    name: "Faroe Islands",
    continent: "europe",
    cities: ["Tórshavn","Klaksvík","Runavík","Tvøroyri"],
    languages: ["faroese","danish"],
    tags: ["faroe","news","folk","public"],
  },
  {
    code: "IM",
    name: "Isle of Man",
    continent: "europe",
    cities: ["Douglas","Ramsey","Peel","Castletown"],
    languages: ["english","manx"],
    tags: ["isle of man","news","community"],
  },
  {
    code: "JE",
    name: "Jersey",
    continent: "europe",
    cities: ["Saint Helier","Saint Saviour","St Brelade"],
    languages: ["english","french","jèrriais"],
    tags: ["jersey","channel islands","news","community"],
  },
  {
    code: "GG",
    name: "Guernsey",
    continent: "europe",
    cities: ["Saint Peter Port","Saint Sampson","Vale"],
    languages: ["english","french","guernésiais"],
    tags: ["guernsey","channel islands","news","community"],
  },
  {
    code: "GI",
    name: "Gibraltar",
    continent: "europe",
    cities: ["Gibraltar"],
    languages: ["english","spanish"],
    tags: ["gibraltar","news","community"],
  },
  {
    code: "AX",
    name: "Åland",
    continent: "europe",
    aliases: ["Aland"],
    cities: ["Mariehamn"],
    languages: ["swedish","finnish"],
    tags: ["aland","finland","news","public"],
  },
  {
    code: "SJ",
    name: "Svalbard",
    continent: "europe",
    aliases: ["Spitsbergen"],
    cities: ["Longyearbyen","Barentsburg"],
    languages: ["norwegian","russian"],
    tags: ["svalbard","arctic","news","community"],
    notes: ["Remote Arctic territory; prefer lawful public/community feeds only"],
  },
];
