/**
 * Controlled North America radio expansion queue (Canada, US, Mexico, Central America, Caribbean).
 */
import type { WorldwideRadioCountry } from "@/lib/radioWorldwideExpansion/types";

export const NORTH_AMERICA_RADIO_QUEUE: WorldwideRadioCountry[] = [
  {
    code: "CA",
    name: "Canada",
    continent: "north_america",
    cities: ["Toronto","Montreal","Vancouver","Calgary","Edmonton","Ottawa","Winnipeg","Quebec City","Hamilton","Kitchener","London","Victoria","Halifax","Saskatoon","Regina","St. John's","Whitehorse","Yellowknife","Iqaluit","Charlottetown","Fredericton","Moncton"],
    states: ["Ontario","Quebec","British Columbia","Alberta","Manitoba","Saskatchewan","Nova Scotia","New Brunswick","Newfoundland and Labrador","Prince Edward Island","Northwest Territories","Yukon","Nunavut"],
    languages: ["english","french","inuktitut","cree","ojibwe"],
    tags: ["canada","news","classical","jazz","folk","public","community","university","cbc","indigenous"],
  },
  {
    code: "US",
    name: "United States",
    continent: "north_america",
    aliases: ["USA","America","United States of America"],
    cities: ["Birmingham","Montgomery","Mobile","Huntsville","Tuscaloosa","Anchorage","Fairbanks","Juneau","Sitka","Wasilla","Phoenix","Tucson","Mesa","Chandler","Scottsdale","Little Rock","Fort Smith","Fayetteville","Springdale","Jonesboro","Los Angeles","San Francisco","San Diego","Sacramento","San Jose","Oakland","Fresno","Denver","Colorado Springs","Aurora","Fort Collins","Boulder","Bridgeport","New Haven","Hartford","Stamford","Waterbury","Wilmington","Dover","Newark","Middletown","Miami","Orlando","Tampa","Jacksonville","Tallahassee","Fort Lauderdale","Atlanta","Augusta","Columbus","Savannah","Macon","Honolulu","Hilo","Kailua","Kahului","Pearl City","Boise","Meridian","Nampa","Idaho Falls","Pocatello","Chicago","Naperville","Rockford","Springfield","Peoria","Indianapolis","Fort Wayne","Evansville","South Bend","Bloomington","Des Moines","Cedar Rapids","Davenport","Sioux City","Iowa City","Wichita","Overland Park","Kansas City","Topeka","Lawrence","Louisville","Lexington","Bowling Green","Owensboro","Covington","New Orleans","Baton Rouge","Shreveport","Lafayette","Lake Charles","Portland","Lewiston","Bangor","South Portland","Auburn","Baltimore","Frederick","Rockville","Gaithersburg","Annapolis","Boston","Worcester","Cambridge","Lowell","Detroit","Grand Rapids","Warren","Ann Arbor","Lansing","Minneapolis","Saint Paul","Rochester","Duluth","Jackson","Gulfport","Southaven","Hattiesburg","Biloxi"],
    states: ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming","District of Columbia","Puerto Rico","Guam","U.S. Virgin Islands","American Samoa","Northern Mariana Islands"],
    languages: ["english","spanish","chinese","tagalog","vietnamese","french","korean","german","arabic","russian","navajo","hawaiian"],
    tags: ["usa","america","news","classical","jazz","country","folk","public","community","university","npr","college","gospel","talk","sports","rock","hip hop","rnb","electronic"],
  },
  {
    code: "MX",
    name: "Mexico",
    continent: "north_america",
    cities: ["Mexico City","Guadalajara","Monterrey","Puebla","Tijuana","León","Juárez","Zapopan","Mérida","Cancún","Querétaro","San Luis Potosí","Aguascalientes","Hermosillo","Saltillo","Morelia","Culiacán","Chihuahua","Toluca","Acapulco"],
    states: ["Aguascalientes","Baja California","Baja California Sur","Campeche","Chiapas","Chihuahua","Coahuila","Colima","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","Mexico City","México","Michoacán","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas"],
    languages: ["spanish","nahuatl","maya","mixtec","zapotec"],
    tags: ["mexico","news","ranchera","mariachi","salsa","reggaeton","public","community","university","folk","classical"],
  },
  {
    code: "GT",
    name: "Guatemala",
    continent: "north_america",
    cities: ["Guatemala City","Quetzaltenango","Escuintla","Antigua","Cobán"],
    states: ["Guatemala","Quetzaltenango","Escuintla","Huehuetenango","Alta Verapaz","Petén","San Marcos"],
    languages: ["spanish","k'iche'","q'eqchi'","kakchiquel"],
    tags: ["guatemala","news","marimba","community","public"],
  },
  {
    code: "BZ",
    name: "Belize",
    continent: "north_america",
    cities: ["Belize City","Belmopan","San Ignacio","Orange Walk","Dangriga"],
    states: ["Belize","Cayo","Corozal","Orange Walk","Stann Creek","Toledo"],
    languages: ["english","spanish","kriol","garifuna","maya"],
    tags: ["belize","news","caribbean","community"],
  },
  {
    code: "HN",
    name: "Honduras",
    continent: "north_america",
    cities: ["Tegucigalpa","San Pedro Sula","La Ceiba","Choloma","Comayagua"],
    states: ["Francisco Morazán","Cortés","Atlántida","Comayagua","Yoro","Choluteca"],
    languages: ["spanish"],
    tags: ["honduras","news","community","public"],
  },
  {
    code: "SV",
    name: "El Salvador",
    continent: "north_america",
    cities: ["San Salvador","Santa Ana","San Miguel","Soyapango","Santa Tecla"],
    states: ["San Salvador","Santa Ana","San Miguel","La Libertad","Sonsonate"],
    languages: ["spanish"],
    tags: ["el salvador","news","community","public"],
  },
  {
    code: "NI",
    name: "Nicaragua",
    continent: "north_america",
    cities: ["Managua","León","Masaya","Matagalpa","Chinandega","Granada"],
    states: ["Managua","León","Masaya","Matagalpa","Chinandega","Granada","Estelí"],
    languages: ["spanish","miskito"],
    tags: ["nicaragua","news","community","public"],
  },
  {
    code: "CR",
    name: "Costa Rica",
    continent: "north_america",
    cities: ["San José","Alajuela","Cartago","Heredia","Limón","Puntarenas"],
    states: ["San José","Alajuela","Cartago","Heredia","Guanacaste","Puntarenas","Limón"],
    languages: ["spanish","english"],
    tags: ["costa rica","news","community","public","university"],
  },
  {
    code: "PA",
    name: "Panama",
    continent: "north_america",
    cities: ["Panama City","Colón","David","La Chorrera","Santiago"],
    states: ["Panamá","Colón","Chiriquí","Coclé","Veraguas","Herrera","Los Santos","Bocas del Toro"],
    languages: ["spanish","english"],
    tags: ["panama","news","salsa","community","public"],
  },
  {
    code: "CU",
    name: "Cuba",
    continent: "north_america",
    cities: ["Havana","Santiago de Cuba","Camagüey","Holguín","Santa Clara","Guantánamo","Matanzas"],
    states: ["La Habana","Santiago de Cuba","Camagüey","Holguín","Villa Clara","Guantánamo","Matanzas","Pinar del Río"],
    languages: ["spanish"],
    tags: ["cuba","salsa","son","news","public","community"],
  },
  {
    code: "JM",
    name: "Jamaica",
    continent: "north_america",
    cities: ["Kingston","Montego Bay","Spanish Town","Portmore","Mandeville","Ocho Rios"],
    states: ["Kingston","Saint Andrew","Saint James","Saint Catherine","Clarendon","Manchester","Saint Ann"],
    languages: ["english","jamaican patois"],
    tags: ["jamaica","reggae","dancehall","news","community","gospel"],
  },
  {
    code: "HT",
    name: "Haiti",
    continent: "north_america",
    cities: ["Port-au-Prince","Cap-Haïtien","Gonaïves","Les Cayes","Jacmel"],
    states: ["Ouest","Nord","Artibonite","Sud","Sud-Est","Centre","Nord-Ouest","Nord-Est","Grande-Anse","Nippes"],
    languages: ["haitian creole","french"],
    tags: ["haiti","compas","news","community","gospel"],
  },
  {
    code: "DO",
    name: "Dominican Republic",
    continent: "north_america",
    cities: ["Santo Domingo","Santiago","La Romana","San Pedro de Macorís","Puerto Plata","Punta Cana"],
    states: ["Distrito Nacional","Santiago","Santo Domingo","La Vega","Puerto Plata","San Cristóbal","La Romana"],
    languages: ["spanish"],
    tags: ["dominican","bachata","merengue","news","community"],
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    continent: "north_america",
    cities: ["Port of Spain","San Fernando","Chaguanas","Arima","Scarborough"],
    states: ["Port of Spain","San Fernando","Chaguanas","Tobago","Tunapuna-Piarco"],
    languages: ["english"],
    tags: ["trinidad","tobago","soca","calypso","news","community"],
  },
  {
    code: "BB",
    name: "Barbados",
    continent: "north_america",
    cities: ["Bridgetown","Speightstown","Oistins","Holetown"],
    languages: ["english"],
    tags: ["barbados","soca","calypso","news","community"],
  },
  {
    code: "BS",
    name: "Bahamas",
    continent: "north_america",
    cities: ["Nassau","Freeport","West End","Marsh Harbour"],
    languages: ["english"],
    tags: ["bahamas","junkanoo","news","community"],
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    continent: "north_america",
    cities: ["St. John's","All Saints","Liberta"],
    languages: ["english"],
    tags: ["antigua","caribbean","news","community"],
  },
  {
    code: "DM",
    name: "Dominica",
    continent: "north_america",
    cities: ["Roseau","Portsmouth","Marigot"],
    languages: ["english","french creole"],
    tags: ["dominica","caribbean","news","community"],
  },
  {
    code: "GD",
    name: "Grenada",
    continent: "north_america",
    cities: ["St. George's","Gouyave","Grenville"],
    languages: ["english"],
    tags: ["grenada","caribbean","soca","news","community"],
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    continent: "north_america",
    cities: ["Basseterre","Charlestown"],
    languages: ["english"],
    tags: ["saint kitts","nevis","caribbean","news"],
  },
  {
    code: "LC",
    name: "Saint Lucia",
    continent: "north_america",
    cities: ["Castries","Vieux Fort","Soufrière"],
    languages: ["english","french creole"],
    tags: ["saint lucia","caribbean","news","community"],
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    continent: "north_america",
    cities: ["Kingstown","Georgetown","Barrouallie"],
    languages: ["english"],
    tags: ["saint vincent","caribbean","news"],
  },
  {
    code: "KY",
    name: "Cayman Islands",
    continent: "north_america",
    cities: ["George Town","West Bay","Bodden Town"],
    languages: ["english"],
    tags: ["cayman","caribbean","news","community"],
  },
  {
    code: "BM",
    name: "Bermuda",
    continent: "north_america",
    cities: ["Hamilton","Saint George"],
    languages: ["english"],
    tags: ["bermuda","news","community"],
  },
  {
    code: "AW",
    name: "Aruba",
    continent: "north_america",
    cities: ["Oranjestad","San Nicolaas","Noord"],
    languages: ["dutch","papiamento","english","spanish"],
    tags: ["aruba","caribbean","news","community"],
  },
  {
    code: "CW",
    name: "Curaçao",
    continent: "north_america",
    cities: ["Willemstad"],
    languages: ["dutch","papiamento","english","spanish"],
    tags: ["curacao","caribbean","news","community"],
  },
  {
    code: "SX",
    name: "Sint Maarten",
    continent: "north_america",
    cities: ["Philipsburg"],
    languages: ["dutch","english"],
    tags: ["sint maarten","caribbean","news"],
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    continent: "north_america",
    cities: ["Cockburn Town","Providenciales"],
    languages: ["english"],
    tags: ["turks and caicos","caribbean","news"],
  },
  {
    code: "VG",
    name: "British Virgin Islands",
    continent: "north_america",
    cities: ["Road Town"],
    languages: ["english"],
    tags: ["british virgin islands","caribbean","news"],
  },
  {
    code: "AI",
    name: "Anguilla",
    continent: "north_america",
    cities: ["The Valley"],
    languages: ["english"],
    tags: ["anguilla","caribbean","news"],
  },
  {
    code: "MQ",
    name: "Martinique",
    continent: "north_america",
    cities: ["Fort-de-France","Le Lamentin","Schoelcher"],
    languages: ["french","antillean creole"],
    tags: ["martinique","caribbean","zouk","news","public"],
  },
  {
    code: "GP",
    name: "Guadeloupe",
    continent: "north_america",
    cities: ["Pointe-à-Pitre","Basse-Terre","Les Abymes"],
    languages: ["french","antillean creole"],
    tags: ["guadeloupe","caribbean","zouk","news","public"],
  },
  {
    code: "MF",
    name: "Saint Martin",
    continent: "north_america",
    cities: ["Marigot"],
    languages: ["french"],
    tags: ["saint martin","caribbean","news"],
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    continent: "north_america",
    cities: ["Gustavia"],
    languages: ["french"],
    tags: ["saint barthelemy","caribbean","news"],
  },
  {
    code: "PR",
    name: "Puerto Rico",
    continent: "north_america",
    cities: ["San Juan","Bayamón","Carolina","Ponce","Caguas","Mayagüez"],
    states: ["San Juan","Bayamón","Carolina","Ponce","Caguas","Mayagüez","Arecibo"],
    languages: ["spanish","english"],
    tags: ["puerto rico","salsa","reggaeton","news","community","university"],
  },
  {
    code: "VI",
    name: "U.S. Virgin Islands",
    continent: "north_america",
    cities: ["Charlotte Amalie","Christiansted","Cruz Bay"],
    languages: ["english"],
    tags: ["us virgin islands","caribbean","news","community"],
  },
  {
    code: "GL",
    name: "Greenland",
    continent: "north_america",
    cities: ["Nuuk","Sisimiut","Ilulissat","Qaqortoq"],
    states: ["Avannaata","Kujalleq","Qeqertalik","Qeqqata","Sermersooq"],
    languages: ["greenlandic","danish"],
    tags: ["greenland","arctic","news","public","community"],
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    continent: "north_america",
    cities: ["Saint-Pierre","Miquelon"],
    languages: ["french"],
    tags: ["saint pierre","news","community"],
  },
  {
    code: "BQ",
    name: "Caribbean Netherlands",
    continent: "north_america",
    aliases: ["Bonaire","Saba","Sint Eustatius"],
    cities: ["Kralendijk","Oranjestad","The Bottom"],
    languages: ["dutch","papiamento","english"],
    tags: ["bonaire","caribbean","news"],
  },
];
