/**
 * Controlled Oceania / Pacific radio expansion queue.
 */
import type { WorldwideRadioCountry } from "@/lib/radioWorldwideExpansion/types";

export const OCEANIA_RADIO_QUEUE: WorldwideRadioCountry[] = [
  {
    code: "AU",
    name: "Australia",
    continent: "oceania",
    cities: ["Sydney","Melbourne","Brisbane","Perth","Adelaide","Canberra","Hobart","Darwin","Gold Coast","Newcastle","Wollongong","Geelong","Townsville","Cairns","Toowoomba","Ballarat","Bendigo","Launceston","Mackay","Rockhampton","Alice Springs","Broome"],
    states: ["New South Wales","Victoria","Queensland","Western Australia","South Australia","Tasmania","Australian Capital Territory","Northern Territory"],
    languages: ["english","mandarin","arabic","vietnamese","italian","greek","aboriginal languages"],
    tags: ["australia","news","classical","jazz","folk","public","community","university","abc","indigenous","rock","country"],
  },
  {
    code: "NZ",
    name: "New Zealand",
    continent: "oceania",
    cities: ["Auckland","Wellington","Christchurch","Hamilton","Tauranga","Napier","Dunedin","Palmerston North","Nelson","Rotorua","New Plymouth","Invercargill","Whangarei","Gisborne"],
    states: ["Auckland","Wellington","Canterbury","Waikato","Bay of Plenty","Otago","Manawatū-Whanganui","Hawke's Bay","Northland","Taranaki","Southland","Nelson","Tasman","Marlborough","Gisborne","West Coast"],
    languages: ["english","māori"],
    tags: ["new zealand","news","classical","jazz","folk","public","community","university","maori","indigenous"],
  },
  {
    code: "PG",
    name: "Papua New Guinea",
    continent: "oceania",
    cities: ["Port Moresby","Lae","Mount Hagen","Madang","Goroka","Kokopo","Kimbe"],
    states: ["National Capital District","Morobe","Western Highlands","Madang","Eastern Highlands","East New Britain","West New Britain","Enga","Southern Highlands","Chimbu"],
    languages: ["english","tok pisin","hiri motu"],
    tags: ["papua new guinea","news","community","public","gospel"],
  },
  {
    code: "FJ",
    name: "Fiji",
    continent: "oceania",
    cities: ["Suva","Nadi","Lautoka","Labasa","Ba"],
    states: ["Central","Western","Northern","Eastern"],
    languages: ["english","fijian","hindi"],
    tags: ["fiji","news","community","public","gospel"],
  },
  {
    code: "SB",
    name: "Solomon Islands",
    continent: "oceania",
    cities: ["Honiara","Gizo","Auki","Kirakira"],
    states: ["Guadalcanal","Malaita","Western","Makira-Ulawa","Central","Isabel","Choiseul"],
    languages: ["english","pijin"],
    tags: ["solomon islands","news","community","gospel"],
  },
  {
    code: "VU",
    name: "Vanuatu",
    continent: "oceania",
    cities: ["Port Vila","Luganville","Isangel"],
    states: ["Shefa","Sanma","Tafea","Malampa","Penama","Torba"],
    languages: ["bislama","english","french"],
    tags: ["vanuatu","news","community","public"],
  },
  {
    code: "NC",
    name: "New Caledonia",
    continent: "oceania",
    cities: ["Nouméa","Mont-Dore","Dumbéa","Païta"],
    states: ["South Province","North Province","Loyalty Islands"],
    languages: ["french"],
    tags: ["new caledonia","news","public","community"],
  },
  {
    code: "FM",
    name: "Micronesia",
    continent: "oceania",
    aliases: ["Federated States of Micronesia"],
    cities: ["Palikir","Weno","Kolonia","Colonia"],
    states: ["Pohnpei","Chuuk","Yap","Kosrae"],
    languages: ["english","chuukese","pohnpeian","yapese","kosraean"],
    tags: ["micronesia","news","community","gospel"],
  },
  {
    code: "MH",
    name: "Marshall Islands",
    continent: "oceania",
    cities: ["Majuro","Ebeye"],
    states: ["Majuro","Kwajalein","Jaluit","Wotje"],
    languages: ["marshallese","english"],
    tags: ["marshall islands","news","community","gospel"],
  },
  {
    code: "PW",
    name: "Palau",
    continent: "oceania",
    cities: ["Ngerulmud","Koror","Melekeok"],
    states: ["Koror","Airai","Melekeok","Aimeliik"],
    languages: ["palauan","english"],
    tags: ["palau","news","community"],
  },
  {
    code: "GU",
    name: "Guam",
    continent: "oceania",
    cities: ["Hagåtña","Dededo","Tamuning","Yigo","Mangilao"],
    languages: ["english","chamorro"],
    tags: ["guam","news","community","university","pacific"],
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    continent: "oceania",
    cities: ["Saipan","Tinian","Rota"],
    languages: ["english","chamorro","carolinian"],
    tags: ["northern mariana","saipan","news","community","pacific"],
  },
  {
    code: "KI",
    name: "Kiribati",
    continent: "oceania",
    cities: ["South Tarawa","Betio","Christmas Island"],
    states: ["Gilbert Islands","Phoenix Islands","Line Islands"],
    languages: ["gilbertese","english"],
    tags: ["kiribati","news","community","gospel"],
  },
  {
    code: "NR",
    name: "Nauru",
    continent: "oceania",
    cities: ["Yaren","Denigomodu","Aiwo"],
    languages: ["nauruan","english"],
    tags: ["nauru","news","community"],
  },
  {
    code: "WS",
    name: "Samoa",
    continent: "oceania",
    cities: ["Apia","Vaitele","Faleula"],
    states: ["Tuamasaga","A'ana","Atua","Savai'i"],
    languages: ["samoan","english"],
    tags: ["samoa","news","community","gospel","pacific"],
  },
  {
    code: "TO",
    name: "Tonga",
    continent: "oceania",
    cities: ["Nuku'alofa","Neiafu","Haveluloto"],
    states: ["Tongatapu","Vava'u","Ha'apai","'Eua"],
    languages: ["tongan","english"],
    tags: ["tonga","news","community","gospel","pacific"],
  },
  {
    code: "TV",
    name: "Tuvalu",
    continent: "oceania",
    cities: ["Funafuti","Vaiaku"],
    languages: ["tuvaluan","english"],
    tags: ["tuvalu","news","community"],
  },
  {
    code: "CK",
    name: "Cook Islands",
    continent: "oceania",
    cities: ["Avarua","Arutanga"],
    states: ["Rarotonga","Aitutaki","Mangaia","Atiu"],
    languages: ["english","cook islands māori"],
    tags: ["cook islands","news","community","pacific"],
  },
  {
    code: "PF",
    name: "French Polynesia",
    continent: "oceania",
    cities: ["Papeete","Faaa","Punaauia","Pirae","Mahina"],
    states: ["Windward Islands","Leeward Islands","Marquesas","Austral Islands","Tuamotu-Gambier"],
    languages: ["french","tahitian"],
    tags: ["french polynesia","tahiti","news","public","community","pacific"],
  },
  {
    code: "NU",
    name: "Niue",
    continent: "oceania",
    cities: ["Alofi"],
    languages: ["niuean","english"],
    tags: ["niue","news","community","pacific"],
  },
  {
    code: "TK",
    name: "Tokelau",
    continent: "oceania",
    cities: ["Atafu","Nukunonu","Fakaofo"],
    languages: ["tokelauan","english"],
    tags: ["tokelau","news","community","pacific"],
  },
  {
    code: "AS",
    name: "American Samoa",
    continent: "oceania",
    cities: ["Pago Pago","Tafuna","Leone"],
    languages: ["english","samoan"],
    tags: ["american samoa","news","community","pacific","gospel"],
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    continent: "oceania",
    cities: ["Mata-Utu","Leava"],
    states: ["Wallis","Futuna","Alofi"],
    languages: ["french","wallisian","futunan"],
    tags: ["wallis and futuna","news","community","pacific"],
  },
  {
    code: "PN",
    name: "Pitcairn Islands",
    continent: "oceania",
    cities: ["Adamstown"],
    languages: ["english","pitkern"],
    tags: ["pitcairn","news","community","pacific"],
    notes: ["Extremely small population; prefer lawful public/community feeds only"],
  },
  {
    code: "NF",
    name: "Norfolk Island",
    continent: "oceania",
    cities: ["Kingston","Burnt Pine"],
    languages: ["english","norfuk"],
    tags: ["norfolk island","news","community","pacific"],
  },
];
