/**
 * Controlled South America radio expansion queue.
 */
import type { WorldwideRadioCountry } from "@/lib/radioWorldwideExpansion/types";

export const SOUTH_AMERICA_RADIO_QUEUE: WorldwideRadioCountry[] = [
  {
    code: "AR",
    name: "Argentina",
    continent: "south_america",
    cities: ["Buenos Aires","Córdoba","Rosario","Mendoza","La Plata","San Miguel de Tucumán","Mar del Plata","Salta","Santa Fe","San Juan","Resistencia","Neuquén","Santiago del Estero","Corrientes","Bahía Blanca"],
    states: ["Buenos Aires","Córdoba","Santa Fe","Mendoza","Tucumán","Entre Ríos","Salta","Misiones","Chaco","Corrientes","Santiago del Estero","San Juan","Jujuy","Río Negro","Neuquén","Formosa","Chubut","San Luis","Catamarca","La Rioja","La Pampa","Santa Cruz","Tierra del Fuego","City of Buenos Aires"],
    languages: ["spanish","italian","quechua","guaraní","welsh"],
    tags: ["argentina","tango","news","folk","classical","public","community","university","rock"],
  },
  {
    code: "BO",
    name: "Bolivia",
    continent: "south_america",
    cities: ["La Paz","Santa Cruz de la Sierra","Cochabamba","Sucre","Oruro","Potosí","Tarija","El Alto"],
    states: ["La Paz","Santa Cruz","Cochabamba","Potosí","Chuquisaca","Oruro","Tarija","Beni","Pando"],
    languages: ["spanish","quechua","aymara","guaraní"],
    tags: ["bolivia","news","folk","andean","public","community"],
  },
  {
    code: "BR",
    name: "Brazil",
    continent: "south_america",
    cities: ["São Paulo","Rio de Janeiro","Brasília","Salvador","Fortaleza","Belo Horizonte","Manaus","Curitiba","Recife","Porto Alegre","Belém","Goiânia","Guarulhos","Campinas","São Luís","Maceió","Natal","Teresina","Campo Grande","João Pessoa","Florianópolis","Vitória","Cuiabá"],
    states: ["São Paulo","Rio de Janeiro","Minas Gerais","Bahia","Paraná","Rio Grande do Sul","Pernambuco","Ceará","Pará","Santa Catarina","Goiás","Maranhão","Amazonas","Espírito Santo","Paraíba","Mato Grosso","Rio Grande do Norte","Alagoas","Piauí","Distrito Federal","Mato Grosso do Sul","Sergipe","Rondônia","Tocantins","Acre","Amapá","Roraima"],
    languages: ["portuguese"],
    tags: ["brazil","samba","bossa nova","mpb","forró","sertanejo","funk","news","public","community","university","gospel","classical","jazz"],
  },
  {
    code: "CL",
    name: "Chile",
    continent: "south_america",
    cities: ["Santiago","Valparaíso","Concepción","La Serena","Antofagasta","Temuco","Rancagua","Talca","Arica","Iquique","Puerto Montt","Punta Arenas"],
    states: ["Santiago Metropolitan","Valparaíso","Biobío","Araucanía","Maule","O'Higgins","Los Lagos","Coquimbo","Antofagasta","Tarapacá","Arica y Parinacota","Atacama","Ñuble","Los Ríos","Aysén","Magallanes"],
    languages: ["spanish","mapudungun","rapa nui"],
    tags: ["chile","news","folk","cueca","public","community","university","rock"],
  },
  {
    code: "CO",
    name: "Colombia",
    continent: "south_america",
    cities: ["Bogotá","Medellín","Cali","Barranquilla","Cartagena","Cúcuta","Bucaramanga","Pereira","Santa Marta","Ibagué","Manizales","Pasto"],
    states: ["Bogotá","Antioquia","Valle del Cauca","Atlántico","Cundinamarca","Santander","Bolívar","Nariño","Córdoba","Tolima","Cauca","Norte de Santander","Huila","Magdalena","Risaralda","Caldas","Meta","Boyacá","Cesar","Quindío"],
    languages: ["spanish"],
    tags: ["colombia","cumbia","vallenato","salsa","news","public","community","university","reggaeton"],
  },
  {
    code: "EC",
    name: "Ecuador",
    continent: "south_america",
    cities: ["Quito","Guayaquil","Cuenca","Santo Domingo","Machala","Manta","Portoviejo","Ambato","Riobamba"],
    states: ["Pichincha","Guayas","Azuay","Manabí","El Oro","Tungurahua","Los Ríos","Loja","Imbabura","Chimborazo","Esmeraldas","Cotopaxi","Galápagos"],
    languages: ["spanish","quechua","shuar"],
    tags: ["ecuador","news","folk","andean","public","community"],
  },
  {
    code: "FK",
    name: "Falkland Islands",
    continent: "south_america",
    aliases: ["Islas Malvinas"],
    cities: ["Stanley"],
    languages: ["english"],
    tags: ["falklands","news","community"],
    notes: ["British Overseas Territory; prefer lawful public/community feeds"],
  },
  {
    code: "GF",
    name: "French Guiana",
    continent: "south_america",
    cities: ["Cayenne","Saint-Laurent-du-Maroni","Kourou","Matoury"],
    languages: ["french","creole"],
    tags: ["french guiana","news","public","community"],
  },
  {
    code: "GY",
    name: "Guyana",
    continent: "south_america",
    cities: ["Georgetown","Linden","New Amsterdam","Anna Regina"],
    states: ["Demerara-Mahaica","East Berbice-Corentyne","Essequibo Islands-West Demerara","Upper Demerara-Berbice","Pomeroon-Supenaam"],
    languages: ["english"],
    tags: ["guyana","news","caribbean","community","gospel"],
  },
  {
    code: "PY",
    name: "Paraguay",
    continent: "south_america",
    cities: ["Asunción","Ciudad del Este","San Lorenzo","Luque","Capiatá","Encarnación"],
    states: ["Central","Alto Paraná","Itapúa","Caaguazú","San Pedro","Cordillera","Paraguarí"],
    languages: ["spanish","guaraní"],
    tags: ["paraguay","news","folk","public","community"],
  },
  {
    code: "PE",
    name: "Peru",
    continent: "south_america",
    cities: ["Lima","Arequipa","Trujillo","Chiclayo","Piura","Iquitos","Cusco","Huancayo","Tacna","Ica","Pucallpa"],
    states: ["Lima","Arequipa","La Libertad","Piura","Lambayeque","Cusco","Junín","Puno","Ancash","Cajamarca","Loreto","Ica","Tacna","Ayacucho","Huánuco","Callao"],
    languages: ["spanish","quechua","aymara"],
    tags: ["peru","news","andean","folk","huayno","public","community","university"],
  },
  {
    code: "SR",
    name: "Suriname",
    continent: "south_america",
    cities: ["Paramaribo","Lelydorp","Nieuw Nickerie","Moengo"],
    states: ["Paramaribo","Wanica","Nickerie","Commewijne","Sipaliwini","Brokopondo"],
    languages: ["dutch","sranan tongo","hindustani","javanese"],
    tags: ["suriname","news","caribbean","community","public"],
  },
  {
    code: "UY",
    name: "Uruguay",
    continent: "south_america",
    cities: ["Montevideo","Salto","Ciudad de la Costa","Paysandú","Las Piedras","Rivera","Maldonado","Punta del Este"],
    states: ["Montevideo","Canelones","Maldonado","Salto","Paysandú","Rivera","Tacuarembó","Colonia","San José"],
    languages: ["spanish"],
    tags: ["uruguay","news","candombe","tango","folk","public","community","university"],
  },
  {
    code: "VE",
    name: "Venezuela",
    continent: "south_america",
    cities: ["Caracas","Maracaibo","Valencia","Barquisimeto","Maracay","Ciudad Guayana","Barcelona","Maturín","San Cristóbal","Ciudad Bolívar"],
    states: ["Capital District","Zulia","Carabobo","Lara","Aragua","Bolívar","Anzoátegui","Miranda","Táchira","Sucre","Falcón","Monagas","Portuguesa","Mérida"],
    languages: ["spanish"],
    tags: ["venezuela","news","salsa","joropo","folk","public","community","university"],
  },
];
