export type AcquisitionJobType = "DISCOVER_SOURCE" | "FETCH_METADATA" | "EVALUATE_RIGHTS" | "DOWNLOAD_ASSET" | "VALIDATE_AUDIO" | "FINGERPRINT" | "DEDUPLICATE" | "CLASSIFY_TAXONOMY" | "PREPARE_INGESTION" | "EXECUTE_APPROVED_INGESTION";
export type AcquisitionJobStatus = "PENDING" | "RUNNING" | "RETRY_WAIT" | "SUCCEEDED" | "FAILED" | "CANCELLED";

