import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { TvRecoveryQueueItem, TvRecoveryDecision } from "@/lib/tvProviders/recovery/types";
const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");const OUTPUT=join(ROOT,"data","pluto-phase2c");
function owner(name:string){if(/^CNN/i.test(name))return["CNN / Warner Bros. Discovery","US","en"];if(/^ABC News/i.test(name))return["ABC News / The Walt Disney Company","US","en"];if(/^BBC/i.test(name))return["BBC","GB","en"];if(/^Bloomberg/i.test(name))return["Bloomberg L.P.","US","en"];if(/^CBC/i.test(name))return["CBC/Radio-Canada","CA","en"];if(/^CBS/i.test(name))return["CBS News / Paramount","US","en"];if(/^Estrella/i.test(name))return["Estrella Media","US","es"];if(/^Euronews Español/i.test(name))return["Euronews","ES","es"];if(/^Euronews Italian/i.test(name))return["Euronews","IT","it"];if(/^Euronews/i.test(name))return["Euronews","EU","en"];if(/^FOX/i.test(name))return["Fox Corporation","US","en"];if(/^Global News/i.test(name))return["Corus Entertainment / Global News","CA","en"];return[null,null,null];}
function family(host:string){if(/cbsnews\.com$|foxweather\.com$|bloomberg\.com$|cdn-euronews\.akamaized\.net$|vs-hls-push-ww-live\.akamaized\.net$/i.test(host))return"DIRECT_OFFICIAL";if(/cbsivideo\.com$|dai\.google\.com$/i.test(host))return"PUBLIC_SESSION";if(/amagi\.tv$|amagi-streams\.akamaized\.net$/i.test(host))return"LEGITIMATE_FAST";return"UNVERIFIED_AGGREGATOR";}
async function main(){const queue=JSON.parse(await readFile(join(OUTPUT,"tier-a-50-recovery-queue.json"),"utf8")) as TvRecoveryQueueItem[];const table=queue.map(item=>{const [broadcaster,country,language]=owner(item.identity.canonicalName);const candidates=item.candidates.map(candidate=>{const host=new URL(candidate.sourceUrl).hostname;const sourceFamily=family(host);return{...candidate,sourceFamily,confidence:sourceFamily==="DIRECT_OFFICIAL"?"HIGH":sourceFamily==="PUBLIC_SESSION"||sourceFamily==="LEGITIMATE_FAST"?"HIGH":"LOW"};});let decision:TvRecoveryDecision="NO_SOURCE_FOUND";if(/^CNN/i.test(item.identity.canonicalName))decision="ACCOUNT_REQUIRED";else if(candidates.some(c=>c.sourceFamily==="PUBLIC_SESSION"))decision="PUBLIC_SESSION_CANDIDATE";else if(candidates.some(c=>["DIRECT_OFFICIAL","LEGITIMATE_FAST"].includes(c.sourceFamily)))decision="DIRECT_CANDIDATE";else if(candidates.length)decision="IDENTITY_UNCERTAIN";return{...item,broadcaster,country,stagedLanguage:language,decision,candidates,evidence:[...item.evidence,`Broadcaster-family research: ${broadcaster??"unresolved"}.`,decision==="ACCOUNT_REQUIRED"?"Official CNN live distribution requires subscription or qualifying TV-provider access.":"Candidate remains staging-only until actual-content and identity validation pass."]};});const decisions=table.reduce<Record<string,number>>((a,x)=>(a[x.decision]=(a[x.decision]??0)+1,a),{});const families=table.flatMap(x=>x.candidates).reduce<Record<string,number>>((a,x)=>(a[x.sourceFamily]=(a[x.sourceFamily]??0)+1,a),{});const report={generatedAt:new Date().toISOString(),selected:table.length,broadcasterOwnershipEstablished:table.filter(x=>x.broadcaster).length,languagesIdentified:table.filter(x=>x.stagedLanguage).length,regionsIdentified:table.filter(x=>x.identity.region.length).length,decisions,families};await writeFile(join(OUTPUT,"tier-a-50-discovery-table.json"),JSON.stringify(table,null,2));await writeFile(join(OUTPUT,"research-summary.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
