import {spawn} from "node:child_process";import {readFileSync,writeFileSync} from "node:fs";import {resolve} from "node:path";import {loadAdminEnv} from "../lib/radioExpansion25k/env";import {getSupabaseAdmin} from "../lib/supabaseAdmin";
const root=resolve(import.meta.dirname,".."),out=resolve(root,"data/tv-recovery");
const plans=[
 {id:"62a0b2aff4cf470007e47e29",record:"cf9fc0b8-76b4-4f45-9b1d-24d2cbf98868"},
 {id:"657881c46e4f6a00087414c2",record:"2677d15a-8bf9-4989-9bae-410311fae926"},
 {id:"5f515ebac01c0f00080e8439",record:"154914d7-6a45-4b95-b482-0cd01d051fec"},
 {id:"66df8aa7abec540008ca8cb6",record:"57dbad06-6944-46da-bd60-9286ee3d1695"},
 {id:"64e35aff6b1fdb0008ea8441",record:"b1f3ee0e-9320-4304-a3c2-2e237224922b"}
];
const rejected=new Map([["5ddd7cb2cbb9010009b4fe32","Aggregator source is unauthorized and ineligible for Nick Jr. Club."]]);
const unresolved=new Map([
 ["65d9167818036500080e8780","Generic slate only; Hunter x Hunter programming and source provenance were not established."],
 ["673bf05ddaad7f0008ac7a5c","Dinosaur programming observed, but opaque CloudFront provenance is insufficient."],
 ["66b646f9cd0d3100086af83c","Interview content observed, but exact 60 Minutes identity and opaque relay provenance were not established."],
 ["64a3d96f060e830008af6745","MovieSphere branding observed, but opaque CloudFront provenance is insufficient."]
]);
function probe(url:string){return new Promise<boolean>(done=>{const child=spawn("ffmpeg",["-hide_banner","-loglevel","error","-rw_timeout","15000000","-i",url,"-t","35","-map","0:v:0","-map","0:a:0","-f","null","-"],{windowsHide:true,stdio:"ignore"});const timer=setTimeout(()=>child.kill(),70000);child.once("close",code=>{clearTimeout(timer);done(code===0)});child.once("error",()=>{clearTimeout(timer);done(false)})})}
async function main(){loadAdminEnv(root);const db=getSupabaseAdmin();const {data,error}=await db.from("tv_videos").select("id,source_url,source_type").in("id",plans.map(x=>x.record));if(error)throw error;const results:any[]=[];for(let i=0;i<plans.length;i+=2)results.push(...await Promise.all(plans.slice(i,i+2).map(async plan=>{const row=(data??[]).find((x:any)=>x.id===plan.record),passed=row?await probe(row.source_url):false;return{providerChannelId:plan.id,existingCatalogRecordId:plan.record,sourceHost:row?new URL(row.source_url).hostname:null,sourceType:row?.source_type??null,provider:"official_fast",confidence:"EXACT",continuitySeconds:passed?35:0,videoAudioPassed:passed,rawUrlPersisted:false}})));const registry=JSON.parse(readFileSync(resolve(out,"master-recovery-registry.json"),"utf8"));for(const entry of registry.entries){const result=results.find(x=>x.providerChannelId===entry.providerChannelId);if(result?.videoAudioPassed){entry.terminalStatus="VERIFIED_PLAYABLE";entry.sourceCount=1;entry.verifiedSource={existingCatalogRecordId:result.existingCatalogRecordId,sourceHost:result.sourceHost,provider:result.provider,confidence:"EXACT",continuitySeconds:35,actualContentVerified:true,identityVerified:true,desktopRuntimeVerified:false,rawUrlPersisted:false}}if(rejected.has(entry.providerChannelId)){entry.terminalStatus="WRONG_SOURCE_REJECTED";entry.researchEvidence={...(entry.researchEvidence??{}),decision:"REJECT",reason:rejected.get(entry.providerChannelId)}}if(unresolved.has(entry.providerChannelId)){entry.terminalStatus="IDENTITY_UNRESOLVED";entry.researchEvidence={...(entry.researchEvidence??{}),decision:"SOURCE_AMBIGUOUS",reason:unresolved.get(entry.providerChannelId)}}}registry.generatedAt=new Date().toISOString();writeFileSync(resolve(out,"master-recovery-registry.json"),JSON.stringify(registry,null,2));const latest=JSON.parse(readFileSync(resolve(out,"latest-checkpoint.json"),"utf8")),verified=results.filter(x=>x.videoAudioPassed).length;const checkpoint={...latest,checkpointVersion:latest.checkpointVersion+1,phase:"BATCH_7_IDENTITY_AND_CONTINUITY_COMPLETE",createdAt:new Date().toISOString(),identitiesCompleted:verified+rejected.size+unresolved.size,verified,rejected:rejected.size,unresolved:unresolved.size,runtimeTested:0,runtimePassed:0,errors:results.filter(x=>!x.videoAudioPassed).map(x=>`Continuity failed: ${x.providerChannelId}`)};writeFileSync(resolve(out,"batch-007-finalization.json"),JSON.stringify({createdAt:new Date().toISOString(),productionWrites:0,rawPlaybackUrlsEmitted:0,results,rejected:[...rejected],unresolved:[...unresolved]},null,2));writeFileSync(resolve(out,"checkpoints/checkpoint-007.json"),JSON.stringify(checkpoint,null,2));writeFileSync(resolve(out,"latest-checkpoint.json"),JSON.stringify(checkpoint,null,2));console.log(JSON.stringify(checkpoint,null,2))}
main().catch(error=>{console.error(error);process.exitCode=1});
