import { spawn } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadAdminEnv } from "../lib/radioExpansion25k/env";
import { getSupabaseAdmin } from "../lib/supabaseAdmin";
const root=resolve(import.meta.dirname,".."),out=resolve(root,"data/tv-recovery"),recordId="53a581d9-7094-4587-a1d3-37c2a3ffbe72",providerId="69ef5682980899a9edf1a884";
async function probe(url:string){return new Promise<boolean>(done=>{const child=spawn("ffmpeg",["-hide_banner","-loglevel","error","-rw_timeout","15000000","-i",url,"-t","35","-map","0:v:0","-map","0:a:0","-f","null","-"],{windowsHide:true,stdio:"ignore"});const timer=setTimeout(()=>child.kill(),70_000);child.once("close",code=>{clearTimeout(timer);done(code===0)});child.once("error",()=>{clearTimeout(timer);done(false)})})}
async function main(){loadAdminEnv(root);const db=getSupabaseAdmin();const {data,error}=await db.from("tv_videos").select("id,source_url,source_type").eq("id",recordId).single();if(error)throw error;const passed=await probe(data.source_url);if(!passed)throw new Error("That's Rock continuity failed");const registry=JSON.parse(readFileSync(resolve(out,"master-recovery-registry.json"),"utf8"));const entry=registry.entries.find((x:any)=>x.providerChannelId===providerId);entry.terminalStatus="VERIFIED_PLAYABLE";entry.sourceCount=1;entry.verifiedSource={existingCatalogRecordId:recordId,sourceHost:new URL(data.source_url).hostname,provider:"official_fast",confidence:"EXACT",continuitySeconds:35,actualContentVerified:true,identityVerified:true,desktopRuntimeVerified:false,rawUrlPersisted:false};registry.generatedAt=new Date().toISOString();writeFileSync(resolve(out,"master-recovery-registry.json"),JSON.stringify(registry,null,2));const checkpoint=JSON.parse(readFileSync(resolve(out,"latest-checkpoint.json"),"utf8"));checkpoint.checkpointVersion++;checkpoint.createdAt=new Date().toISOString();checkpoint.verified++;checkpoint.identitiesCompleted++;checkpoint.errors=[];writeFileSync(resolve(out,"checkpoints/checkpoint-002.json"),JSON.stringify(checkpoint,null,2));writeFileSync(resolve(out,"latest-checkpoint.json"),JSON.stringify(checkpoint,null,2));writeFileSync(resolve(out,"batch-002-thats-rock-retry.json"),JSON.stringify({testedAt:new Date().toISOString(),productionWrites:0,rawPlaybackUrlsEmitted:0,providerChannelId:providerId,sourceHost:new URL(data.source_url).hostname,continuitySeconds:35,passed:true},null,2));console.log(JSON.stringify(checkpoint,null,2))}
main().catch(error=>{console.error(error);process.exitCode=1});
