/** Promote only discovery candidates whose official website directly references their stream host. */
/* eslint-disable @typescript-eslint/no-explicit-any -- consumes structured discovery evidence. */
import fs from "node:fs";import path from "node:path";import {fileURLToPath}from"node:url";
import{loadAdminEnv}from"@/lib/radioExpansion25k/env";import{probeStreamUrl}from"@/lib/tvStreamProtocol";import{probeTvStation,importVerifiedTvGrowthCandidates,type TvGrowthCandidate}from"@/lib/tvStationHealth";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");loadAdminEnv(root);const dir=path.join(root,"data","africa-tv-import-all");const input=path.join(dir,"report-dry-run.json");const cpFile=path.join(dir,"official-correlation-checkpoint.json");const reportFile=path.join(dir,"official-correlation-report.json");const project=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL||"";const publish=process.argv.includes("--publish");
function save(f:string,v:unknown){fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2))}function host(u:string){try{return new URL(u).hostname.toLowerCase()}catch{return""}}function esc(v:string){return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
async function fetchOfficial(url:string){try{const r=await fetch(url,{redirect:"follow",headers:{"User-Agent":"Mozilla/5.0 HiddenTunesSourceVerifier/1.0"},signal:AbortSignal.timeout(20000)});const type=r.headers.get("content-type")||"";if(!r.ok||!type.includes("text/html"))return{ok:false,status:r.status,html:""};return{ok:true,status:r.status,html:(await r.text()).slice(0,3_000_000)}}catch(e){return{ok:false,status:0,html:"",error:String(e)}}}
async function main(){if(!fs.existsSync(input))throw new Error("Run Africa-wide dry-run first.");if(publish&&project!=="https://kojcyswxfuikxmqntwye.supabase.co")throw new Error(`Unexpected project ${project}`);console.log(JSON.stringify({project,table:"tv_videos",mode:publish?"CORRELATE_VALIDATE_PUBLISH":"CORRELATE_DRY_RUN"}));
 const base=JSON.parse(fs.readFileSync(input,"utf8"));const leads:any[]=[];for(const entry of Object.values(base.byCountry)as any[])for(const o of entry.outcomes||[])if(o.state==="quarantined"&&o.reason==="stream_host_not_tied_to_official_source"&&o.website)leads.push(o);
 const websites=[...new Set(leads.map(o=>o.website))];const pages:Record<string,any>=fs.existsSync(cpFile)?JSON.parse(fs.readFileSync(cpFile,"utf8")):{};let next=0;await Promise.all(Array.from({length:4},async()=>{while(next<websites.length){const i=next++;const w=websites[i];if(!pages[w]){pages[w]=await fetchOfficial(w);save(cpFile,pages)}console.log(`Official ${i+1}/${websites.length} — ${w} — ${pages[w].ok?"fetched":"failed"}`)}}));
 const correlated=leads.filter(o=>{const page=pages[o.website];if(!page?.ok)return false;const h=host(o.url);return h&&new RegExp(esc(h),"i").test(page.html)});const outcomes=[] as any[];let imported=0;
 for(const o of correlated){try{const d=await probeStreamUrl(o.url,{timeoutMs:25000});const h=await probeTvStation({id:"candidate",title:o.title,source_type:"hls_stream",source_id:o.sourceId,source_url:o.url,embed_url:null,status:"approved",playback_status:"unchecked",is_active:false});if(!d.playable||!h.playable){outcomes.push({...o,state:"rejected",reason:d.reason||h.reason});continue}const accepted={...o,state:"accepted",reason:"official_page_references_stream_host",url:d.finalUrl||o.url,ios:h.ios_playable,android:h.android_playable,protocol:d.protocol};if(publish){const p:TvGrowthCandidate={source_type:"hls_stream",source_id:o.sourceId,source_url:accepted.url,source_key:`africa-official:${o.country}:${o.sourceId}`,title:o.title,description:`${o.title}, verified from official broadcaster page ${o.website}`,country:o.country,region:o.country,category:"General",tags:["Africa","official-page-correlated"]};const r=await importVerifiedTvGrowthCandidates([p]);accepted.state=r.imported===1?"imported":"duplicate";accepted.reason=r.imported===1?accepted.reason:"shared_importer_deduplicated_or_rejected";imported+=r.imported}outcomes.push(accepted)}catch(e){outcomes.push({...o,state:"rejected",reason:`exception:${String(e).slice(0,180)}`})}}
 const report={at:new Date().toISOString(),project,mode:publish?"PUBLISHED":"DRY_RUN",leads:leads.length,officialWebsites:websites.length,officialPagesFetched:Object.values(pages).filter((p:any)=>p.ok).length,correlated:correlated.length,tested:outcomes.length,accepted:outcomes.filter(o=>o.state==="accepted").length,imported,rejected:outcomes.filter(o=>o.state==="rejected").length,duplicates:outcomes.filter(o=>o.state==="duplicate").length,outcomes};save(reportFile,report);console.log(JSON.stringify({...report,outcomes:undefined},null,2));}
main().catch(e=>{console.error(e);process.exit(1)});
