import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadAdminEnv } from "@/lib/radioExpansion25k/env";
import { getSupabaseAdmin } from "@/lib/supabaseAdmin";
import type { TvRecoveryQueueItem } from "@/lib/tvProviders/recovery/types";
const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");
const requestedLimit=Math.max(1,Math.min(500,Number(process.argv.find(arg=>arg.startsWith("--limit="))?.split("=")[1]??50)));
const OUTPUT=join(ROOT,"data",requestedLimit>50?"pluto-phase2d":"pluto-phase2c");
const tierA=/(news|nachrichten|weather|wetter|public|international|world|music|mtv|sport|fifa|tennis|darts|government|parliament|bloomberg|cnn|bbc|cbs|nbc|euronews|france 24|reuters|al jazeera|red bull)/i;
const direct=/\.m3u8(?:\?|$)|\/hls\/|\/live\//i;
const normalize=(value:string)=>value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(pluto tv|pluto|720p|1080p|fhd|hd)\b/g," ").replace(/[^a-z0-9]+/g," ").trim();
async function rows(){loadAdminEnv(ROOT);const db=getSupabaseAdmin();const all:any[]=[];for(let from=0;;from+=1000){const {data,error}=await db.from("tv_videos").select("id,title,source_url,source_type,source_id,source_key,tags,region,language,category,status,playback_status,is_active").range(from,from+999);if(error)throw error;all.push(...(data??[]));if((data??[]).length<1000)break;}return all;}
async function main(){await mkdir(OUTPUT,{recursive:true});const map=JSON.parse(await readFile(join(ROOT,"data","pluto-phase2b","canonical-map.json"),"utf8"));const all=await rows();const plutoIds=new Set(map.flatMap((item:any)=>item.records));const nonPluto=all.filter((row)=>!plutoIds.has(row.id)&&!/pluto|jmp2\.uk/i.test(`${row.title} ${row.source_url} ${JSON.stringify(row.tags??[])}`));const score=(item:any)=>{const text=`${item.currentName??""} ${(item.names??[]).join(" ")} ${(item.categories??[]).join(" ")}`;let value=tierA.test(text)?100:0;if(/news|nachrichten|weather|wetter|public|government|parliament/i.test(text))value+=50;if(/music|mtv|international|world/i.test(text))value+=30;if(/sport|fifa|tennis|darts/i.test(text))value+=20;if(item.currentName)value+=10;return value;};const selected=[...map].filter((item:any)=>score(item)>=100).sort((a:any,b:any)=>score(b)-score(a)||String(a.currentName??a.names[0]).localeCompare(String(b.currentName??b.names[0]))).slice(0,requestedLimit);const now=new Date().toISOString();const queue:TvRecoveryQueueItem[]=selected.map((item:any)=>{const canonical=item.currentName??item.names[0];const key=normalize(canonical);const matches=nonPluto.filter((row)=>normalize(row.title??"")===key&&direct.test(row.source_url??"")&&!/youtube/i.test(`${row.source_type} ${row.source_url}`)).slice(0,5);const candidates=matches.map((row)=>({channelIdentity:item.providerId,sourceProvider:"existing_catalog_cross_reference",sourceType:row.source_type,sourceUrl:row.source_url,region:row.region??null,protocol:"hls" as const,requiresHeaders:false,requiresPublicSession:false,requiresAccount:false,drm:"unknown" as const,confidence:"MEDIUM" as const,provenance:`existing_tv_record:${row.id}`,discoveredAt:now,lastValidatedAt:null,validationStatus:"UNKNOWN" as const,platformCompatibility:{mobile:null,desktop:null,smartTv:null}}));return {identity:{provider:"pluto",providerChannelId:item.providerId,canonicalName:canonical,aliases:item.names,catalogOrigins:["pluto"],region:item.regions,language:item.languages,category:item.categories},tier:"A" as const,broadcaster:null,decision:candidates.length?"DIRECT_CANDIDATE" as const:"NO_SOURCE_FOUND" as const,candidates,evidence:[candidates.length?`Found ${candidates.length} exact-name direct-stream cross-reference(s); provenance requires verification.`:"No exact-name direct source in the existing non-Pluto catalog."]};});await writeFile(join(OUTPUT,`recovery-queue-${requestedLimit}.json`),JSON.stringify(queue,null,2));console.log(JSON.stringify({selected:queue.length,withDirectCrossReferences:queue.filter(x=>x.candidates.length).length,directCandidateRows:queue.reduce((n,x)=>n+x.candidates.length,0),languagesIdentified:queue.filter(x=>x.identity.language.length).length,regionsIdentified:queue.filter(x=>x.identity.region.length).length,names:queue.map(x=>x.identity.canonicalName)},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
