import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { createDogmazicAdapterFromEnv } from "../lib/externalCatalogAcquisition/adapters/dogmazic";
import { evaluateAudioQuality } from "../lib/externalCatalogAcquisition/audioQuality";
import { resolveCompositionRightsFromMetadata } from "../lib/externalCatalogAcquisition/compositionRightsResolver";
import { decideQualification } from "../lib/externalCatalogAcquisition/decisionEngine";
import { calculateAcousticFingerprint, DuplicateIndex, loadExistingFingerprintRecords } from "../lib/externalCatalogAcquisition/duplicateDetection";
import { validateDogmazicDownload } from "../lib/externalCatalogAcquisition/downloadValidator";
import { createEvidenceSnapshot } from "../lib/externalCatalogAcquisition/provenance";
import { qualifyRecordingRights } from "../lib/externalCatalogAcquisition/recordingRightsQualification";
import { classifyCanonicalTaxonomy, taxonomyUnmappedSourceValues } from "../lib/externalCatalogAcquisition/taxonomyQualification";
import { resolveStoragePolicy } from "../lib/externalCatalogAcquisition/storagePolicy";
import type { TaxonomyResult } from "../lib/externalCatalogAcquisition/qualificationTypes";
import { evaluateRights } from "../lib/externalCatalogAcquisition/rightsEvaluator";
import type { RightsEvaluationInput } from "../lib/externalCatalogAcquisition/types";
const arg=(name:string):string|null=>{const p=`--${name}=`;return process.argv.find(v=>v.startsWith(p))?.slice(p.length)||null;};
const canonical=(value:unknown):string=>Array.isArray(value)?`[${value.map(canonical).join(",")}]`:value&&typeof value==="object"?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`:JSON.stringify(value);
const count=(values:string[])=>Object.fromEntries(Object.entries(values.reduce<Record<string,number>>((a,v)=>(a[v]=(a[v]||0)+1,a),{})).sort(([a],[b])=>a.localeCompare(b)));
function fallbackRights(raw:Record<string,unknown>):RightsEvaluationInput { const value=raw.rightsInput; if(!value||typeof value!=="object") throw new Error("Cohort item has no immutable rights evidence."); return value as RightsEvaluationInput; }
async function main(){
  if(String(process.env.EXTERNAL_CATALOG_MEDIA_VALIDATION_ENABLED||"").toLowerCase()!=="true") throw new Error("EXTERNAL_CATALOG_MEDIA_VALIDATION_ENABLED=true is required for this qualification run.");
  const storage=resolveStoragePolicy(); const input=arg("input")||path.join(storage.root,"reports","dogmazic-phase2-dry-50.json"); const output=arg("output")||path.join(storage.root,"reports","dogmazic-media-rights-qualification-50.json"); const source=JSON.parse(await readFile(path.resolve(input),"utf8")) as Record<string,unknown>;
  if(source.provider!=="dogmazic"||!Array.isArray(source.items)) throw new Error("Input must be the existing Dogmazic cohort report.");
  const adapter=createDogmazicAdapterFromEnv(process.env,{allowMediaResolution:true}); const health=await adapter.healthCheck(); if(!health.reachable) throw new Error(`Dogmazic health check failed: ${health.reason||"unknown"}`);
  const existing=await loadExistingFingerprintRecords(process.env.EXTERNAL_CATALOG_EXISTING_DUPLICATE_MANIFEST); const duplicates=new DuplicateIndex(existing); const capturedAt=new Date().toISOString(); const refresh=String(process.env.EXTERNAL_CATALOG_REFRESH_COHORT_METADATA||"").toLowerCase()==="true"; const items:Record<string,unknown>[]=[];
  for(const rawValue of source.items){
    const raw=rawValue as Record<string,unknown>; const metadataFromCohort=(raw.metadata||{}) as Record<string,unknown>; const sourceItemId=String(raw.sourceItemId); const sourceUrl=String(raw.sourceUrl); let metadata=metadataFromCohort; let rightsInput:RightsEvaluationInput; let refreshError:string|null=null;
    try { rightsInput=refresh?await adapter.fetchRights(sourceItemId):fallbackRights(raw); if(refresh) metadata=adapter.normalize(await adapter.fetchMetadata(sourceItemId)); } catch(error) { refreshError=error instanceof Error?error.message:String(error); rightsInput=fallbackRights(raw); }
    const rightsEvaluation=evaluateRights(rightsInput); const recordingRights=qualifyRecordingRights(rightsInput.recording); const compositionRights=resolveCompositionRightsFromMetadata(metadata,capturedAt);
    const download=await validateDogmazicDownload({sourceItemId,resolveMedia:()=>adapter.resolveMedia(sourceItemId),storageRoot:storage.root,fingerprint:file=>calculateAcousticFingerprint(file)}); if(refreshError && download.status==="DOWNLOAD_FAIL" && !download.error) download.error=refreshError;
    const quality=evaluateAudioQuality(download); const fingerprint=download.fingerprint||{status:"UNAVAILABLE",fingerprint:null,durationSeconds:null,tool:null,error:"Fingerprint was not attempted because media validation failed."}; const duplicate=duplicates.evaluate({sourceItemId,artist:typeof metadata.artist==="string"?metadata.artist:null,title:typeof metadata.title==="string"?metadata.title:null,sha256:download.sha256},fingerprint); const taxonomy=classifyCanonicalTaxonomy(metadata); const final=decideQualification({recordingRights,rightsEvaluation,compositionRights,downloadStatus:download.status,quality,duplicate,taxonomy});
    const evidenceContent=canonical({provider:"dogmazic",sourceItemId,sourceUrl,artist:metadata.artist,title:metadata.title,album:metadata.album,rightsInput,compositionRights,capturedAt}); const evidence=createEvidenceSnapshot({evidenceUrl:String(metadata.licenseEvidenceUrl||"https://dogmazic.net/licences.php?lang=en"),content:evidenceContent,capturedAt});
    items.push({sourceItemId,sourceUrl,metadata,recordingRights,rightsInput,rightsEvaluation,compositionRights,recordingEvidence:{source:"dogmazic",sourceItemId,artist:metadata.artist,title:metadata.title,album:metadata.album,licenseName:rightsInput.recording.licenseName,licenseUrl:rightsInput.recording.licenseUrl,licenseIdentifier:rightsInput.recording.licenseIdentifier,attributionRequired:rightsInput.recording.attributionRequired,commercialUseAllowed:rightsInput.recording.commercialUseAllowed,derivativeWorksAllowed:rightsInput.recording.derivativeWorksAllowed,shareAlikeRequired:false,sourceEvidenceUrl:evidence.evidenceUrl,evidenceTimestamp:evidence.capturedAt,evidenceHash:evidence.evidenceHash},compositionEvidence:compositionRights.evidence,refreshError,media:{...download,temporaryPath:null,persistedUrl:false},quality,duplicate,taxonomy,final,production:{published:false,ingestionAttempted:false,productionId:null}});
  }
  const finalValues=items.map(i=>String((i.final as Record<string,unknown>).verdict)); const report={schemaVersion:2,provider:"dogmazic",mode:"MEDIA_RIGHTS_QUALIFICATION",cohortInput:path.resolve(input),requested:Number(source.requested||items.length),discovered:items.length,capturedAt,health,cohortMetadataRefreshed:refresh,previousCounts:source.counts,temporaryMediaRoot:path.join(storage.root,"staging","dogmazic"),mediaRemovedAfterEachItem:true,existingCatalogComparison:process.env.EXTERNAL_CATALOG_EXISTING_DUPLICATE_MANIFEST?"READ_ONLY_MANIFEST":"NOT_CONFIGURED",counts:{recordingRights:count(items.map(i=>(i.recordingRights as Record<string,unknown>).eligible?"ELIGIBLE":"INELIGIBLE")),compositionRights:count(items.map(i=>(i.compositionRights as Record<string,unknown>).status as string)),download:count(items.map(i=>(i.media as Record<string,unknown>).status as string)),mediaFailures:count(items.map(i=>String((i.media as Record<string,unknown>).failureClass||"NONE")).filter(v=>v!=="NONE")),audioQuality:count(items.map(i=>(i.quality as Record<string,unknown>).verdict as string)),duplicates:count(items.map(i=>(i.duplicate as Record<string,unknown>).verdict as string)),taxonomy:count(items.map(i=>(i.taxonomy as Record<string,unknown>).status as string)),taxonomyConfidence:count(items.map(i=>(i.taxonomy as Record<string,unknown>).confidenceBand as string)),unmappedSourceValues:taxonomyUnmappedSourceValues(items.map(i=>i.taxonomy as TaxonomyResult)),final:count(finalValues)},gates:{downloads:true,taxonomyClassification:true,ingestion:false,publishing:false,productionDatabase:false},authorization:{greenRequiresIndependentCompositionRights:true,greenRequiresAcousticFingerprint:true,zeroGreenAcceptable:true,authorizeDogmazic100ItemStagedQualification:false},items};
  await mkdir(path.dirname(path.resolve(output)),{recursive:true}); await writeFile(path.resolve(output),`${JSON.stringify(report,null,2)}\n`,"utf8"); await mkdir(path.join(storage.root,"fingerprints"),{recursive:true}); await writeFile(path.join(storage.root,"fingerprints","dogmazic-blocker-resolution-50.json"),`${JSON.stringify(items.map(i=>({sourceItemId:i.sourceItemId,sha256:(i.media as Record<string,unknown>).sha256,fingerprint:(i.duplicate as Record<string,unknown>).fingerprint})),null,2)}\n`,"utf8"); const md=path.resolve(output).replace(/\.json$/i,".md"); const c=report.counts as Record<string,unknown>; const markdown=`# Dogmazic media + rights qualification (50)\n\nCaptured: ${capturedAt}\n\n## Counts\n\n- Final: ${JSON.stringify(c.final)}\n- Recording rights: ${JSON.stringify(c.recordingRights)}\n- Composition rights: ${JSON.stringify(c.compositionRights)}\n- Downloads: ${JSON.stringify(c.download)}\n- Media failure classes: ${JSON.stringify(c.mediaFailures)}\n- Audio quality: ${JSON.stringify(c.audioQuality)}\n- Duplicates: ${JSON.stringify(c.duplicates)}\n- Taxonomy status: ${JSON.stringify(c.taxonomy)}\n- Taxonomy confidence: ${JSON.stringify(c.taxonomyConfidence)}\n- Unmapped source values: ${JSON.stringify(c.unmappedSourceValues)}\n\n## Safety and blockers\n\nTemporary media was constrained to D: and removed after each item. No media URL, production ID, upload job, or production catalog mutation was permitted. Composition rights defaulted to UNKNOWN unless independently evidenced. Source item disappearance or media validation failure is retained as a per-item failure. The 100-item qualification is not authorized.\n`;
  await writeFile(md,markdown,"utf8"); console.log(JSON.stringify({result:"DOGMAZIC_MEDIA_RIGHTS_QUALIFICATION_COMPLETE",output:path.resolve(output),markdown:md,counts:report.counts,authorize100:false},null,2));
}
main().catch(error=>{console.error(error);process.exitCode=1;});