import { spawn } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { TvRecoveryQueueItem } from "@/lib/tvProviders/recovery/types";
const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");const OUTPUT=join(ROOT,"data","pluto-phase2c");
const ids=["62b976b93279cb000772c6f9","5a6b92f6e22a617379789618","5dc9b875e280c80009a8a44a","60fb299b79498900070b29e0","60cb6df2b2ad610008cd5bea","60492e6d7f3f560007ab0f62","61de8e502c8e9400077e5de7","61de90a47365340007f77c27"];
const eligible=/cbsnews\.com$|cbsivideo\.com$|dai\.google\.com$|foxweather\.com$|cdn-euronews\.akamaized\.net$|bloomberg\.com$|vs-hls-push-ww-live\.akamaized\.net$|amagi\.tv$|amagi-streams\.akamaized\.net$/i;
function test(url:string,seconds:number):Promise<boolean>{return new Promise(resolve=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-i",url,"-t",String(seconds),"-map","0:v:0","-f","null","NUL"],{windowsHide:true,stdio:"ignore"});const timer=setTimeout(()=>p.kill(),(seconds+45)*1000);p.once("exit",code=>{clearTimeout(timer);resolve(code===0)});p.once("error",()=>{clearTimeout(timer);resolve(false)});});}
async function pool<T,R>(values:T[],limit:number,fn:(value:T)=>Promise<R>){const output:R[]=[];let cursor=0;async function worker(){while(cursor<values.length){const index=cursor++;output[index]=await fn(values[index]);}}await Promise.all(Array.from({length:Math.min(limit,values.length)},worker));return output;}
async function main(){const queue=JSON.parse(await readFile(join(OUTPUT,"tier-a-50-recovery-queue.json"),"utf8")) as TvRecoveryQueueItem[];const chosen=ids.map(id=>{const item=queue.find(q=>q.identity.providerChannelId===id)!;const candidate=item.candidates.find(c=>eligible.test(new URL(c.sourceUrl).hostname))!;return {id,name:item.identity.canonicalName,url:candidate.sourceUrl,host:new URL(candidate.sourceUrl).hostname};});const thirty=await pool(chosen,3,async c=>({...c,passed:await test(c.url,30)}));const twoMinute=await pool(chosen.filter((_,i)=>i<3),2,async c=>({...c,passed:await test(c.url,120)}));const fiveMinute=await pool(chosen.filter((_,i)=>i<1),1,async c=>({...c,passed:await test(c.url,300)}));const redact=(rows:any[])=>rows.map(({url,...row})=>row);const report={testedAt:new Date().toISOString(),productionWrites:0,thirtySeconds:redact(thirty),twoMinutes:redact(twoMinute),fiveMinutes:redact(fiveMinute)};await writeFile(join(OUTPUT,"continuity-validation.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
