import assert from"node:assert/strict";import{ownerAlertFingerprint}from"../lib/ownerAlerts/fingerprint";import{initialDeliveryState,reopenedStatus,shouldDeliver}from"../lib/ownerAlerts/policy";import{redactText,sanitizeMetadata}from"../lib/ownerAlerts/redaction";import{DisabledSmsProvider}from"../lib/ownerAlerts/smsProvider";import{buildOwnerDigest}from"../lib/ownerAlerts/digest";import{normalizePm2Snapshot}from"../lib/ownerAlerts/watchdog";import type{OwnerAlertRecord}from"../lib/ownerAlerts/types";
async function main(){const base={eventType:"pm2.offline",severity:"critical" as const,source:"watchdog",title:"x",message:"x",entityId:"hidden-tunes-admin"};
assert.equal(ownerAlertFingerprint(base),ownerAlertFingerprint({...base,title:"changed",message:"changed"}));assert.match(ownerAlertFingerprint(base),/^[a-f0-9]{64}$/);
assert.equal(initialDeliveryState("critical"),"pending");assert.equal(initialDeliveryState("normal"),"digest_pending");assert.equal(shouldDeliver("critical",1,null,new Date()),true);assert.equal(shouldDeliver("critical",2,new Date().toISOString(),new Date()),false);assert.equal(reopenedStatus("resolved","2026-01-01",new Date("2026-01-02")),"open");
const safe=sanitizeMetadata({authorization:"Bearer secret",cookie:"x",email:"me@example.com",phone:"+491234567890",url:"https://x.test/?token=abc",undefinedValue:undefined,nested:{value:undefined},array:["x"],nullValue:null,oversized:"x".repeat(900)});assert.equal(safe.authorization,"[REDACTED]");assert.equal(safe.email,"[REDACTED]");assert.ok(String(safe.url).includes("[REDACTED]"));assert.equal("undefinedValue" in safe,false);assert.equal("nested" in safe,false);assert.equal("array" in safe,false);assert.equal(safe.nullValue,null);assert.ok(String(safe.oversized).length<=500);assert.ok(redactText("Bearer abc.def me@example.com").includes("[REDACTED]"));
delete process.env.OWNER_ALERT_PHONE;assert.equal((await new DisabledSmsProvider().send("x")).state,"disabled");
const record={severity:"normal",delivery_state:"digest_pending",event_type:"deployment.succeeded",occurrence_count:2}as OwnerAlertRecord;assert.match(buildOwnerDigest([record]),/deployment\.succeeded: 2/);
assert.equal(normalizePm2Snapshot({name:"hidden-tunes-admin",status:"online",restarts:0,windowMinutes:10}),null);assert.equal(normalizePm2Snapshot({name:"hidden-tunes-admin",status:"offline",restarts:0,windowMinutes:10})?.eventType,"pm2.offline");assert.equal(normalizePm2Snapshot({name:"hidden-tunes-admin",status:"online",restarts:5,windowMinutes:10})?.eventType,"pm2.restart_loop");
console.log("owner alert core contracts: PASS");}
void main();
