import assert from "node:assert/strict";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { resolveCompositionRights, resolveCompositionRightsFromMetadata } from "../lib/externalCatalogAcquisition/compositionRightsResolver";
import { qualifyRecordingRights } from "../lib/externalCatalogAcquisition/recordingRightsQualification";
import { validateDogmazicDownload } from "../lib/externalCatalogAcquisition/downloadValidator";
import { evaluateAudioQuality } from "../lib/externalCatalogAcquisition/audioQuality";
import { calculateAcousticFingerprint, DuplicateIndex } from "../lib/externalCatalogAcquisition/duplicateDetection";
import { classifyCanonicalTaxonomy } from "../lib/externalCatalogAcquisition/taxonomyQualification";
import { decideQualification } from "../lib/externalCatalogAcquisition/decisionEngine";
import type { RightsEvaluation, RightsLayerInput } from "../lib/externalCatalogAcquisition/types";
const rights: RightsLayerInput={layer:"recording",licenseName:"Creative Commons - by 4.0",licenseIdentifier:"CC-BY-4.0",licenseUrl:"https://creativecommons.org/licenses/by/4.0/",commercialUseAllowed:true,redistributionAllowed:true,derivativeWorksAllowed:true,evidencePresent:true,attributionRequired:true,attributionText:"credit"};
const composition=resolveCompositionRights({artist:"Artist",composer:null,recordingRights:rights}); const explicit=resolveCompositionRightsFromMetadata({artist:"Artist",composer:"Artist",originalWorkDeclaration:"Original song written and performed by Artist",sourceUrl:"https://example.invalid/track"}); assert.equal(explicit.status,"ORIGINAL_BY_RECORDING_ARTIST"); const ambiguous=resolveCompositionRightsFromMetadata({artist:"Artist",composer:"Artist",sourceUrl:"https://example.invalid/track"}); assert.equal(ambiguous.status,"UNKNOWN"); assert.equal(composition.status,"UNKNOWN"); assert.equal(qualifyRecordingRights(rights).eligible,true); assert.equal(resolveCompositionRights({artist:"Artist",composer:"Artist",recordingRights:rights,explicitStatus:"ORIGINAL_BY_RECORDING_ARTIST"}).status,"CONFLICT");
function wav():Uint8Array { const b=new Uint8Array(44+80000); const v=new DataView(b.buffer); const put=(o:number,s:string)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0))); put(0,"RIFF"); v.setUint32(4,b.length-8,true); put(8,"WAVEfmt "); v.setUint32(16,16,true); v.setUint16(20,1,true); v.setUint16(22,1,true); v.setUint32(24,8000,true); v.setUint32(28,8000,true); v.setUint16(32,1,true); v.setUint16(34,8,true); put(36,"data"); v.setUint32(40,80000,true); for(let i=0;i<80000;i++) v.setUint8(44+i,128+Math.round(40*Math.sin(2*Math.PI*440*i/8000))); return b; }
const valid=wav(); const response=(body:BodyInit,headers:Record<string,string>)=>new Response(body,{status:200,headers});
async function main(){
const fingerprintPath="D:\\HiddenTunes\\Data\\external-acquisition\\staging\\qualification-test.wav"; await mkdir(path.dirname(fingerprintPath),{recursive:true}); await writeFile(fingerprintPath,Buffer.from(valid)); const fp=await calculateAcousticFingerprint(fingerprintPath); assert.equal(fp.status,"AVAILABLE",fp.error||"fingerprint unavailable"); assert.ok(fp.fingerprint); await rm(fingerprintPath,{force:true}); const download=await validateDogmazicDownload({sourceItemId:"1",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/1"}),fetchImpl:async()=>response(Buffer.from(valid),{"content-type":"audio/wav"}),sleep:async()=>undefined}); assert.equal(download.status,"DOWNLOAD_PASS"); assert.equal((await evaluateAudioQuality(download)).verdict,"AUDIO_PASS");
const html=await validateDogmazicDownload({sourceItemId:"2",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/2"}),fetchImpl:async()=>response("<html>error</html>",{"content-type":"audio/mpeg"}),sleep:async()=>undefined,maxRetries:0}); assert.equal(html.status,"DOWNLOAD_FAIL"); assert.match(html.error||"",/HTML/); assert.equal(html.failureClass,"HTML_RESPONSE");
const badMime=await validateDogmazicDownload({sourceItemId:"3",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/3"}),fetchImpl:async()=>response(Buffer.from(valid),{"content-type":"text/html"}),sleep:async()=>undefined,maxRetries:0}); assert.equal(badMime.status,"DOWNLOAD_FAIL"); assert.match(badMime.error||"",/MIME/); assert.equal(badMime.failureClass,"INVALID_MIME");
const corrupt=await validateDogmazicDownload({sourceItemId:"4",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/4"}),fetchImpl:async()=>response(new Uint8Array([1,2,3]),{"content-type":"audio/wav"}),sleep:async()=>undefined,maxRetries:0}); assert.equal(corrupt.status,"DOWNLOAD_FAIL"); assert.equal(corrupt.failureClass,"CORRUPT_AUDIO");
const oversized=await validateDogmazicDownload({sourceItemId:"5",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",maxBytes:10,resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/5"}),fetchImpl:async()=>response(Buffer.from(valid),{"content-type":"audio/wav","content-length":"999"}),sleep:async()=>undefined,maxRetries:0}); assert.equal(oversized.status,"DOWNLOAD_FAIL"); assert.match(oversized.error||"",/maximum/);
const stale=await validateDogmazicDownload({sourceItemId:"8",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",resolveMedia:async()=>{throw new Error("Dogmazic fail-closed: song 8 license URL is missing or unknown.")},fetchImpl:async()=>response(Buffer.from(valid),{"content-type":"audio/wav"}),sleep:async()=>undefined,maxRetries:0}); assert.equal(stale.failureClass,"API_METADATA_STALE"); const timeout=await validateDogmazicDownload({sourceItemId:"6",storageRoot:"D:\\HiddenTunes\\Data\\external-acquisition",resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/6"}),fetchImpl:async()=>{throw new DOMException("timed out","AbortError")},sleep:async()=>undefined,maxRetries:0}); assert.equal(timeout.status,"DOWNLOAD_FAIL"); assert.equal(timeout.failureClass,"TIMEOUT");
await assert.rejects(()=>validateDogmazicDownload({sourceItemId:"7",storageRoot:"C:\\blocked",resolveMedia:async()=>({mediaUrl:"https://play.dogmazic.net/media/7"})}));
const index=new DuplicateIndex([{sourceItemId:"10",artist:"A",title:"T",sha256:"h",fingerprint:"fp",origin:"accepted_external"}]); assert.equal(index.evaluate({sourceItemId:"11",artist:"A",title:"T",sha256:"x"},{status:"AVAILABLE",fingerprint:"different",durationSeconds:1,tool:"fpcalc",error:null}).verdict,"METADATA_COLLISION"); assert.equal(index.evaluate({sourceItemId:"12",artist:"B",title:"B",sha256:"h"},{status:"AVAILABLE",fingerprint:"different",durationSeconds:1,tool:"fpcalc",error:null}).verdict,"EXACT_DUPLICATE"); assert.equal(index.evaluate({sourceItemId:"13",artist:"C",title:"C",sha256:"z"},{status:"AVAILABLE",fingerprint:"fp",durationSeconds:1,tool:"fpcalc",error:null}).verdict,"LIKELY_AUDIO_DUPLICATE"); assert.equal(new DuplicateIndex().evaluate({sourceItemId:"14",artist:"D",title:"D",sha256:"z"},{status:"UNAVAILABLE",fingerprint:null,durationSeconds:null,tool:null,error:"tool unavailable"}).verdict,"REVIEW_REQUIRED");
assert.equal(classifyCanonicalTaxonomy({genres:["Jazz"]}).status,"TAXONOMY_PASS"); assert.equal(classifyCanonicalTaxonomy({genres:["Punk Rock"]}).confidenceBand,"MEDIUM"); assert.equal(classifyCanonicalTaxonomy({genres:["Unmapped experimental term"]}).status,"TAXONOMY_REVIEW");
const evaluation:RightsEvaluation={bucket:"AMBER",decision:"REVIEW",nextState:"RIGHTS_REVIEW",reason:"review",attributionRequired:false,attributionText:null,recording:rights,composition:{...rights,layer:"composition",licenseName:null,commercialUseAllowed:null,redistributionAllowed:null,evidencePresent:true}}; const final=decideQualification({recordingRights:{eligible:true},rightsEvaluation:evaluation,compositionRights:composition,downloadStatus:"DOWNLOAD_PASS",quality:evaluateAudioQuality(download),duplicate:{verdict:"UNIQUE",reasons:[],sourceIdentity:"x",normalizedMetadata:"x",fileHash:"x",fingerprint:{status:"AVAILABLE",fingerprint:"x",durationSeconds:1,tool:"fpcalc",error:null},comparedWith:[]},taxonomy:classifyCanonicalTaxonomy({genres:["Jazz"]})}); assert.equal(final.verdict,"AMBER / RIGHTS_REVIEW");
const runner=await readFile(path.join(process.cwd(),"scripts","run-dogmazic-media-rights-qualification.ts"),"utf8"); assert.match(runner,/productionId:null/); assert.doesNotMatch(runner,/insert into public\.songs/i);
console.log("external-catalog-qualification: PASS");
}
main().catch((error)=>{console.error(error);process.exitCode=1;});
