import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { rankVerifiedTvSources } from "../lib/tvProviders/recovery/waterfall";
import type { TvPlaybackSourceCandidate, TvSourceHealth } from "../lib/tvProviders/recovery/types";
const root=resolve(import.meta.dirname,"..");const queue=JSON.parse(readFileSync(resolve(root,"data/pluto-phase2c/tier-a-50-recovery-queue.json"),"utf8"));
const cases=[{id:"62b976b93279cb000772c6f9",hosts:[/bloomberg\.com$/i,/wurl\.com$/i],providers:["broadcaster_direct","official_fast"]},{id:"5a6b92f6e22a617379789618",hosts:[/cbsnews\.com$/i,/dai\.google\.com$/i],providers:["broadcaster_direct","broadcaster_public_api"]},{id:"60492e6d7f3f560007ab0f62",hosts:[/estrellanews-glewed\.amagi\.tv$/i,/estrella-news-oando\.amagi\.tv$/i],providers:["official_fast","official_fast"]}];
function probe(url:string){const started=Date.now();const run=spawnSync("ffmpeg",["-hide_banner","-loglevel","error","-rw_timeout","12000000","-i",url,"-t","8","-map","0:v:0","-map","0:a:0","-f","null","-"],{encoding:"utf8",timeout:20_000});return{passed:run.status===0,latencyMs:Date.now()-started,errorClass:run.status===0?null:"transport_or_decode_failure"}}
function candidate(item:any,source:any,index:number,provider:string):TvPlaybackSourceCandidate{return{...source,sourceProvider:provider,confidence:"HIGH",drm:false,requiresAccount:false,validationStatus:"PLAYING_CONTENT",health:"VERIFIED_HEALTHY",actualContentVerified:true,continuitySeconds:300,provenance:`${index+1}-${source.provenance}`,platformCompatibility:{mobile:null,desktop:true,smartTv:null}}}
const results=cases.map(test=>{const item=queue.find((entry:any)=>entry.identity.providerChannelId===test.id);const sources=test.hosts.map(pattern=>item.candidates.find((entry:any)=>pattern.test(new URL(entry.sourceUrl).hostname)));const candidates=sources.map((source,index)=>candidate(item,source,index,test.providers[index]));const initialProbes=sources.map(source=>probe(source.sourceUrl));candidates.forEach((entry,index)=>entry.health=initialProbes[index].passed?"VERIFIED_HEALTHY":"TEMPORARILY_UNAVAILABLE");const initial=rankVerifiedTvSources(candidates)[0];candidates[0].health="TEMPORARILY_UNAVAILABLE";const fallback=rankVerifiedTvSources(candidates)[0];const fallbackPlayback=fallback?probe(fallback.sourceUrl):{passed:false,latencyMs:0,errorClass:"no_fallback"};const primaryRecovery=probe(candidates[0].sourceUrl);candidates[0].health=(primaryRecovery.passed?"VERIFIED_HEALTHY":"TEMPORARILY_UNAVAILABLE") as TvSourceHealth;const restored=rankVerifiedTvSources(candidates)[0];return{id:test.id,name:item.identity.canonicalName,initialPrimaryRank:initial===candidates[0]?1:null,primaryMarkedUnhealthy:true,fallbackRank:fallback===candidates[1]?2:null,fallbackPlayback,primaryRecovery,restoredPrimaryRank:restored===candidates[0]?1:null,passed:initial===candidates[0]&&fallback===candidates[1]&&fallbackPlayback.passed&&primaryRecovery.passed&&restored===candidates[0]}});
const report={testedAt:new Date().toISOString(),productionWrites:0,rawPlaybackUrlsEmitted:0,channels:results.length,results,passed:results.every(result=>result.passed)};mkdirSync(resolve(root,"data/pluto-phase2e"),{recursive:true});writeFileSync(resolve(root,"data/pluto-phase2e/fallback-recovery.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));process.exitCode=report.passed?0:1;
