import { spawn } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { TvRecoveryQueueItem } from "@/lib/tvProviders/recovery/types";
const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");const OUTPUT=join(ROOT,"data","pluto-phase2d");
const eligible=/cbsnews\.com$|cbsivideo\.com$|dai\.google\.com$|foxweather\.com$|cdn-euronews\.akamaized\.net$|bloomberg\.com$|fast\.nbcuni\.com$|skynewsarabia\.com$|akamaized\.net$|amagi\.tv$|wurl\.com$|fast\.rakuten\.tv$/i;
const slate=["9896530d4d230e00","4b9b3529c1463630","9c96530f2d232e00","4b9b3529c5463630","9c93534d25232600","6b8931295b443430","9c16514d6d2b2e00","c39b3d29c6463630"].map(x=>BigInt(`0x${x}`));
function hamming(a:bigint,b:bigint){let v=a^b,c=0;while(v){c++;v&=v-1n;}return c;}
function hash(path:string):Promise<{hash:string|null,distance:number|null}>{return new Promise(resolve=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-i",path,"-vf","scale=9:8,format=gray","-frames:v","1","-f","rawvideo","pipe:1"],{windowsHide:true});const chunks:Buffer[]=[];p.stdout.on("data",d=>chunks.push(Buffer.from(d)));p.once("exit",()=>{const b=Buffer.concat(chunks);if(b.length<72)return resolve({hash:null,distance:null});let bits="";for(let y=0;y<8;y++)for(let x=0;x<8;x++)bits+=b[y*9+x]>b[y*9+x+1]?"1":"0";const value=BigInt(`0b${bits}`);resolve({hash:value.toString(16).padStart(16,"0"),distance:Math.min(...slate.map(s=>hamming(value,s)))});});p.once("error",()=>resolve({hash:null,distance:null}));});}
function sample(url:string,pattern:string):Promise<boolean>{return new Promise(resolve=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-y","-i",url,"-t","29","-vf","fps=1/10,scale=480:-2","-frames:v","3",pattern],{windowsHide:true,stdio:"ignore"});const timer=setTimeout(()=>p.kill(),70000);p.once("exit",code=>{clearTimeout(timer);resolve(code===0)});p.once("error",()=>{clearTimeout(timer);resolve(false)});});}
async function pool<T,R>(items:T[],limit:number,fn:(item:T,index:number)=>Promise<R>){const out:R[]=[];let cursor=0;async function worker(){while(cursor<items.length){const i=cursor++;out[i]=await fn(items[i],i);}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out;}
async function main(){const queue=JSON.parse(await readFile(join(OUTPUT,"recovery-queue-150.json"),"utf8")) as TvRecoveryQueueItem[];const candidates:any[]=[];for(const item of queue){for(const candidate of item.candidates){const host=new URL(candidate.sourceUrl).hostname;if(eligible.test(host)&&!/samsung|roku|jmp2|youtube/i.test(`${candidate.sourceUrl} ${candidate.provenance}`))candidates.push({item,candidate,host});if(candidates.length===50)break;}if(candidates.length===50)break;}const frames=join(tmpdir(),"hidden-tunes-pluto-phase2d-50");await rm(frames,{recursive:true,force:true});await mkdir(frames,{recursive:true});const results=await pool(candidates,3,async({item,candidate,host},i)=>{const stem=`${String(i+1).padStart(2,"0")}-${item.identity.providerChannelId}`;const pattern=join(frames,`${stem}-%02d.jpg`);const decoded=await sample(candidate.sourceUrl,pattern);const samples=[];if(decoded)for(let n=1;n<=3;n++){const path=join(frames,`${stem}-${String(n).padStart(2,"0")}.jpg`);samples.push({path,...await hash(path)});}const slateMatches=samples.filter(x=>x.distance!==null&&x.distance<=8).length;return{providerChannelId:item.identity.providerChannelId,canonicalName:item.identity.canonicalName,category:item.identity.category,region:item.identity.region,sourceHost:host,provenance:candidate.provenance,decoded,samples,automaticState:!decoded?"DEAD":slateMatches>=2?"END_OF_AVAILABILITY":"NEEDS_VISUAL_IDENTITY_REVIEW"};});const report={testedAt:new Date().toISOString(),productionWrites:0,candidatesTested:results.length,decoded:results.filter(x=>x.decoded).length,dead:results.filter(x=>!x.decoded).length,endOfAvailability:results.filter(x=>x.automaticState==="END_OF_AVAILABILITY").length,negativeControlFrames:results.flatMap(x=>x.samples).filter(x=>x.distance!==null&&x.distance>8).length,rawPlaybackUrlsEmitted:0,results};await writeFile(join(OUTPUT,"technical-validation-50.json"),JSON.stringify(report,null,2));console.log(JSON.stringify({...report,results:results.map(({samples,...x})=>({...x,sampleCount:samples.length,minSlateDistance:Math.min(...samples.map(s=>s.distance??99))}))},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
