import { spawn } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { TvRecoveryQueueItem } from "@/lib/tvProviders/recovery/types";
const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");const OUTPUT=join(ROOT,"data","pluto-phase2c");
const eligible=/cbsnews\.com$|cbsivideo\.com$|dai\.google\.com$|foxweather\.com$|cdn-euronews\.akamaized\.net$|bloomberg\.com$|vs-hls-push-ww-live\.akamaized\.net$|amagi\.tv$|amagi-streams\.akamaized\.net$/i;
const slateHashes=["9896530d4d230e00","4b9b3529c1463630","9c96530f2d232e00","4b9b3529c5463630","9c93534d25232600","6b8931295b443430","9c16514d6d2b2e00","c39b3d29c6463630"].map(x=>BigInt(`0x${x}`));
function hamming(a:bigint,b:bigint){let v=a^b,c=0;while(v){c++;v&=v-1n;}return c;}
function decode(url:string,output:string):Promise<{decoded:boolean,hash:string|null,minSlateDistance:number|null}>{return new Promise(resolve=>{const p=spawn("ffmpeg",["-hide_banner","-loglevel","error","-y","-i",url,"-t","15","-vf","thumbnail,scale=480:-2","-frames:v","1",output],{windowsHide:true,stdio:"ignore"});const timer=setTimeout(()=>p.kill(),40000);p.once("exit",code=>{clearTimeout(timer);if(code!==0)return resolve({decoded:false,hash:null,minSlateDistance:null});const h=spawn("ffmpeg",["-hide_banner","-loglevel","error","-i",output,"-vf","scale=9:8,format=gray","-frames:v","1","-f","rawvideo","pipe:1"],{windowsHide:true});const chunks:Buffer[]=[];h.stdout.on("data",d=>chunks.push(Buffer.from(d)));h.once("exit",()=>{const b=Buffer.concat(chunks);if(b.length<72)return resolve({decoded:true,hash:null,minSlateDistance:null});let bits="";for(let y=0;y<8;y++)for(let x=0;x<8;x++)bits+=b[y*9+x]>b[y*9+x+1]?"1":"0";const value=BigInt(`0b${bits}`);resolve({decoded:true,hash:value.toString(16).padStart(16,"0"),minSlateDistance:Math.min(...slateHashes.map(s=>hamming(value,s)))});});});p.once("error",()=>resolve({decoded:false,hash:null,minSlateDistance:null}));});}
async function main(){const queue=JSON.parse(await readFile(join(OUTPUT,"tier-a-50-recovery-queue.json"),"utf8")) as TvRecoveryQueueItem[];const selected:any[]=[];const names=new Set<string>();for(const item of queue){const candidate=item.candidates.find(c=>{try{return eligible.test(new URL(c.sourceUrl).hostname)}catch{return false}});const key=item.identity.canonicalName.replace(/\s*\(720p\)\s*/i,"").toLowerCase();if(candidate&&!names.has(key)){names.add(key);selected.push({item,candidate});if(selected.length===20)break;}}const frameDir=join(tmpdir(),"hidden-tunes-pluto-phase2c-controls");await rm(frameDir,{recursive:true,force:true});await mkdir(frameDir,{recursive:true});const results=[];for(const [i,{item,candidate}] of selected.entries()){const path=join(frameDir,`${String(i+1).padStart(2,"0")}-${item.identity.providerChannelId}.jpg`);const sample=await decode(candidate.sourceUrl,path);results.push({providerChannelId:item.identity.providerChannelId,canonicalName:item.identity.canonicalName,sourceHost:new URL(candidate.sourceUrl).hostname,provenance:candidate.provenance,...sample,automaticState:!sample.decoded?"DEAD":sample.minSlateDistance!==null&&sample.minSlateDistance<=8?"END_OF_AVAILABILITY":"NEEDS_VISUAL_REVIEW",frame:path});}const report={validatedAt:new Date().toISOString(),productionWrites:0,selected:results.length,rawPlaybackUrlsEmitted:0,results};await writeFile(join(OUTPUT,"technical-validation-20.json"),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
main().catch(e=>{console.error(e);process.exitCode=1});
