-- =============================================================================
-- Hidden Tunes TV — Safe Starter Catalog Seed
-- =============================================================================
-- Curated public, embeddable YouTube metadata only (no download/rehost).
-- Sources: NPR Music Tiny Desk, BBC Music, NASA (public domain), TED.
-- Safe to re-run: upserts on (source_type, source_id).
--
-- Run in Supabase SQL Editor after tv_catalog migration is applied.
-- =============================================================================

insert into public.tv_videos (
  source_type,
  source_id,
  source_url,
  embed_url,
  title,
  thumbnail_url,
  channel_name,
  category,
  genre,
  mood,
  format,
  tags,
  status,
  playback_status,
  is_active,
  is_featured,
  sort_order
)
values
  -- Blues (Live Performances)
  (
    'youtube_video',
    'm5XxOLdMSS8',
    'https://www.youtube.com/watch?v=m5XxOLdMSS8',
    'https://www.youtube.com/embed/m5XxOLdMSS8',
    'Buddy Guy: Tiny Desk Concert',
    'https://i.ytimg.com/vi/m5XxOLdMSS8/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Blues',
    'Soulful',
    'Live Performances',
    array['tiny-desk', 'blues', 'live', 'official'],
    'approved',
    'playable',
    true,
    true,
    1
  ),
  (
    'youtube_video',
    'rPVQlQQgPLg',
    'https://www.youtube.com/watch?v=rPVQlQQgPLg',
    'https://www.youtube.com/embed/rPVQlQQgPLg',
    'Charley Crockett: Tiny Desk Concert',
    'https://i.ytimg.com/vi/rPVQlQQgPLg/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Blues',
    'Reflective',
    'Live Performances',
    array['tiny-desk', 'blues', 'country', 'folk', 'live'],
    'approved',
    'playable',
    true,
    false,
    2
  ),

  -- Jazz Lounge
  (
    'youtube_video',
    '8IcrlAYyA_o',
    'https://www.youtube.com/watch?v=8IcrlAYyA_o',
    'https://www.youtube.com/embed/8IcrlAYyA_o',
    'Kenny Garrett and Sounds From The Ancestors: Tiny Desk Concert',
    'https://i.ytimg.com/vi/8IcrlAYyA_o/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Uplifting',
    'Live Performances',
    array['tiny-desk', 'jazz', 'live', 'official'],
    'approved',
    'playable',
    true,
    true,
    3
  ),
  (
    'youtube_video',
    'xjVx3Wcoolo',
    'https://www.youtube.com/watch?v=xjVx3Wcoolo',
    'https://www.youtube.com/embed/xjVx3Wcoolo',
    'Julius Rodriguez: Tiny Desk Concert',
    'https://i.ytimg.com/vi/xjVx3Wcoolo/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Warm',
    'Live Performances',
    array['tiny-desk', 'jazz', 'piano', 'live'],
    'approved',
    'playable',
    true,
    false,
    4
  ),
  (
    'youtube_video',
    'x8WTPgeVPjg',
    'https://www.youtube.com/watch?v=x8WTPgeVPjg',
    'https://www.youtube.com/embed/x8WTPgeVPjg',
    'Kamasi Washington: Tiny Desk Concert',
    'https://i.ytimg.com/vi/x8WTPgeVPjg/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Epic',
    'Live Performances',
    array['tiny-desk', 'jazz', 'live', 'official'],
    'approved',
    'playable',
    true,
    true,
    5
  ),
  (
    'youtube_video',
    'IJm5sOkFSZ4',
    'https://www.youtube.com/watch?v=IJm5sOkFSZ4',
    'https://www.youtube.com/embed/IJm5sOkFSZ4',
    'Yu Sakai feat. TBN Trio: Tiny Desk Concert',
    'https://i.ytimg.com/vi/IJm5sOkFSZ4/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Bright',
    'Live Performances',
    array['tiny-desk', 'jazz', 'live'],
    'approved',
    'playable',
    true,
    false,
    6
  ),
  (
    'youtube_video',
    'oGTVoX7AaRc',
    'https://www.youtube.com/watch?v=oGTVoX7AaRc',
    'https://www.youtube.com/embed/oGTVoX7AaRc',
    'Robert Glasper Experiment: Tiny Desk Concert',
    'https://i.ytimg.com/vi/oGTVoX7AaRc/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Smooth',
    'Live Performances',
    array['tiny-desk', 'jazz', 'neo-soul', 'live'],
    'approved',
    'playable',
    true,
    false,
    7
  ),
  (
    'youtube_video',
    '3uiUHvET_jg',
    'https://www.youtube.com/watch?v=3uiUHvET_jg',
    'https://www.youtube.com/embed/3uiUHvET_jg',
    'Yo-Yo Ma: Tiny Desk Concert',
    'https://i.ytimg.com/vi/3uiUHvET_jg/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Reflective',
    'Live Performances',
    array['tiny-desk', 'classical', 'cello', 'live'],
    'approved',
    'playable',
    true,
    false,
    8
  ),

  -- Gospel Inspiration
  (
    'youtube_video',
    'tZWZ82Em-Q8',
    'https://www.youtube.com/watch?v=tZWZ82Em-Q8',
    'https://www.youtube.com/embed/tZWZ82Em-Q8',
    'Tye Tribbett: Tiny Desk Concert',
    'https://i.ytimg.com/vi/tZWZ82Em-Q8/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Gospel',
    'Inspirational',
    'Live Performances',
    array['tiny-desk', 'gospel', 'choir', 'live'],
    'approved',
    'playable',
    true,
    true,
    9
  ),
  (
    'youtube_video',
    't4p20PsP3cw',
    'https://www.youtube.com/watch?v=t4p20PsP3cw',
    'https://www.youtube.com/embed/t4p20PsP3cw',
    'CeCe Winans: Tiny Desk Concert',
    'https://i.ytimg.com/vi/t4p20PsP3cw/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Gospel',
    'Uplifting',
    'Live Performances',
    array['tiny-desk', 'gospel', 'live', 'official'],
    'approved',
    'playable',
    true,
    false,
    10
  ),

  -- Afro Soul TV
  (
    'youtube_video',
    '7rzGNL28Js0',
    'https://www.youtube.com/watch?v=7rzGNL28Js0',
    'https://www.youtube.com/embed/7rzGNL28Js0',
    'Angélique Kidjo: Tiny Desk Concert',
    'https://i.ytimg.com/vi/7rzGNL28Js0/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Celebratory',
    'Live Performances',
    array['tiny-desk', 'afro-soul', 'world', 'live'],
    'approved',
    'playable',
    true,
    true,
    11
  ),
  (
    'youtube_video',
    'YleSYAEYdrg',
    'https://www.youtube.com/watch?v=YleSYAEYdrg',
    'https://www.youtube.com/embed/YleSYAEYdrg',
    'Tems: Tiny Desk Concert',
    'https://i.ytimg.com/vi/YleSYAEYdrg/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Dreamy',
    'Live Performances',
    array['tiny-desk', 'afro-soul', 'rnb', 'live'],
    'approved',
    'playable',
    true,
    false,
    12
  ),
  (
    'youtube_video',
    'eo0UxS6lnjA',
    'https://www.youtube.com/watch?v=eo0UxS6lnjA',
    'https://www.youtube.com/embed/eo0UxS6lnjA',
    'Asake: Tiny Desk Concert',
    'https://i.ytimg.com/vi/eo0UxS6lnjA/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Energetic',
    'Live Performances',
    array['tiny-desk', 'afro-soul', 'afrobeats', 'live'],
    'approved',
    'playable',
    true,
    false,
    13
  ),
  (
    'youtube_video',
    'y1VKZUg8XZA',
    'https://www.youtube.com/watch?v=y1VKZUg8XZA',
    'https://www.youtube.com/embed/y1VKZUg8XZA',
    'The Free Nationals feat. Anderson .Paak, Chronixx & India Shawn: Tiny Desk Concert',
    'https://i.ytimg.com/vi/y1VKZUg8XZA/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Groovy',
    'Live Performances',
    array['tiny-desk', 'afro-soul', 'soul', 'live'],
    'approved',
    'playable',
    true,
    false,
    14
  ),

  -- Soul / R&B / Pop live sessions
  (
    'youtube_video',
    'ferZnZ0_rSM',
    'https://www.youtube.com/watch?v=ferZnZ0_rSM',
    'https://www.youtube.com/embed/ferZnZ0_rSM',
    'Anderson .Paak & The Free Nationals: Tiny Desk Concert',
    'https://i.ytimg.com/vi/ferZnZ0_rSM/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Funky',
    'Live Performances',
    array['tiny-desk', 'soul', 'hip-hop', 'live'],
    'approved',
    'playable',
    true,
    true,
    15
  ),
  (
    'youtube_video',
    '4cfmEgpOOZk',
    'https://www.youtube.com/watch?v=4cfmEgpOOZk',
    'https://www.youtube.com/embed/4cfmEgpOOZk',
    'Erykah Badu: Tiny Desk Concert',
    'https://i.ytimg.com/vi/4cfmEgpOOZk/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Moody',
    'Live Performances',
    array['tiny-desk', 'neo-soul', 'rnb', 'live'],
    'approved',
    'playable',
    true,
    false,
    16
  ),
  (
    'youtube_video',
    'hxxcEzM8r-4',
    'https://www.youtube.com/watch?v=hxxcEzM8r-4',
    'https://www.youtube.com/embed/hxxcEzM8r-4',
    'H.E.R.: Tiny Desk Concert',
    'https://i.ytimg.com/vi/hxxcEzM8r-4/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Intimate',
    'Live Performances',
    array['tiny-desk', 'rnb', 'live'],
    'approved',
    'playable',
    true,
    false,
    17
  ),
  (
    'youtube_video',
    '_KKjBeAfdPg',
    'https://www.youtube.com/watch?v=_KKjBeAfdPg',
    'https://www.youtube.com/embed/_KKjBeAfdPg',
    'Raphael Saadiq: Tiny Desk Concert',
    'https://i.ytimg.com/vi/_KKjBeAfdPg/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Smooth',
    'Live Performances',
    array['tiny-desk', 'soul', 'rnb', 'live'],
    'approved',
    'playable',
    true,
    false,
    18
  ),
  (
    'youtube_video',
    'DFiLdByWIDY',
    'https://www.youtube.com/watch?v=DFiLdByWIDY',
    'https://www.youtube.com/embed/DFiLdByWIDY',
    'Lizzo: Tiny Desk Concert',
    'https://i.ytimg.com/vi/DFiLdByWIDY/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Joyful',
    'Live Performances',
    array['tiny-desk', 'pop', 'live'],
    'approved',
    'playable',
    true,
    false,
    19
  ),
  (
    'youtube_video',
    'vWLJeqLPfSU',
    'https://www.youtube.com/watch?v=vWLJeqLPfSU',
    'https://www.youtube.com/embed/vWLJeqLPfSU',
    'Khruangbin: Tiny Desk Concert',
    'https://i.ytimg.com/vi/vWLJeqLPfSU/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Chill',
    'Live Performances',
    array['tiny-desk', 'instrumental', 'live'],
    'approved',
    'playable',
    true,
    false,
    20
  ),

  -- Country / Folk
  (
    'youtube_video',
    'Oxudnq20uRw',
    'https://www.youtube.com/watch?v=Oxudnq20uRw',
    'https://www.youtube.com/embed/Oxudnq20uRw',
    'Old Crow Medicine Show: Tiny Desk Concert',
    'https://i.ytimg.com/vi/Oxudnq20uRw/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Blues',
    'Roots',
    'Live Performances',
    array['tiny-desk', 'country', 'folk', 'live'],
    'approved',
    'playable',
    true,
    false,
    21
  ),
  (
    'youtube_video',
    'wuOJF8ecoY8',
    'https://www.youtube.com/watch?v=wuOJF8ecoY8',
    'https://www.youtube.com/embed/wuOJF8ecoY8',
    'Brent Cobb: Tiny Desk Concert',
    'https://i.ytimg.com/vi/wuOJF8ecoY8/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Blues',
    'Laid-back',
    'Live Performances',
    array['tiny-desk', 'country', 'live'],
    'approved',
    'playable',
    true,
    false,
    22
  ),
  (
    'youtube_video',
    'jtRXy0mGtTs',
    'https://www.youtube.com/watch?v=jtRXy0mGtTs',
    'https://www.youtube.com/embed/jtRXy0mGtTs',
    'Megan Moroney: Tiny Desk Concert',
    'https://i.ytimg.com/vi/jtRXy0mGtTs/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Blues',
    'Warm',
    'Live Performances',
    array['tiny-desk', 'country', 'live'],
    'approved',
    'playable',
    true,
    false,
    23
  ),
  (
    'youtube_video',
    'NC0-L6C-kmo',
    'https://www.youtube.com/watch?v=NC0-L6C-kmo',
    'https://www.youtube.com/embed/NC0-L6C-kmo',
    'Jakob Dylan: Tiny Desk Concert',
    'https://i.ytimg.com/vi/NC0-L6C-kmo/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Blues',
    'Reflective',
    'Live Performances',
    array['tiny-desk', 'folk', 'rock', 'live'],
    'approved',
    'playable',
    true,
    false,
    24
  ),

  -- Latin / Reggae
  (
    'youtube_video',
    'id28fCyYgIU',
    'https://www.youtube.com/watch?v=id28fCyYgIU',
    'https://www.youtube.com/embed/id28fCyYgIU',
    'Damian ''Jr. Gong'' Marley: Tiny Desk Concert',
    'https://i.ytimg.com/vi/id28fCyYgIU/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Roots',
    'Live Performances',
    array['tiny-desk', 'reggae', 'live'],
    'approved',
    'playable',
    true,
    false,
    25
  ),
  (
    'youtube_video',
    'tFdebIZJah8',
    'https://www.youtube.com/watch?v=tFdebIZJah8',
    'https://www.youtube.com/embed/tFdebIZJah8',
    'Chronixx: Tiny Desk Concert',
    'https://i.ytimg.com/vi/tFdebIZJah8/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Positive',
    'Live Performances',
    array['tiny-desk', 'reggae', 'live'],
    'approved',
    'playable',
    true,
    false,
    26
  ),
  (
    'youtube_video',
    '7EAM4pxxL4Y',
    'https://www.youtube.com/watch?v=7EAM4pxxL4Y',
    'https://www.youtube.com/embed/7EAM4pxxL4Y',
    'Ivy Queen: Tiny Desk Concert',
    'https://i.ytimg.com/vi/7EAM4pxxL4Y/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Bold',
    'Live Performances',
    array['tiny-desk', 'latin', 'reggaeton', 'live'],
    'approved',
    'playable',
    true,
    false,
    27
  ),
  (
    'youtube_video',
    'Y1f0WK9lsb0',
    'https://www.youtube.com/watch?v=Y1f0WK9lsb0',
    'https://www.youtube.com/embed/Y1f0WK9lsb0',
    'Machel Montano: Tiny Desk Concert',
    'https://i.ytimg.com/vi/Y1f0WK9lsb0/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Festive',
    'Live Performances',
    array['tiny-desk', 'soca', 'caribbean', 'live'],
    'approved',
    'playable',
    true,
    false,
    28
  ),
  (
    'youtube_video',
    'ouuPSxE1hK4',
    'https://www.youtube.com/watch?v=ouuPSxE1hK4',
    'https://www.youtube.com/embed/ouuPSxE1hK4',
    'Bad Bunny: Tiny Desk Concert',
    'https://i.ytimg.com/vi/ouuPSxE1hK4/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Energetic',
    'Live Performances',
    array['tiny-desk', 'latin', 'live'],
    'approved',
    'playable',
    true,
    false,
    29
  ),
  (
    'youtube_video',
    'P_yPDiMN3uk',
    'https://www.youtube.com/watch?v=P_yPDiMN3uk',
    'https://www.youtube.com/embed/P_yPDiMN3uk',
    'Maluma: Tiny Desk Concert',
    'https://i.ytimg.com/vi/P_yPDiMN3uk/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Afro Soul',
    'Romantic',
    'Live Performances',
    array['tiny-desk', 'latin', 'live'],
    'approved',
    'playable',
    true,
    false,
    30
  ),

  -- Hip-Hop + BBC live
  (
    'youtube_video',
    'iU0_cYjm8HE',
    'https://www.youtube.com/watch?v=iU0_cYjm8HE',
    'https://www.youtube.com/embed/iU0_cYjm8HE',
    'Rakim: Tiny Desk Concert',
    'https://i.ytimg.com/vi/iU0_cYjm8HE/hqdefault.jpg',
    'NPR Music',
    'Music',
    'Jazz',
    'Classic',
    'Live Performances',
    array['tiny-desk', 'hip-hop', 'live'],
    'approved',
    'playable',
    true,
    false,
    31
  ),
  (
    'youtube_video',
    '5XNeYtmpQrQ',
    'https://www.youtube.com/watch?v=5XNeYtmpQrQ',
    'https://www.youtube.com/embed/5XNeYtmpQrQ',
    'Little Simz - Lonely (Live At The BBC)',
    'https://i.ytimg.com/vi/5XNeYtmpQrQ/hqdefault.jpg',
    'BBC Music',
    'Music',
    'Jazz',
    'Intense',
    'Live Performances',
    array['bbc', 'live', 'hip-hop', 'official'],
    'approved',
    'playable',
    true,
    false,
    32
  ),

  -- Documentary Nights (NASA public domain + music/creativity talks)
  (
    'youtube_video',
    'CFrP6QfbC2g',
    'https://www.youtube.com/watch?v=CFrP6QfbC2g',
    'https://www.youtube.com/embed/CFrP6QfbC2g',
    'One Year on Earth – Seen From 1 Million Miles',
    'https://i.ytimg.com/vi/CFrP6QfbC2g/hqdefault.jpg',
    'NASA Goddard',
    'Documentary',
    'Jazz',
    'Awe',
    'Documentaries',
    array['nasa', 'public-domain', 'space', 'documentary'],
    'approved',
    'playable',
    true,
    true,
    33
  ),
  (
    'youtube_video',
    'f-2F3QD_UyA',
    'https://www.youtube.com/watch?v=f-2F3QD_UyA',
    'https://www.youtube.com/embed/f-2F3QD_UyA',
    'Cosmic Cycles: Earth, Our Home (NASA Space Symphony)',
    'https://i.ytimg.com/vi/f-2F3QD_UyA/hqdefault.jpg',
    'NASA Goddard',
    'Documentary',
    'Jazz',
    'Cinematic',
    'Documentaries',
    array['nasa', 'orchestral', 'space', 'documentary'],
    'approved',
    'playable',
    true,
    false,
    34
  ),
  (
    'youtube_video',
    'ElxVZL526o8',
    'https://www.youtube.com/watch?v=ElxVZL526o8',
    'https://www.youtube.com/embed/ElxVZL526o8',
    '4K Earth Views Extended Cut for Earth Day 2021',
    'https://i.ytimg.com/vi/ElxVZL526o8/hqdefault.jpg',
    'NASA',
    'Documentary',
    'Jazz',
    'Calm',
    'Documentaries',
    array['nasa', 'space', '4k', 'documentary'],
    'approved',
    'playable',
    true,
    false,
    35
  ),
  (
    'youtube_video',
    'yQNEKTOL_oA',
    'https://www.youtube.com/watch?v=yQNEKTOL_oA',
    'https://www.youtube.com/embed/yQNEKTOL_oA',
    'Earth from Space in 4K – Expedition 65 Edition',
    'https://i.ytimg.com/vi/yQNEKTOL_oA/hqdefault.jpg',
    'NASA',
    'Documentary',
    'Jazz',
    'Serene',
    'Documentaries',
    array['nasa', 'iss', 'space', 'documentary'],
    'approved',
    'playable',
    true,
    false,
    36
  ),
  (
    'youtube_video',
    'oy25A7vnigg',
    'https://www.youtube.com/watch?v=oy25A7vnigg',
    'https://www.youtube.com/embed/oy25A7vnigg',
    'Sting: How I started writing songs again | TED',
    'https://i.ytimg.com/vi/oy25A7vnigg/hqdefault.jpg',
    'TED',
    'Education',
    'Gospel',
    'Reflective',
    'Documentaries',
    array['ted', 'songwriting', 'interview', 'official'],
    'approved',
    'playable',
    true,
    false,
    37
  ),
  (
    'youtube_video',
    'H3TF-hI7zKc',
    'https://www.youtube.com/watch?v=H3TF-hI7zKc',
    'https://www.youtube.com/embed/H3TF-hI7zKc',
    'How sampling transformed music | Mark Ronson | TED',
    'https://i.ytimg.com/vi/H3TF-hI7zKc/hqdefault.jpg',
    'TED',
    'Education',
    'Gospel',
    'Curious',
    'Documentaries',
    array['ted', 'music-history', 'sampling', 'official'],
    'approved',
    'playable',
    true,
    false,
    38
  ),
  (
    'youtube_video',
    'GRgqbsP_-uw',
    'https://www.youtube.com/watch?v=GRgqbsP_-uw',
    'https://www.youtube.com/embed/GRgqbsP_-uw',
    'Why Do You Love Your Favorite Songs? | Scarlet Keys | TED',
    'https://i.ytimg.com/vi/GRgqbsP_-uw/hqdefault.jpg',
    'TED',
    'Education',
    'Gospel',
    'Thoughtful',
    'Documentaries',
    array['ted', 'songwriting', 'education', 'official'],
    'approved',
    'playable',
    true,
    false,
    39
  ),
  (
    'youtube_video',
    'N7wF2AdVy2Q',
    'https://www.youtube.com/watch?v=N7wF2AdVy2Q',
    'https://www.youtube.com/embed/N7wF2AdVy2Q',
    'How frustration can make us more creative | Tim Harford | TED',
    'https://i.ytimg.com/vi/N7wF2AdVy2Q/hqdefault.jpg',
    'TED',
    'Education',
    'Jazz',
    'Inspiring',
    'Documentaries',
    array['ted', 'creativity', 'keith-jarrett', 'official'],
    'approved',
    'playable',
    true,
    false,
    40
  )

on conflict (source_type, source_id) do update set
  source_url = excluded.source_url,
  embed_url = excluded.embed_url,
  title = excluded.title,
  thumbnail_url = excluded.thumbnail_url,
  channel_name = excluded.channel_name,
  category = excluded.category,
  genre = excluded.genre,
  mood = excluded.mood,
  format = excluded.format,
  tags = excluded.tags,
  status = excluded.status,
  playback_status = excluded.playback_status,
  is_active = excluded.is_active,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  updated_at = now();

-- Optional: refresh PostgREST schema cache after seeding
notify pgrst, 'reload schema';
