export const AUDIOBOOK_EXPANSION_TARGET = 150_000;

export const AUDIOBOOK_EXPANSION_DEFAULT_BATCH_SIZE = 1000;

export const AUDIOBOOK_EXPANSION_PROMOTION_BATCH_SIZE = 250;

export const AUDIOBOOK_EXPANSION_CANDIDATE_BATCH_MIN = 500;

export const AUDIOBOOK_EXPANSION_CANDIDATE_BATCH_MAX = 2000;

export const AUDIOBOOK_CHAPTER_PAGE_SIZE = 40;

export const AUDIOBOOK_PLAYABILITY_TIMEOUT_MS = 12_000;

export const AUDIOBOOK_PLAYABILITY_MAX_REDIRECTS = 3;
