export type TvSourceHealth="HEALTHY"|"DEGRADED"|"TEMPORARY_FAILURE"|"DEAD"|"GEO_RESTRICTED"|"AUTH_REQUIRED"|"DRM"|"IDENTITY_MISMATCH";
export type TvSourceRole="PRIMARY"|"FALLBACK_1"|"FALLBACK_2"|"HISTORICAL";
export type TvRecoveryReason="SOURCE_DEAD"|"SOURCE_DEGRADED"|"IDENTITY_UNRESOLVED"|"NO_SOURCE"|"GEO_RESTRICTED"|"AUTH_REQUIRED"|"DRM"|"REBRAND_SUSPECTED"|"DUPLICATE_SUSPECTED";
export type TvSourceState={health:TvSourceHealth;consecutiveFailures:number;successCount:number;failureCount:number;quarantined:boolean;nextCheckAt:string;lastSuccessAt:string|null;lastFailureAt:string|null};
export type TvProbeEvidence={playable:boolean;reason:string;identityMatch?:boolean;geoRestricted?:boolean;authRequired?:boolean;drm?:boolean};
const minutes=(iso:string,value:number)=>new Date(Date.parse(iso)+value*60000).toISOString();
export function classifyTvProbeFailure(e:TvProbeEvidence):TvSourceHealth{if(e.identityMatch===false)return"IDENTITY_MISMATCH";if(e.drm)return"DRM";if(e.authRequired)return"AUTH_REQUIRED";if(e.geoRestricted)return"GEO_RESTRICTED";return"TEMPORARY_FAILURE"}
export function applyTvSourceEvidence(previous:TvSourceState,evidence:TvProbeEvidence,now=new Date().toISOString()):TvSourceState{if(evidence.playable&&evidence.identityMatch!==false)return{health:"HEALTHY",consecutiveFailures:0,successCount:previous.successCount+1,failureCount:previous.failureCount,quarantined:false,nextCheckAt:minutes(now,360),lastSuccessAt:now,lastFailureAt:previous.lastFailureAt};const failures=previous.consecutiveFailures+1;let health=classifyTvProbeFailure(evidence),quarantined=false,delay=15;if(["IDENTITY_MISMATCH","DRM","AUTH_REQUIRED"].includes(health)){quarantined=true;delay=1440}else if(health==="GEO_RESTRICTED")delay=720;else if(failures>=5){health="DEAD";quarantined=true;delay=1440}else if(failures>=3){health="TEMPORARY_FAILURE";delay=60}else{health="DEGRADED";delay=15}return{health,consecutiveFailures:failures,successCount:previous.successCount,failureCount:previous.failureCount+1,quarantined,nextCheckAt:minutes(now,delay),lastSuccessAt:previous.lastSuccessAt,lastFailureAt:now}}
export type RankedTvSource={id:string;health:TvSourceHealth;role:TvSourceRole;priority:number;isHttps:boolean;startupMs:number|null;reliabilityScore:number;quarantined:boolean;platformPlayable:boolean};
const roleWeight:Record<TvSourceRole,number>={PRIMARY:400,FALLBACK_1:300,FALLBACK_2:200,HISTORICAL:0};
const healthWeight:Record<TvSourceHealth,number>={HEALTHY:500,DEGRADED:250,TEMPORARY_FAILURE:100,GEO_RESTRICTED:50,AUTH_REQUIRED:-500,DRM:-500,IDENTITY_MISMATCH:-1000,DEAD:-1000};
export function rankTvSources(sources:RankedTvSource[]){return sources.filter(x=>!x.quarantined&&x.platformPlayable&&!['DEAD','DRM','AUTH_REQUIRED','IDENTITY_MISMATCH'].includes(x.health)).sort((a,b)=>score(b)-score(a)||a.id.localeCompare(b.id))}
function score(x:RankedTvSource){return healthWeight[x.health]+roleWeight[x.role]+x.priority+x.reliabilityScore+(x.isHttps?25:0)-Math.min(100,Math.round((x.startupMs??5000)/100))}
export function chooseTvFailover(sources:RankedTvSource[],failedIds:string[]=[]){return rankTvSources(sources).find(x=>!failedIds.includes(x.id))??null}
export function recoveryReasonForState(state:TvSourceState):TvRecoveryReason|null{if(state.health==='DEAD')return'SOURCE_DEAD';if(state.health==='DEGRADED'||state.health==='TEMPORARY_FAILURE')return'SOURCE_DEGRADED';if(state.health==='GEO_RESTRICTED')return'GEO_RESTRICTED';if(state.health==='AUTH_REQUIRED')return'AUTH_REQUIRED';if(state.health==='DRM')return'DRM';if(state.health==='IDENTITY_MISMATCH')return'REBRAND_SUSPECTED';return null}
