import { useEffect, useRef, useState } from 'react'
import { useDesktopPlayback,useDesktopPlaybackProgress } from '../../context/DesktopPlaybackProvider'
import { currentLocalCrossplayConfig,LocalCrossplayClient } from '../../services/localCrossplayRuntime'
const PERIOD_MS=20_000,INSTALL_KEY='hidden-tunes.crossplay.local-install.v1'
function installationId(){let id=localStorage.getItem(INSTALL_KEY);if(!id){const b=new Uint8Array(24);crypto.getRandomValues(b);id=Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');localStorage.setItem(INSTALL_KEY,id)}return id}
function fixtureType(id:string){if(id.startsWith('podcast'))return'podcast';if(id.startsWith('audiobook'))return'audiobook';if(id.startsWith('lecture'))return'lecture';if(id.startsWith('motivational'))return'motivational';if(id.startsWith('radio'))return'radio';if(id.startsWith('tv-'))return'tv';return'music'}
export function DesktopLocalCrossplayBridge(){if(!import.meta.env.DEV)return null;const config=currentLocalCrossplayConfig();if(!config.enabled)return null;return <EnabledLocalBridge config={config}/>}
function EnabledLocalBridge({config}:{config:ReturnType<typeof currentLocalCrossplayConfig>}){
 const {currentTrack,isPlaying}=useDesktopPlayback(),{positionSeconds,durationSeconds}=useDesktopPlaybackProgress();const [items,setItems]=useState<unknown[]>([]);const state=useRef({track:currentTrack,positionSeconds,durationSeconds});const {origin,identity,jwt}=config;
 useEffect(()=>{state.current={track:currentTrack,positionSeconds,durationSeconds}},[currentTrack,positionSeconds,durationSeconds]);
 useEffect(()=>{const client=new LocalCrossplayClient({enabled:true,reason:'local_only',origin,identity,jwt});let active=true,timer:number|undefined,deviceId='',version=0,lastPosition=-1;const flush=async(force=false)=>{const s=state.current;if(!active||!deviceId||!s.track?.id)return;const pos=Math.floor(s.positionSeconds*1000);if(!force&&Math.abs(pos-lastPosition)<10_000)return;lastPosition=pos;try{const type=fixtureType(String(s.track.id));const row=await client.writeProgress({deviceId,type,contentId:`fixture-${type}-current`,positionMs:pos,durationMs:Math.floor(s.durationSeconds*1000),expectedVersion:version}) as {version?:number};version=Number(row?.version||version);const next=await client.listContinuations();if(active)setItems(Array.isArray(next)?next:[])}catch{/* bounded next-event retry; playback is never blocked */}};queueMicrotask(()=>{void client.registerDevice({publicId:installationId(),name:'Desktop Local Fixture',platform:'desktop',deviceClass:'computer'}).then((d)=>{if(!active)return;deviceId=String((d as {id?:string})?.id||'');return flush(true)}).catch(()=>{})});if(isPlaying)timer=window.setInterval(()=>void flush(false),PERIOD_MS);const hidden=()=>{if(document.visibilityState==='hidden')void flush(true)},exit=()=>void flush(true);document.addEventListener('visibilitychange',hidden);window.addEventListener('beforeunload',exit);return()=>{if(timer)window.clearInterval(timer);document.removeEventListener('visibilitychange',hidden);window.removeEventListener('beforeunload',exit);void flush(true);active=false}},[origin,identity,jwt,isPlaying,currentTrack?.id]);
 return <aside className="crossplay-local-test" aria-label="Cross Play local test"><strong>Cross Play — Local Test Only</strong><span>{items.length} bounded continuation fixture{items.length===1?'':'s'}</span></aside>
}
